In [1]:
import os
import json
import re
import numpy as np
import pandas as pd
import torch
from tqdm import tqdm
from datasets import Dataset
from peft import LoraConfig, TaskType, get_peft_model
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    TrainingArguments,
    Trainer,
    DataCollatorForSeq2Seq
)

In [2]:
# ====================
# 0. 基础配置
# ====================
model_name = "./model/Mistral-7B/mistralai/Mistral-7B-Instruct-v0___3/"
output_dir = "./output/VLE_LLM/等温等压/随机划分/random_72_aug"

In [3]:
# ====================
# 1. 加载 tokenizer 和模型
# ====================
device = "cuda" if torch.cuda.is_available() else "cpu"
dtype = torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float16
tokenizer = AutoTokenizer.from_pretrained(model_name)
# Mistral 特殊设置：确保 pad_token 存在且方向正确
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right" 

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    dtype=dtype,
    device_map="auto"
)
model.config.use_cache = False
model.enable_input_require_grads()

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

The module name  (originally ) is not a valid Python identifier. Please rename the original module to avoid import issues.

In [4]:
MAX_LENGTH = 1024
SYSTEM_PROMPT = """You are an expert in thermodynamics and vapor-liquid equilibrium.
Your task is to predict equilibrium properties of binary mixtures from molecular structures and operating conditions.
Return only the requested numerical results.
"""
def build_messages(user_input, assistant_output=None):
    # 将System Prompt直接拼接到User内容
    user_content = SYSTEM_PROMPT.strip() + "\n\n" + user_input.strip()
    messages = [
        {
            "role": "user",
            "content": user_content
        }
    ]
    if assistant_output is not None:
        messages.append(
            {
                "role": "assistant",
                "content": assistant_output
            }
        )
    return messages
def process_func(example):
    # 完整聊天
    messages = build_messages(
        example["input"],
        example["output"]
    )
    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=False
    )
    enc = tokenizer(
        text,
        truncation=True,
        max_length=MAX_LENGTH,
        add_special_tokens=False,
    )
    input_ids = enc["input_ids"]
    attention_mask = enc["attention_mask"]
    labels = input_ids.copy()
    # prompt（只有User）
    prompt_messages = build_messages(
        example["input"],
        None
    )
    prompt_text = tokenizer.apply_chat_template(
        prompt_messages,
        tokenize=False,
        add_generation_prompt=False
    )
    prompt_ids = tokenizer(
        prompt_text,
        truncation=True,
        max_length=MAX_LENGTH,
        add_special_tokens=False
    )["input_ids"]
    prompt_len = len(prompt_ids)
    # Mask User部分
    labels[:prompt_len] = [-100] * prompt_len
    return {
        "input_ids": input_ids,
        "attention_mask": attention_mask,
        "labels": labels,
    }

In [5]:
# ====================
# 3. 数据处理
# ====================
train_df = pd.read_json("./随机划分/训练文件/train_data_72_aug.jsonl", lines=True)
train_ds = Dataset.from_pandas(train_df)
train_dataset = train_ds.map(process_func, remove_columns=train_ds.column_names)

Map:   0%|          | 0/4952 [00:00<?, ? examples/s]

In [6]:
# ====================
# 4. LoRA 配置
# ====================
config = LoraConfig(
    task_type=TaskType.CAUSAL_LM,
    target_modules=[
        "q_proj", "k_proj", "v_proj", "o_proj", 
        "gate_proj", "up_proj", "down_proj"
    ],
    inference_mode=False,
    r=64,
    lora_alpha=128,
    lora_dropout=0.05,
    bias="none"
)
model = get_peft_model(model, config)
model.print_trainable_parameters()

trainable params: 167,772,160 || all params: 7,415,795,712 || trainable%: 2.2624

In [7]:
# ====================
# 5. 训练参数
# ====================
args = TrainingArguments(
    output_dir=output_dir,
    per_device_train_batch_size=4,
    gradient_accumulation_steps=8,
    
    num_train_epochs=7,
    
    learning_rate=8e-6,
    weight_decay=0.03,
    
    lr_scheduler_type="cosine",
    warmup_steps=0,
    
    logging_steps=50,
    save_steps=100,
    #eval_steps=100,
    #eval_strategy="steps",
    save_total_limit=2,
    
    #load_best_model_at_end=True,
    #metric_for_best_model="eval_loss",
    bf16=True,
    gradient_checkpointing=True,
    report_to="none",
    optim="adamw_torch"
)

In [8]:
# ====================
# 6. Trainer 执行
# ====================
trainer = Trainer(
    model=model,
    args=args,
    train_dataset=train_dataset,
    #eval_dataset=eval_dataset,
    data_collator=DataCollatorForSeq2Seq(tokenizer=tokenizer, padding=True),
)
trainer.train()

The model is already on multiple devices. Skipping the move to device specified in `args`.

TrainOutput(global_step=1085, training_loss=0.29070114408220565, metrics={'train_runtime': 2676.4437, 'train_samples_per_second': 12.952, 'train_steps_per_second': 0.405, 'total_flos': 2.897560657278075e+17, 'train_loss': 0.29070114408220565, 'epoch': 7.0})

In [9]:
def get_task_type(input_text):
    """
    根据input自动判断任务类型
    """
    text = input_text.lower()
    if "isobaric" in text:
        return "isobaric"
    elif "isothermal" in text:
        return "isothermal"
    else:
        raise ValueError("Cannot determine task type.")
def predict(example, model, tokenizer):
    model.eval()
    messages = build_messages(
        user_input=example["input"],
        assistant_output=None
    )
    inputs = tokenizer.apply_chat_template(
        messages,
        add_generation_prompt=True,
        tokenize=True,
        return_tensors="pt",
        return_dict=True
    ).to(device)
    input_length = inputs["input_ids"].shape[1]
    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=64,
            do_sample=False,
            pad_token_id=tokenizer.pad_token_id,
            eos_token_id=tokenizer.eos_token_id
        )
    response = tokenizer.decode(
        outputs[0][input_length:],
        skip_special_tokens=True
    ).strip()
    return response
def parse_vle_output(text, task_type):
    text = str(text)
    y1 = None
    T = None
    P = None
    m = re.search(
        r"Vapor-phase mole fraction of component 1\s*:\s*([-+]?\d*\.?\d+)",
        text,
        re.I
    )
    if m:
        y1 = float(m.group(1))
    if task_type == "isobaric":
        m = re.search(
            r"Equilibrium temperature\s*:\s*([-+]?\d*\.?\d+)",
            text,
            re.I
        )
        if m:
            T = float(m.group(1))
    else:
        m = re.search(
            r"Equilibrium pressure\s*:\s*([-+]?\d*\.?\d+)",
            text,
            re.I
        )
        if m:
            P = float(m.group(1))
    return y1, T, P
def batch_predict_mixed_vle(
    test_file_path,
    save_path,
    max_samples=None
):
    results = []
    # Overall
    true_y1_all = []
    pred_y1_all = []
    # Isobaric
    true_y1_isoB = []
    pred_y1_isoB = []
    true_T_isoB = []
    pred_T_isoB = []
    # Isothermal
    true_y1_isoT = []
    pred_y1_isoT = []
    true_P_isoT = []
    pred_P_isoT = []
    with open(test_file_path, "r", encoding="utf-8") as f:
        lines = [line for line in f if line.strip()]
    if max_samples is not None:
        lines = lines[:max_samples]
    print(f"🚀 Total samples: {len(lines)}")
    model.eval()
    for i, line in enumerate(tqdm(lines)):
        try:
            data = json.loads(line)
            # 自动判断任务
            task_type = get_task_type(data["input"])
            # 模型预测
            raw_pred = predict(
                data,
                model,
                tokenizer
            )
            # 解析预测
            pred_y1, pred_T, pred_P = parse_vle_output(
                raw_pred,
                task_type
            )
            # 解析真实值
            true_y1, true_T, true_P = parse_vle_output(
                data["output"],
                task_type
            )
            #############################
            # 误差
            #############################
            err_y1 = None
            err_T = None
            err_P = None
            if pred_y1 is not None and true_y1 is not None:
                err_y1 = abs(pred_y1 - true_y1)
                true_y1_all.append(true_y1)
                pred_y1_all.append(pred_y1)
                if task_type == "isobaric":
                    true_y1_isoB.append(true_y1)
                    pred_y1_isoB.append(pred_y1)
                else:
                    true_y1_isoT.append(true_y1)
                    pred_y1_isoT.append(pred_y1)
            if task_type == "isobaric":
                if pred_T is not None and true_T is not None:
                    err_T = abs(pred_T - true_T)
                    true_T_isoB.append(true_T)
                    pred_T_isoB.append(pred_T)
            else:
                if pred_P is not None and true_P is not None:
                    err_P = abs(pred_P - true_P)
                    true_P_isoT.append(true_P)
                    pred_P_isoT.append(pred_P)

            #############################
            # 保存结果
            #############################
            result = {
                "task_type": task_type,
                "input": data["input"],
                "true_output": data["output"],
                "raw_prediction": raw_pred,
                "true_Y1": true_y1,
                "pred_Y1": pred_y1,
                "err_Y1": err_y1,
                "true_T": true_T,
                "pred_T": pred_T,
                "err_T": err_T,
                "true_P": true_P,
                "pred_P": pred_P,
                "err_P": err_P

            }
            results.append(result)
            #########################################
            print("\n" + "=" * 100)
            print(f"[{i+1}/{len(lines)}]")
            print("Task :", task_type)
            print("\nInput:")
            print(data["input"])
            print("\nGround Truth:")
            print(data["output"])
            print("\nPrediction:")
            print(raw_pred)
            print("\nParsed:")
            print(
                f"Y1 : {true_y1} -> {pred_y1}"
            )
            if task_type == "isobaric":
                print(
                    f"T  : {true_T} -> {pred_T}"
                )
            else:
                print(
                    f"P  : {true_P} -> {pred_P}"
                )
        except Exception as e:
            print(f"Sample {i+1} failed: {e}")
    #########################################
    # 保存json
    #########################################
    with open(save_path, "w", encoding="utf-8") as f:
        json.dump(
            results,
            f,
            indent=2,
            ensure_ascii=False
        )
    print(f"\nResults saved to {save_path}")
    #########################################
    # Metrics
    #########################################
    def print_metrics(name, y_true, y_pred):
        if len(y_true) == 0:
            print(f"\n{name}: No valid samples")
            return
        y_true = np.array(y_true)
        y_pred = np.array(y_pred)
        mae = np.mean(np.abs(y_true - y_pred))
        rmse = np.sqrt(np.mean((y_true - y_pred) ** 2))
        r2 = r2_score(y_true, y_pred)
        print("\n" + "=" * 60)
        print(name)
        print(f"Samples : {len(y_true)}")
        print(f"MAE  : {mae:.6f}")
        print(f"RMSE : {rmse:.6f}")
        print(f"R²   : {r2:.6f}")
    print_metrics(
        "Overall Y1",
        true_y1_all,
        pred_y1_all
    )
    print_metrics(
        "Isobaric Y1",
        true_y1_isoB,
        pred_y1_isoB
    )
    print_metrics(
        "Isobaric Temperature",
        true_T_isoB,
        pred_T_isoB
    )
    print_metrics(
        "Isothermal Y1",
        true_y1_isoT,
        pred_y1_isoT
    )
    print_metrics(
        "Isothermal Pressure",
        true_P_isoT,
        pred_P_isoT
    )
    return results
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

In [10]:
test_file_path = "./随机划分/训练文件/test_data_72.jsonl"
save_path = "./随机划分/结果文件/test_data_72.json"
results_all = batch_predict_mixed_vle(
    test_file_path=test_file_path,
    save_path=save_path,
    max_samples= None
)

🚀 Total samples: 276

  0%|          | 1/276 [00:01<09:08,  1.99s/it]

====================================================================================================
[1/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: CC(=O)O
Operating pressure: 16.670 kPa
Liquid-phase mole fraction of component 1: 0.476
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.586
Equilibrium temperature: 333.08 K

Prediction:
Vapor-phase mole fraction of component 1: 0.580
Equilibrium temperature: 334.99 K

Parsed:
Y1 : 0.586 -> 0.58
T  : 333.08 -> 334.99

  1%|          | 2/276 [00:03<08:33,  1.87s/it]

====================================================================================================
[2/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(C)O
Component 2 SMILES: O
Operating pressure: 25.330 kPa
Liquid-phase mole fraction of component 1: 0.084
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.484
Equilibrium temperature: 325.14 K

Prediction:
Vapor-phase mole fraction of component 1: 0.469
Equilibrium temperature: 324.99 K

Parsed:
Y1 : 0.484 -> 0.469
T  : 325.14 -> 324.99

  1%|          | 3/276 [00:05<08:20,  1.84s/it]

====================================================================================================
[3/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: CCCC=O
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.713
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.751
Equilibrium temperature: 336.75 K

Prediction:
Vapor-phase mole fraction of component 1: 0.650
Equilibrium temperature: 334.15 K

Parsed:
Y1 : 0.751 -> 0.65
T  : 336.75 -> 334.15

  1%|▏         | 4/276 [00:07<08:14,  1.82s/it]

====================================================================================================
[4/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(C=O)O
Component 2 SMILES: CO
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.849
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.788
Equilibrium temperature: 327.65 K

Prediction:
Vapor-phase mole fraction of component 1: 0.774
Equilibrium temperature: 328.55 K

Parsed:
Y1 : 0.788 -> 0.774
T  : 327.65 -> 328.55

  2%|▏         | 5/276 [00:09<08:09,  1.81s/it]

====================================================================================================
[5/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: C(C(CO)O)O
Operating pressure: 48.000 kPa
Liquid-phase mole fraction of component 1: 0.420
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.982
Equilibrium temperature: 433.15 K

Prediction:
Vapor-phase mole fraction of component 1: 0.985
Equilibrium temperature: 433.15 K

Parsed:
Y1 : 0.982 -> 0.985
T  : 433.15 -> 433.15

  2%|▏         | 6/276 [00:10<08:05,  1.80s/it]

====================================================================================================
[6/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: C(C(CO)O)O
Operating pressure: 6.670 kPa
Liquid-phase mole fraction of component 1: 0.800
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 1.000
Equilibrium temperature: 316.85 K

Prediction:
Vapor-phase mole fraction of component 1: 1.000
Equilibrium temperature: 319.65 K

Parsed:
Y1 : 1.0 -> 1.0
T  : 316.85 -> 319.65

  3%|▎         | 7/276 [00:12<08:03,  1.80s/it]

====================================================================================================
[7/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(C=O)O
Component 2 SMILES: CO
Operating pressure: 79.990 kPa
Liquid-phase mole fraction of component 1: 0.726
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.708
Equilibrium temperature: 320.45 K

Prediction:
Vapor-phase mole fraction of component 1: 0.702
Equilibrium temperature: 320.75 K

Parsed:
Y1 : 0.708 -> 0.702
T  : 320.45 -> 320.75

  3%|▎         | 8/276 [00:14<08:00,  1.79s/it]

====================================================================================================
[8/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(C)O
Component 2 SMILES: O
Operating pressure: 12.670 kPa
Liquid-phase mole fraction of component 1: 0.388
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.571
Equilibrium temperature: 310.02 K

Prediction:
Vapor-phase mole fraction of component 1: 0.576
Equilibrium temperature: 309.49 K

Parsed:
Y1 : 0.571 -> 0.576
T  : 310.02 -> 309.49

  3%|▎         | 9/276 [00:16<07:58,  1.79s/it]

====================================================================================================
[9/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(=O)O
Component 2 SMILES: O
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.840
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.752
Equilibrium temperature: 384.55 K

Prediction:
Vapor-phase mole fraction of component 1: 0.750
Equilibrium temperature: 383.15 K

Parsed:
Y1 : 0.752 -> 0.75
T  : 384.55 -> 383.15

  4%|▎         | 10/276 [00:18<07:56,  1.79s/it]

====================================================================================================
[10/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(=O)C
Component 2 SMILES: O
Operating pressure: 66.660 kPa
Liquid-phase mole fraction of component 1: 0.948
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.965
Equilibrium temperature: 318.25 K

Prediction:
Vapor-phase mole fraction of component 1: 0.966
Equilibrium temperature: 319.65 K

Parsed:
Y1 : 0.965 -> 0.966
T  : 318.25 -> 319.65

  4%|▍         | 11/276 [00:19<07:54,  1.79s/it]

====================================================================================================
[11/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: C=CCO
Component 2 SMILES: O
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.692
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.575
Equilibrium temperature: 363.19 K

Prediction:
Vapor-phase mole fraction of component 1: 0.564
Equilibrium temperature: 363.15 K

Parsed:
Y1 : 0.575 -> 0.564
T  : 363.19 -> 363.15

  4%|▍         | 12/276 [00:21<07:52,  1.79s/it]

====================================================================================================
[12/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: CN(C)C=O
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.843
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.953
Equilibrium temperature: 375.65 K

Prediction:
Vapor-phase mole fraction of component 1: 0.956
Equilibrium temperature: 375.95 K

Parsed:
Y1 : 0.953 -> 0.956
T  : 375.65 -> 375.95

  5%|▍         | 13/276 [00:23<07:51,  1.79s/it]

====================================================================================================
[13/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: C(CN)N
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.757
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.900
Equilibrium temperature: 385.55 K

Prediction:
Vapor-phase mole fraction of component 1: 0.898
Equilibrium temperature: 386.85 K

Parsed:
Y1 : 0.9 -> 0.898
T  : 385.55 -> 386.85

  5%|▌         | 14/276 [00:25<07:49,  1.79s/it]

====================================================================================================
[14/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: O
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.545
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.673
Equilibrium temperature: 352.65 K

Prediction:
Vapor-phase mole fraction of component 1: 0.668
Equilibrium temperature: 352.25 K

Parsed:
Y1 : 0.673 -> 0.668
T  : 352.65 -> 352.25

  5%|▌         | 15/276 [00:27<07:47,  1.79s/it]

====================================================================================================
[15/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: CCC(=O)O
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.153
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.512
Equilibrium temperature: 392.75 K

Prediction:
Vapor-phase mole fraction of component 1: 0.460
Equilibrium temperature: 393.05 K

Parsed:
Y1 : 0.512 -> 0.46
T  : 392.75 -> 393.05

  6%|▌         | 16/276 [00:28<07:46,  1.79s/it]

====================================================================================================
[16/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: C(=O)O
Component 2 SMILES: O
Operating pressure: 26.660 kPa
Liquid-phase mole fraction of component 1: 0.583
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.656
Equilibrium temperature: 344.25 K

Prediction:
Vapor-phase mole fraction of component 1: 0.622
Equilibrium temperature: 344.95 K

Parsed:
Y1 : 0.656 -> 0.622
T  : 344.25 -> 344.95

  6%|▌         | 17/276 [00:30<07:45,  1.80s/it]

====================================================================================================
[17/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(C)O
Component 2 SMILES: O
Operating pressure: 12.670 kPa
Liquid-phase mole fraction of component 1: 0.820
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.766
Equilibrium temperature: 309.54 K

Prediction:
Vapor-phase mole fraction of component 1: 0.776
Equilibrium temperature: 309.49 K

Parsed:
Y1 : 0.766 -> 0.776
T  : 309.54 -> 309.49

  7%|▋         | 18/276 [00:32<07:43,  1.80s/it]

====================================================================================================
[18/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: O
Operating pressure: 98.070 kPa
Liquid-phase mole fraction of component 1: 0.044
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.300
Equilibrium temperature: 364.05 K

Prediction:
Vapor-phase mole fraction of component 1: 0.318
Equilibrium temperature: 362.35 K

Parsed:
Y1 : 0.3 -> 0.318
T  : 364.05 -> 362.35

  7%|▋         | 19/276 [00:34<07:41,  1.80s/it]

====================================================================================================
[19/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CC(C)CCO
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.643
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.865
Equilibrium temperature: 378.15 K

Prediction:
Vapor-phase mole fraction of component 1: 0.846
Equilibrium temperature: 378.15 K

Parsed:
Y1 : 0.865 -> 0.846
T  : 378.15 -> 378.15

  7%|▋         | 20/276 [00:36<07:40,  1.80s/it]

====================================================================================================
[20/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: C(CO)O
Operating pressure: 1.330 kPa
Liquid-phase mole fraction of component 1: 0.145
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.950
Equilibrium temperature: 326.65 K

Prediction:
Vapor-phase mole fraction of component 1: 0.942
Equilibrium temperature: 335.15 K

Parsed:
Y1 : 0.95 -> 0.942
T  : 326.65 -> 335.15

  8%|▊         | 21/276 [00:37<07:38,  1.80s/it]

====================================================================================================
[21/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(=O)C
Component 2 SMILES: CO
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.050
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.108
Equilibrium temperature: 336.15 K

Prediction:
Vapor-phase mole fraction of component 1: 0.110
Equilibrium temperature: 336.85 K

Parsed:
Y1 : 0.108 -> 0.11
T  : 336.15 -> 336.85

  8%|▊         | 22/276 [00:39<07:36,  1.80s/it]

====================================================================================================
[22/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: C1COCCO1
Operating pressure: 6.670 kPa
Liquid-phase mole fraction of component 1: 0.921
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.649
Equilibrium temperature: 304.45 K

Prediction:
Vapor-phase mole fraction of component 1: 0.604
Equilibrium temperature: 304.75 K

Parsed:
Y1 : 0.649 -> 0.604
T  : 304.45 -> 304.75

  8%|▊         | 23/276 [00:41<07:34,  1.80s/it]

====================================================================================================
[23/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: C1COCOC1
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.142
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.378
Equilibrium temperature: 364.88 K

Prediction:
Vapor-phase mole fraction of component 1: 0.396
Equilibrium temperature: 363.15 K

Parsed:
Y1 : 0.378 -> 0.396
T  : 364.88 -> 363.15

  9%|▊         | 24/276 [00:43<07:32,  1.79s/it]

====================================================================================================
[24/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: C1COCOC1
Operating pressure: 26.660 kPa
Liquid-phase mole fraction of component 1: 0.942
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.928
Equilibrium temperature: 320.09 K

Prediction:
Vapor-phase mole fraction of component 1: 0.930
Equilibrium temperature: 319.79 K

Parsed:
Y1 : 0.928 -> 0.93
T  : 320.09 -> 319.79

  9%|▉         | 25/276 [00:45<07:29,  1.79s/it]

====================================================================================================
[25/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: C1=CC=CC=C1
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.245
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.390
Equilibrium temperature: 341.55 K

Prediction:
Vapor-phase mole fraction of component 1: 0.365
Equilibrium temperature: 341.15 K

Parsed:
Y1 : 0.39 -> 0.365
T  : 341.55 -> 341.15

  9%|▉         | 26/276 [00:46<07:28,  1.79s/it]

====================================================================================================
[26/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: C1COCOC1
Operating pressure: 53.330 kPa
Liquid-phase mole fraction of component 1: 0.480
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.669
Equilibrium temperature: 337.85 K

Prediction:
Vapor-phase mole fraction of component 1: 0.675
Equilibrium temperature: 337.80 K

Parsed:
Y1 : 0.669 -> 0.675
T  : 337.85 -> 337.8

 10%|▉         | 27/276 [00:48<07:25,  1.79s/it]

====================================================================================================
[27/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: C1=CC=CC=C1
Operating pressure: 40.000 kPa
Liquid-phase mole fraction of component 1: 0.000
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.000
Equilibrium temperature: 326.05 K

Prediction:
Vapor-phase mole fraction of component 1: 0.000
Equilibrium temperature: 324.75 K

Parsed:
Y1 : 0.0 -> 0.0
T  : 326.05 -> 324.75

 10%|█         | 28/276 [00:50<07:23,  1.79s/it]

====================================================================================================
[28/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: C1COCOC1
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.734
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.812
Equilibrium temperature: 352.22 K

Prediction:
Vapor-phase mole fraction of component 1: 0.802
Equilibrium temperature: 352.15 K

Parsed:
Y1 : 0.812 -> 0.802
T  : 352.22 -> 352.15

 11%|█         | 29/276 [00:52<07:21,  1.79s/it]

====================================================================================================
[29/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(C=O)O
Component 2 SMILES: CO
Operating pressure: 26.660 kPa
Liquid-phase mole fraction of component 1: 0.086
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.282
Equilibrium temperature: 301.95 K

Prediction:
Vapor-phase mole fraction of component 1: 0.270
Equilibrium temperature: 304.95 K

Parsed:
Y1 : 0.282 -> 0.27
T  : 301.95 -> 304.95

 11%|█         | 30/276 [00:53<07:19,  1.79s/it]

====================================================================================================
[30/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(=O)C
Component 2 SMILES: O
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.250
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.819
Equilibrium temperature: 335.39 K

Prediction:
Vapor-phase mole fraction of component 1: 0.806
Equilibrium temperature: 334.75 K

Parsed:
Y1 : 0.819 -> 0.806
T  : 335.39 -> 334.75

 11%|█         | 31/276 [00:55<07:18,  1.79s/it]

====================================================================================================
[31/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: C(C(CO)O)O
Operating pressure: 1.330 kPa
Liquid-phase mole fraction of component 1: 0.406
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 1.000
Equilibrium temperature: 314.35 K

Prediction:
Vapor-phase mole fraction of component 1: 0.999
Equilibrium temperature: 315.55 K

Parsed:
Y1 : 1.0 -> 0.999
T  : 314.35 -> 315.55

 12%|█▏        | 32/276 [00:57<07:16,  1.79s/it]

====================================================================================================
[32/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: COCCl
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.441
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.728
Equilibrium temperature: 375.05 K

Prediction:
Vapor-phase mole fraction of component 1: 0.724
Equilibrium temperature: 374.15 K

Parsed:
Y1 : 0.728 -> 0.724
T  : 375.05 -> 374.15

 12%|█▏        | 33/276 [00:59<07:14,  1.79s/it]

====================================================================================================
[33/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: C(CN)N
Operating pressure: 13.330 kPa
Liquid-phase mole fraction of component 1: 0.922
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.997
Equilibrium temperature: 327.15 K

Prediction:
Vapor-phase mole fraction of component 1: 0.999
Equilibrium temperature: 326.55 K

Parsed:
Y1 : 0.997 -> 0.999
T  : 327.15 -> 326.55

 12%|█▏        | 34/276 [01:01<07:13,  1.79s/it]

====================================================================================================
[34/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: CCCC(=O)O
Operating pressure: 53.330 kPa
Liquid-phase mole fraction of component 1: 0.471
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.921
Equilibrium temperature: 359.55 K

Prediction:
Vapor-phase mole fraction of component 1: 0.911
Equilibrium temperature: 359.15 K

Parsed:
Y1 : 0.921 -> 0.911
T  : 359.55 -> 359.15

 13%|█▎        | 35/276 [01:02<07:11,  1.79s/it]

====================================================================================================
[35/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: C1COCOC1
Operating pressure: 26.660 kPa
Liquid-phase mole fraction of component 1: 0.790
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.802
Equilibrium temperature: 319.61 K

Prediction:
Vapor-phase mole fraction of component 1: 0.806
Equilibrium temperature: 319.79 K

Parsed:
Y1 : 0.802 -> 0.806
T  : 319.61 -> 319.79

 13%|█▎        | 36/276 [01:04<07:09,  1.79s/it]

====================================================================================================
[36/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(C)O
Component 2 SMILES: O
Operating pressure: 25.330 kPa
Liquid-phase mole fraction of component 1: 0.708
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.691
Equilibrium temperature: 322.38 K

Prediction:
Vapor-phase mole fraction of component 1: 0.679
Equilibrium temperature: 322.39 K

Parsed:
Y1 : 0.691 -> 0.679
T  : 322.38 -> 322.39

 13%|█▎        | 37/276 [01:06<07:07,  1.79s/it]

====================================================================================================
[37/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(C=O)O
Component 2 SMILES: CO
Operating pressure: 585.660 kPa
Liquid-phase mole fraction of component 1: 0.558
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.536
Equilibrium temperature: 382.94 K

Prediction:
Vapor-phase mole fraction of component 1: 0.590
Equilibrium temperature: 383.20 K

Parsed:
Y1 : 0.536 -> 0.59
T  : 382.94 -> 383.2

 14%|█▍        | 38/276 [01:08<07:05,  1.79s/it]

====================================================================================================
[38/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: CCCCO
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.936
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.738
Equilibrium temperature: 365.90 K

Prediction:
Vapor-phase mole fraction of component 1: 0.750
Equilibrium temperature: 365.95 K

Parsed:
Y1 : 0.738 -> 0.75
T  : 365.9 -> 365.95

 14%|█▍        | 39/276 [01:10<07:03,  1.79s/it]

====================================================================================================
[39/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: O
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.345
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.591
Equilibrium temperature: 354.35 K

Prediction:
Vapor-phase mole fraction of component 1: 0.596
Equilibrium temperature: 354.75 K

Parsed:
Y1 : 0.591 -> 0.596
T  : 354.35 -> 354.75

 14%|█▍        | 40/276 [01:11<07:01,  1.79s/it]

====================================================================================================
[40/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: C(C(CO)O)O
Operating pressure: 87.990 kPa
Liquid-phase mole fraction of component 1: 0.915
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 1.000
Equilibrium temperature: 383.15 K

Prediction:
Vapor-phase mole fraction of component 1: 1.000
Equilibrium temperature: 373.15 K

Parsed:
Y1 : 1.0 -> 1.0
T  : 383.15 -> 373.15

 15%|█▍        | 41/276 [01:13<06:59,  1.79s/it]

====================================================================================================
[41/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: C1=CC=CC=C1
Operating pressure: 69.490 kPa
Liquid-phase mole fraction of component 1: 0.032
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.289
Equilibrium temperature: 332.01 K

Prediction:
Vapor-phase mole fraction of component 1: 0.300
Equilibrium temperature: 330.00 K

Parsed:
Y1 : 0.289 -> 0.3
T  : 332.01 -> 330.0

 15%|█▌        | 42/276 [01:15<06:58,  1.79s/it]

====================================================================================================
[42/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: C1COCOC1
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.409
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.644
Equilibrium temperature: 356.34 K

Prediction:
Vapor-phase mole fraction of component 1: 0.648
Equilibrium temperature: 356.45 K

Parsed:
Y1 : 0.644 -> 0.648
T  : 356.34 -> 356.45

 16%|█▌        | 43/276 [01:17<06:56,  1.79s/it]

====================================================================================================
[43/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: CCCC(=O)O
Operating pressure: 26.660 kPa
Liquid-phase mole fraction of component 1: 0.210
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.880
Equilibrium temperature: 350.65 K

Prediction:
Vapor-phase mole fraction of component 1: 0.860
Equilibrium temperature: 353.05 K

Parsed:
Y1 : 0.88 -> 0.86
T  : 350.65 -> 353.05

 16%|█▌        | 44/276 [01:18<06:55,  1.79s/it]

====================================================================================================
[44/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: O
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.000
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.000
Equilibrium temperature: 373.15 K

Prediction:
Vapor-phase mole fraction of component 1: 0.000
Equilibrium temperature: 373.15 K

Parsed:
Y1 : 0.0 -> 0.0
T  : 373.15 -> 373.15

 16%|█▋        | 45/276 [01:20<06:53,  1.79s/it]

====================================================================================================
[45/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: O
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.843
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.930
Equilibrium temperature: 340.32 K

Prediction:
Vapor-phase mole fraction of component 1: 0.926
Equilibrium temperature: 340.05 K

Parsed:
Y1 : 0.93 -> 0.926
T  : 340.32 -> 340.05

 17%|█▋        | 46/276 [01:22<06:51,  1.79s/it]

====================================================================================================
[46/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(C)O
Component 2 SMILES: O
Operating pressure: 25.330 kPa
Liquid-phase mole fraction of component 1: 0.664
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.667
Equilibrium temperature: 322.48 K

Prediction:
Vapor-phase mole fraction of component 1: 0.669
Equilibrium temperature: 322.39 K

Parsed:
Y1 : 0.667 -> 0.669
T  : 322.48 -> 322.39

 17%|█▋        | 47/276 [01:24<06:49,  1.79s/it]

====================================================================================================
[47/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: C1=CC=CC=C1
Operating pressure: 69.490 kPa
Liquid-phase mole fraction of component 1: 0.009
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.108
Equilibrium temperature: 338.57 K

Prediction:
Vapor-phase mole fraction of component 1: 0.140
Equilibrium temperature: 339.70 K

Parsed:
Y1 : 0.108 -> 0.14
T  : 338.57 -> 339.7

 17%|█▋        | 48/276 [01:26<06:48,  1.79s/it]

====================================================================================================
[48/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: CCC(=O)O
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.525
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.801
Equilibrium temperature: 376.75 K

Prediction:
Vapor-phase mole fraction of component 1: 0.815
Equilibrium temperature: 376.05 K

Parsed:
Y1 : 0.801 -> 0.815
T  : 376.75 -> 376.05

 18%|█▊        | 49/276 [01:27<06:46,  1.79s/it]

====================================================================================================
[49/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(C)O
Component 2 SMILES: O
Operating pressure: 25.330 kPa
Liquid-phase mole fraction of component 1: 1.000
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 1.000
Equilibrium temperature: 324.51 K

Prediction:
Vapor-phase mole fraction of component 1: 1.000
Equilibrium temperature: 324.79 K

Parsed:
Y1 : 1.0 -> 1.0
T  : 324.51 -> 324.79

 18%|█▊        | 50/276 [01:29<06:44,  1.79s/it]

====================================================================================================
[50/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: CNNC
Operating pressure: 100.390 kPa
Liquid-phase mole fraction of component 1: 0.866
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.996
Equilibrium temperature: 343.65 K

Prediction:
Vapor-phase mole fraction of component 1: 0.995
Equilibrium temperature: 345.65 K

Parsed:
Y1 : 0.996 -> 0.995
T  : 343.65 -> 345.65

 18%|█▊        | 51/276 [01:31<06:42,  1.79s/it]

====================================================================================================
[51/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(=O)C
Component 2 SMILES: O
Operating pressure: 66.660 kPa
Liquid-phase mole fraction of component 1: 0.882
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.933
Equilibrium temperature: 318.85 K

Prediction:
Vapor-phase mole fraction of component 1: 0.922
Equilibrium temperature: 319.65 K

Parsed:
Y1 : 0.933 -> 0.922
T  : 318.85 -> 319.65

 19%|█▉        | 52/276 [01:33<06:40,  1.79s/it]

====================================================================================================
[52/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(C)O
Component 2 SMILES: O
Operating pressure: 50.660 kPa
Liquid-phase mole fraction of component 1: 0.060
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.457
Equilibrium temperature: 340.91 K

Prediction:
Vapor-phase mole fraction of component 1: 0.439
Equilibrium temperature: 339.70 K

Parsed:
Y1 : 0.457 -> 0.439
T  : 340.91 -> 339.7

 19%|█▉        | 53/276 [01:35<06:38,  1.79s/it]

====================================================================================================
[53/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: C1COCOC1
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.027
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.108
Equilibrium temperature: 371.62 K

Prediction:
Vapor-phase mole fraction of component 1: 0.110
Equilibrium temperature: 370.05 K

Parsed:
Y1 : 0.108 -> 0.11
T  : 371.62 -> 370.05

 20%|█▉        | 54/276 [01:36<06:37,  1.79s/it]

====================================================================================================
[54/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: CC(C)OC(C)C
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.746
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.684
Equilibrium temperature: 346.74 K

Prediction:
Vapor-phase mole fraction of component 1: 0.685
Equilibrium temperature: 346.59 K

Parsed:
Y1 : 0.684 -> 0.685
T  : 346.74 -> 346.59

 20%|█▉        | 55/276 [01:38<06:35,  1.79s/it]

====================================================================================================
[55/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CC(=O)O
Operating pressure: 94.130 kPa
Liquid-phase mole fraction of component 1: 0.126
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.159
Equilibrium temperature: 387.25 K

Prediction:
Vapor-phase mole fraction of component 1: 0.140
Equilibrium temperature: 386.65 K

Parsed:
Y1 : 0.159 -> 0.14
T  : 387.25 -> 386.65

 20%|██        | 56/276 [01:40<06:33,  1.79s/it]

====================================================================================================
[56/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(C)O
Component 2 SMILES: O
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.190
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.537
Equilibrium temperature: 354.73 K

Prediction:
Vapor-phase mole fraction of component 1: 0.536
Equilibrium temperature: 355.05 K

Parsed:
Y1 : 0.537 -> 0.536
T  : 354.73 -> 355.05

 21%|██        | 57/276 [01:42<06:32,  1.79s/it]

====================================================================================================
[57/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: C(CO)O
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.075
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.845
Equilibrium temperature: 420.35 K

Prediction:
Vapor-phase mole fraction of component 1: 0.850
Equilibrium temperature: 423.15 K

Parsed:
Y1 : 0.845 -> 0.85
T  : 420.35 -> 423.15

 21%|██        | 58/276 [01:44<06:30,  1.79s/it]

====================================================================================================
[58/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: C1CCOC1
Component 2 SMILES: O
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.840
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.826
Equilibrium temperature: 336.72 K

Prediction:
Vapor-phase mole fraction of component 1: 0.820
Equilibrium temperature: 336.87 K

Parsed:
Y1 : 0.826 -> 0.82
T  : 336.72 -> 336.87

 21%|██▏       | 59/276 [01:45<06:28,  1.79s/it]

====================================================================================================
[59/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: CCCC(=O)C
Operating pressure: 13.330 kPa
Liquid-phase mole fraction of component 1: 0.750
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.776
Equilibrium temperature: 307.05 K

Prediction:
Vapor-phase mole fraction of component 1: 0.760
Equilibrium temperature: 306.95 K

Parsed:
Y1 : 0.776 -> 0.76
T  : 307.05 -> 306.95

 22%|██▏       | 60/276 [01:47<06:26,  1.79s/it]

====================================================================================================
[60/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: C1COCOC1
Operating pressure: 53.330 kPa
Liquid-phase mole fraction of component 1: 0.801
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.829
Equilibrium temperature: 335.77 K

Prediction:
Vapor-phase mole fraction of component 1: 0.826
Equilibrium temperature: 335.68 K

Parsed:
Y1 : 0.829 -> 0.826
T  : 335.77 -> 335.68

 22%|██▏       | 61/276 [01:49<06:24,  1.79s/it]

====================================================================================================
[61/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: C1CCOC1
Component 2 SMILES: O
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.960
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.932
Equilibrium temperature: 337.76 K

Prediction:
Vapor-phase mole fraction of component 1: 0.940
Equilibrium temperature: 337.69 K

Parsed:
Y1 : 0.932 -> 0.94
T  : 337.76 -> 337.69

 22%|██▏       | 62/276 [01:51<06:22,  1.79s/it]

====================================================================================================
[62/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: C(C(CO)O)O
Operating pressure: 13.330 kPa
Liquid-phase mole fraction of component 1: 0.100
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.952
Equilibrium temperature: 394.55 K

Prediction:
Vapor-phase mole fraction of component 1: 0.929
Equilibrium temperature: 429.35 K

Parsed:
Y1 : 0.952 -> 0.929
T  : 394.55 -> 429.35

 23%|██▎       | 63/276 [01:52<06:20,  1.79s/it]

====================================================================================================
[63/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(C=O)O
Component 2 SMILES: CO
Operating pressure: 585.660 kPa
Liquid-phase mole fraction of component 1: 0.516
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.516
Equilibrium temperature: 382.89 K

Prediction:
Vapor-phase mole fraction of component 1: 0.536
Equilibrium temperature: 383.20 K

Parsed:
Y1 : 0.516 -> 0.536
T  : 382.89 -> 383.2

 23%|██▎       | 64/276 [01:54<06:18,  1.79s/it]

====================================================================================================
[64/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: O
Operating pressure: 50.660 kPa
Liquid-phase mole fraction of component 1: 0.015
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.163
Equilibrium temperature: 351.15 K

Prediction:
Vapor-phase mole fraction of component 1: 0.130
Equilibrium temperature: 353.05 K

Parsed:
Y1 : 0.163 -> 0.13
T  : 351.15 -> 353.05

 24%|██▎       | 65/276 [01:56<06:17,  1.79s/it]

====================================================================================================
[65/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CC(=O)O
Operating pressure: 94.130 kPa
Liquid-phase mole fraction of component 1: 1.000
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 1.000
Equilibrium temperature: 368.45 K

Prediction:
Vapor-phase mole fraction of component 1: 1.000
Equilibrium temperature: 368.45 K

Parsed:
Y1 : 1.0 -> 1.0
T  : 368.45 -> 368.45

 24%|██▍       | 66/276 [01:58<06:15,  1.79s/it]

====================================================================================================
[66/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: O
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.020
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.121
Equilibrium temperature: 370.07 K

Prediction:
Vapor-phase mole fraction of component 1: 0.160
Equilibrium temperature: 369.95 K

Parsed:
Y1 : 0.121 -> 0.16
T  : 370.07 -> 369.95

 24%|██▍       | 67/276 [02:00<06:13,  1.79s/it]

====================================================================================================
[67/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC=O
Component 2 SMILES: O
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.890
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.991
Equilibrium temperature: 285.05 K

Prediction:
Vapor-phase mole fraction of component 1: 0.990
Equilibrium temperature: 284.95 K

Parsed:
Y1 : 0.991 -> 0.99
T  : 285.05 -> 284.95

 25%|██▍       | 68/276 [02:01<06:11,  1.79s/it]

====================================================================================================
[68/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: C1=CC=CC=C1
Operating pressure: 69.490 kPa
Liquid-phase mole fraction of component 1: 0.519
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.588
Equilibrium temperature: 321.39 K

Prediction:
Vapor-phase mole fraction of component 1: 0.596
Equilibrium temperature: 321.47 K

Parsed:
Y1 : 0.588 -> 0.596
T  : 321.39 -> 321.47

 25%|██▌       | 69/276 [02:03<06:10,  1.79s/it]

====================================================================================================
[69/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(=O)O
Component 2 SMILES: O
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.734
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.626
Equilibrium temperature: 381.95 K

Prediction:
Vapor-phase mole fraction of component 1: 0.602
Equilibrium temperature: 381.75 K

Parsed:
Y1 : 0.626 -> 0.602
T  : 381.95 -> 381.75

 25%|██▌       | 70/276 [02:05<06:08,  1.79s/it]

====================================================================================================
[70/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: CNC=O
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.665
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.983
Equilibrium temperature: 383.35 K

Prediction:
Vapor-phase mole fraction of component 1: 0.980
Equilibrium temperature: 382.05 K

Parsed:
Y1 : 0.983 -> 0.98
T  : 383.35 -> 382.05

 26%|██▌       | 71/276 [02:07<06:06,  1.79s/it]

====================================================================================================
[71/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: C1COCOC1
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.675
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.786
Equilibrium temperature: 352.72 K

Prediction:
Vapor-phase mole fraction of component 1: 0.775
Equilibrium temperature: 352.15 K

Parsed:
Y1 : 0.786 -> 0.775
T  : 352.72 -> 352.15

 26%|██▌       | 72/276 [02:09<06:04,  1.79s/it]

====================================================================================================
[72/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: C(=C(Cl)Cl)(Cl)Cl
Component 2 SMILES: CCO
Operating pressure: 99.320 kPa
Liquid-phase mole fraction of component 1: 0.557
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.597
Equilibrium temperature: 337.03 K

Prediction:
Vapor-phase mole fraction of component 1: 0.650
Equilibrium temperature: 337.45 K

Parsed:
Y1 : 0.597 -> 0.65
T  : 337.03 -> 337.45

 26%|██▋       | 73/276 [02:10<06:02,  1.79s/it]

====================================================================================================
[73/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: O
Operating pressure: 66.660 kPa
Liquid-phase mole fraction of component 1: 0.772
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.913
Equilibrium temperature: 330.85 K

Prediction:
Vapor-phase mole fraction of component 1: 0.906
Equilibrium temperature: 332.45 K

Parsed:
Y1 : 0.913 -> 0.906
T  : 330.85 -> 332.45

 27%|██▋       | 74/276 [02:12<06:00,  1.79s/it]

====================================================================================================
[74/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(C)O
Component 2 SMILES: O
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.100
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.501
Equilibrium temperature: 355.85 K

Prediction:
Vapor-phase mole fraction of component 1: 0.522
Equilibrium temperature: 355.05 K

Parsed:
Y1 : 0.501 -> 0.522
T  : 355.85 -> 355.05

 27%|██▋       | 75/276 [02:14<05:59,  1.79s/it]

====================================================================================================
[75/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: O
Operating pressure: 26.660 kPa
Liquid-phase mole fraction of component 1: 0.795
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.937
Equilibrium temperature: 310.25 K

Prediction:
Vapor-phase mole fraction of component 1: 0.924
Equilibrium temperature: 309.45 K

Parsed:
Y1 : 0.937 -> 0.924
T  : 310.25 -> 309.45

 28%|██▊       | 76/276 [02:16<05:57,  1.79s/it]

====================================================================================================
[76/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCOC(=O)C
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.558
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.573
Equilibrium temperature: 367.95 K

Prediction:
Vapor-phase mole fraction of component 1: 0.590
Equilibrium temperature: 368.65 K

Parsed:
Y1 : 0.573 -> 0.59
T  : 367.95 -> 368.65

 28%|██▊       | 77/276 [02:18<05:55,  1.79s/it]

====================================================================================================
[77/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: C1COCOC1
Operating pressure: 26.660 kPa
Liquid-phase mole fraction of component 1: 0.657
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.732
Equilibrium temperature: 319.99 K

Prediction:
Vapor-phase mole fraction of component 1: 0.732
Equilibrium temperature: 319.79 K

Parsed:
Y1 : 0.732 -> 0.732
T  : 319.99 -> 319.79

 28%|██▊       | 78/276 [02:19<05:53,  1.79s/it]

====================================================================================================
[78/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: CNNC
Operating pressure: 100.390 kPa
Liquid-phase mole fraction of component 1: 0.585
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.901
Equilibrium temperature: 361.55 K

Prediction:
Vapor-phase mole fraction of component 1: 0.890
Equilibrium temperature: 363.15 K

Parsed:
Y1 : 0.901 -> 0.89
T  : 361.55 -> 363.15

 29%|██▊       | 79/276 [02:21<05:51,  1.79s/it]

====================================================================================================
[79/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(C)O
Component 2 SMILES: O
Operating pressure: 12.670 kPa
Liquid-phase mole fraction of component 1: 0.185
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.528
Equilibrium temperature: 310.74 K

Prediction:
Vapor-phase mole fraction of component 1: 0.536
Equilibrium temperature: 311.02 K

Parsed:
Y1 : 0.528 -> 0.536
T  : 310.74 -> 311.02

 29%|██▉       | 80/276 [02:23<05:50,  1.79s/it]

====================================================================================================
[80/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: CCC(CC)C(=O)O
Operating pressure: 13.330 kPa
Liquid-phase mole fraction of component 1: 0.920
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.970
Equilibrium temperature: 325.25 K

Prediction:
Vapor-phase mole fraction of component 1: 0.972
Equilibrium temperature: 324.95 K

Parsed:
Y1 : 0.97 -> 0.972
T  : 325.25 -> 324.95

 29%|██▉       | 81/276 [02:25<05:48,  1.79s/it]

====================================================================================================
[81/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: O
Operating pressure: 98.070 kPa
Liquid-phase mole fraction of component 1: 0.391
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.608
Equilibrium temperature: 354.15 K

Prediction:
Vapor-phase mole fraction of component 1: 0.600
Equilibrium temperature: 354.45 K

Parsed:
Y1 : 0.608 -> 0.6
T  : 354.15 -> 354.45

 30%|██▉       | 82/276 [02:26<05:46,  1.79s/it]

====================================================================================================
[82/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: CNNC
Operating pressure: 100.390 kPa
Liquid-phase mole fraction of component 1: 0.414
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.710
Equilibrium temperature: 372.25 K

Prediction:
Vapor-phase mole fraction of component 1: 0.647
Equilibrium temperature: 374.65 K

Parsed:
Y1 : 0.71 -> 0.647
T  : 372.25 -> 374.65

 30%|███       | 83/276 [02:28<05:44,  1.79s/it]

====================================================================================================
[83/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: C(C(CO)O)O
Operating pressure: 87.990 kPa
Liquid-phase mole fraction of component 1: 0.545
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.990
Equilibrium temperature: 433.15 K

Prediction:
Vapor-phase mole fraction of component 1: 0.995
Equilibrium temperature: 423.15 K

Parsed:
Y1 : 0.99 -> 0.995
T  : 433.15 -> 423.15

 30%|███       | 84/276 [02:30<05:42,  1.79s/it]

====================================================================================================
[84/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(=O)C
Component 2 SMILES: CCO
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.852
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.896
Equilibrium temperature: 330.45 K

Prediction:
Vapor-phase mole fraction of component 1: 0.882
Equilibrium temperature: 329.65 K

Parsed:
Y1 : 0.896 -> 0.882
T  : 330.45 -> 329.65

 31%|███       | 85/276 [02:32<05:41,  1.79s/it]

====================================================================================================
[85/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: O
Operating pressure: 46.660 kPa
Liquid-phase mole fraction of component 1: 0.122
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.493
Equilibrium temperature: 340.15 K

Prediction:
Vapor-phase mole fraction of component 1: 0.475
Equilibrium temperature: 342.35 K

Parsed:
Y1 : 0.493 -> 0.475
T  : 340.15 -> 342.35

 31%|███       | 86/276 [02:34<05:39,  1.79s/it]

====================================================================================================
[86/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: CN(C)C=O
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.434
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.820
Equilibrium temperature: 386.75 K

Prediction:
Vapor-phase mole fraction of component 1: 0.812
Equilibrium temperature: 384.45 K

Parsed:
Y1 : 0.82 -> 0.812
T  : 386.75 -> 384.45

 32%|███▏      | 87/276 [02:35<05:37,  1.79s/it]

====================================================================================================
[87/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(C)O
Component 2 SMILES: O
Operating pressure: 50.660 kPa
Liquid-phase mole fraction of component 1: 0.335
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.562
Equilibrium temperature: 337.76 K

Prediction:
Vapor-phase mole fraction of component 1: 0.554
Equilibrium temperature: 337.70 K

Parsed:
Y1 : 0.562 -> 0.554
T  : 337.76 -> 337.7

 32%|███▏      | 88/276 [02:37<05:36,  1.79s/it]

====================================================================================================
[88/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: C(C(CO)O)O
Operating pressure: 66.660 kPa
Liquid-phase mole fraction of component 1: 0.150
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.976
Equilibrium temperature: 441.45 K

Prediction:
Vapor-phase mole fraction of component 1: 0.936
Equilibrium temperature: 469.65 K

Parsed:
Y1 : 0.976 -> 0.936
T  : 441.45 -> 469.65

 32%|███▏      | 89/276 [02:39<05:34,  1.79s/it]

====================================================================================================
[89/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: O
Operating pressure: 94.130 kPa
Liquid-phase mole fraction of component 1: 0.008
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.088
Equilibrium temperature: 369.05 K

Prediction:
Vapor-phase mole fraction of component 1: 0.080
Equilibrium temperature: 370.05 K

Parsed:
Y1 : 0.088 -> 0.08
T  : 369.05 -> 370.05

 33%|███▎      | 90/276 [02:41<05:32,  1.79s/it]

====================================================================================================
[90/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCOC(=O)C
Component 2 SMILES: CCO
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.900
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.836
Equilibrium temperature: 348.15 K

Prediction:
Vapor-phase mole fraction of component 1: 0.830
Equilibrium temperature: 347.55 K

Parsed:
Y1 : 0.836 -> 0.83
T  : 348.15 -> 347.55

 33%|███▎      | 91/276 [02:43<05:30,  1.79s/it]

====================================================================================================
[91/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: CCCC(=O)O
Operating pressure: 13.330 kPa
Liquid-phase mole fraction of component 1: 0.041
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.642
Equilibrium temperature: 360.55 K

Prediction:
Vapor-phase mole fraction of component 1: 0.596
Equilibrium temperature: 359.45 K

Parsed:
Y1 : 0.642 -> 0.596
T  : 360.55 -> 359.45

 33%|███▎      | 92/276 [02:44<05:28,  1.79s/it]

====================================================================================================
[92/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(C=O)O
Component 2 SMILES: CO
Operating pressure: 26.660 kPa
Liquid-phase mole fraction of component 1: 0.128
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.343
Equilibrium temperature: 300.85 K

Prediction:
Vapor-phase mole fraction of component 1: 0.346
Equilibrium temperature: 301.95 K

Parsed:
Y1 : 0.343 -> 0.346
T  : 300.85 -> 301.95

 34%|███▎      | 93/276 [02:46<05:27,  1.79s/it]

====================================================================================================
[93/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(C)O
Component 2 SMILES: O
Operating pressure: 50.660 kPa
Liquid-phase mole fraction of component 1: 0.041
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.391
Equilibrium temperature: 343.27 K

Prediction:
Vapor-phase mole fraction of component 1: 0.403
Equilibrium temperature: 342.00 K

Parsed:
Y1 : 0.391 -> 0.403
T  : 343.27 -> 342.0

 34%|███▍      | 94/276 [02:48<05:25,  1.79s/it]

====================================================================================================
[94/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: COCCl
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.892
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.865
Equilibrium temperature: 371.15 K

Prediction:
Vapor-phase mole fraction of component 1: 0.878
Equilibrium temperature: 371.35 K

Parsed:
Y1 : 0.865 -> 0.878
T  : 371.15 -> 371.35

 34%|███▍      | 95/276 [02:50<05:23,  1.79s/it]

====================================================================================================
[95/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: CC(=O)O
Operating pressure: 16.670 kPa
Liquid-phase mole fraction of component 1: 0.737
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.795
Equilibrium temperature: 331.25 K

Prediction:
Vapor-phase mole fraction of component 1: 0.802
Equilibrium temperature: 331.02 K

Parsed:
Y1 : 0.795 -> 0.802
T  : 331.25 -> 331.02

 35%|███▍      | 96/276 [02:51<05:21,  1.79s/it]

====================================================================================================
[96/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: C(CN)N
Operating pressure: 79.990 kPa
Liquid-phase mole fraction of component 1: 0.000
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.000
Equilibrium temperature: 382.45 K

Prediction:
Vapor-phase mole fraction of component 1: 0.000
Equilibrium temperature: 373.15 K

Parsed:
Y1 : 0.0 -> 0.0
T  : 382.45 -> 373.15

 35%|███▌      | 97/276 [02:53<05:19,  1.79s/it]

====================================================================================================
[97/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: C1COCOC1
Operating pressure: 79.990 kPa
Liquid-phase mole fraction of component 1: 0.972
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.971
Equilibrium temperature: 345.55 K

Prediction:
Vapor-phase mole fraction of component 1: 0.966
Equilibrium temperature: 346.12 K

Parsed:
Y1 : 0.971 -> 0.966
T  : 345.55 -> 346.12

 36%|███▌      | 98/276 [02:55<05:18,  1.79s/it]

====================================================================================================
[98/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: O
Operating pressure: 98.070 kPa
Liquid-phase mole fraction of component 1: 0.006
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.065
Equilibrium temperature: 371.65 K

Prediction:
Vapor-phase mole fraction of component 1: 0.060
Equilibrium temperature: 371.35 K

Parsed:
Y1 : 0.065 -> 0.06
T  : 371.65 -> 371.35

 36%|███▌      | 99/276 [02:57<05:16,  1.79s/it]

====================================================================================================
[99/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: CNC=O
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.409
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.945
Equilibrium temperature: 396.75 K

Prediction:
Vapor-phase mole fraction of component 1: 0.940
Equilibrium temperature: 394.65 K

Parsed:
Y1 : 0.945 -> 0.94
T  : 396.75 -> 394.65

 36%|███▌      | 100/276 [02:59<05:14,  1.79s/it]

====================================================================================================
[100/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: C1COCOC1
Operating pressure: 53.330 kPa
Liquid-phase mole fraction of component 1: 0.180
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.448
Equilibrium temperature: 343.99 K

Prediction:
Vapor-phase mole fraction of component 1: 0.450
Equilibrium temperature: 345.00 K

Parsed:
Y1 : 0.448 -> 0.45
T  : 343.99 -> 345.0

 37%|███▋      | 101/276 [03:00<05:12,  1.79s/it]

====================================================================================================
[101/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: C(Cl)(Cl)Cl
Component 2 SMILES: CO
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.753
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.604
Equilibrium temperature: 326.85 K

Prediction:
Vapor-phase mole fraction of component 1: 0.630
Equilibrium temperature: 327.05 K

Parsed:
Y1 : 0.604 -> 0.63
T  : 326.85 -> 327.05

 37%|███▋      | 102/276 [03:02<05:10,  1.79s/it]

====================================================================================================
[102/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: CCCCO
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.616
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.883
Equilibrium temperature: 360.65 K

Prediction:
Vapor-phase mole fraction of component 1: 0.862
Equilibrium temperature: 363.15 K

Parsed:
Y1 : 0.883 -> 0.862
T  : 360.65 -> 363.15

 37%|███▋      | 103/276 [03:04<05:08,  1.79s/it]

====================================================================================================
[103/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: O
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.790
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.910
Equilibrium temperature: 341.22 K

Prediction:
Vapor-phase mole fraction of component 1: 0.902
Equilibrium temperature: 340.05 K

Parsed:
Y1 : 0.91 -> 0.902
T  : 341.22 -> 340.05

 38%|███▊      | 104/276 [03:06<05:07,  1.79s/it]

====================================================================================================
[104/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCC(=O)C
Component 2 SMILES: O
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.000
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.000
Equilibrium temperature: 373.15 K

Prediction:
Vapor-phase mole fraction of component 1: 0.000
Equilibrium temperature: 373.15 K

Parsed:
Y1 : 0.0 -> 0.0
T  : 373.15 -> 373.15

 38%|███▊      | 105/276 [03:08<05:05,  1.79s/it]

====================================================================================================
[105/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: CCCCO
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.018
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.097
Equilibrium temperature: 388.75 K

Prediction:
Vapor-phase mole fraction of component 1: 0.070
Equilibrium temperature: 379.35 K

Parsed:
Y1 : 0.097 -> 0.07
T  : 388.75 -> 379.35

 38%|███▊      | 106/276 [03:09<05:03,  1.78s/it]

====================================================================================================
[106/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: CC(=O)O
Operating pressure: 26.660 kPa
Liquid-phase mole fraction of component 1: 0.858
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.899
Equilibrium temperature: 340.05 K

Prediction:
Vapor-phase mole fraction of component 1: 0.899
Equilibrium temperature: 340.25 K

Parsed:
Y1 : 0.899 -> 0.899
T  : 340.05 -> 340.25

 39%|███▉      | 107/276 [03:11<05:01,  1.78s/it]

====================================================================================================
[107/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: CCC(=O)O
Operating pressure: 26.660 kPa
Liquid-phase mole fraction of component 1: 0.844
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.916
Equilibrium temperature: 339.95 K

Prediction:
Vapor-phase mole fraction of component 1: 0.916
Equilibrium temperature: 339.95 K

Parsed:
Y1 : 0.916 -> 0.916
T  : 339.95 -> 339.95

 39%|███▉      | 108/276 [03:13<04:59,  1.79s/it]

====================================================================================================
[108/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: C(CN)N
Operating pressure: 13.330 kPa
Liquid-phase mole fraction of component 1: 0.630
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.742
Equilibrium temperature: 342.32 K

Prediction:
Vapor-phase mole fraction of component 1: 0.730
Equilibrium temperature: 341.55 K

Parsed:
Y1 : 0.742 -> 0.73
T  : 342.32 -> 341.55

 39%|███▉      | 109/276 [03:15<04:58,  1.79s/it]

====================================================================================================
[109/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: C(C(CO)O)O
Operating pressure: 74.660 kPa
Liquid-phase mole fraction of component 1: 0.320
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.951
Equilibrium temperature: 463.15 K

Prediction:
Vapor-phase mole fraction of component 1: 0.965
Equilibrium temperature: 453.15 K

Parsed:
Y1 : 0.951 -> 0.965
T  : 463.15 -> 453.15

 40%|███▉      | 110/276 [03:16<04:56,  1.79s/it]

====================================================================================================
[110/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(C=O)O
Component 2 SMILES: CO
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.595
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.629
Equilibrium temperature: 327.03 K

Prediction:
Vapor-phase mole fraction of component 1: 0.625
Equilibrium temperature: 327.05 K

Parsed:
Y1 : 0.629 -> 0.625
T  : 327.03 -> 327.05

 40%|████      | 111/276 [03:18<04:54,  1.79s/it]

====================================================================================================
[111/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(C)O
Component 2 SMILES: O
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.283
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.553
Equilibrium temperature: 354.38 K

Prediction:
Vapor-phase mole fraction of component 1: 0.544
Equilibrium temperature: 354.79 K

Parsed:
Y1 : 0.553 -> 0.544
T  : 354.38 -> 354.79

 41%|████      | 112/276 [03:20<04:53,  1.79s/it]

====================================================================================================
[112/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: C1=CC=CC=C1
Operating pressure: 30.730 kPa
Liquid-phase mole fraction of component 1: 0.595
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.567
Equilibrium temperature: 302.87 K

Prediction:
Vapor-phase mole fraction of component 1: 0.568
Equilibrium temperature: 302.99 K

Parsed:
Y1 : 0.567 -> 0.568
T  : 302.87 -> 302.99

 41%|████      | 113/276 [03:22<04:51,  1.79s/it]

====================================================================================================
[113/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: O
Operating pressure: 333.420 kPa
Liquid-phase mole fraction of component 1: 0.068
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.338
Equilibrium temperature: 398.55 K

Prediction:
Vapor-phase mole fraction of component 1: 0.348
Equilibrium temperature: 396.45 K

Parsed:
Y1 : 0.338 -> 0.348
T  : 398.55 -> 396.45

 41%|████▏     | 114/276 [03:24<04:49,  1.79s/it]

====================================================================================================
[114/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: C1CCOC1
Component 2 SMILES: O
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.500
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.766
Equilibrium temperature: 337.31 K

Prediction:
Vapor-phase mole fraction of component 1: 0.764
Equilibrium temperature: 337.21 K

Parsed:
Y1 : 0.766 -> 0.764
T  : 337.31 -> 337.21

 42%|████▏     | 115/276 [03:25<04:47,  1.79s/it]

====================================================================================================
[115/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: C1=CC=CC=C1
Operating pressure: 53.330 kPa
Liquid-phase mole fraction of component 1: 0.000
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.000
Equilibrium temperature: 333.45 K

Prediction:
Vapor-phase mole fraction of component 1: 0.000
Equilibrium temperature: 331.85 K

Parsed:
Y1 : 0.0 -> 0.0
T  : 333.45 -> 331.85

 42%|████▏     | 116/276 [03:27<04:45,  1.79s/it]

====================================================================================================
[116/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(C=O)O
Component 2 SMILES: CO
Operating pressure: 585.660 kPa
Liquid-phase mole fraction of component 1: 0.623
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.579
Equilibrium temperature: 383.22 K

Prediction:
Vapor-phase mole fraction of component 1: 0.604
Equilibrium temperature: 383.20 K

Parsed:
Y1 : 0.579 -> 0.604
T  : 383.22 -> 383.2

 42%|████▏     | 117/276 [03:29<04:44,  1.79s/it]

====================================================================================================
[117/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: C1COCCO1
Operating pressure: 13.330 kPa
Liquid-phase mole fraction of component 1: 0.983
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.898
Equilibrium temperature: 323.05 K

Prediction:
Vapor-phase mole fraction of component 1: 0.720
Equilibrium temperature: 322.95 K

Parsed:
Y1 : 0.898 -> 0.72
T  : 323.05 -> 322.95

 43%|████▎     | 118/276 [03:31<04:42,  1.79s/it]

====================================================================================================
[118/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: O
Operating pressure: 66.660 kPa
Liquid-phase mole fraction of component 1: 0.212
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.622
Equilibrium temperature: 343.15 K

Prediction:
Vapor-phase mole fraction of component 1: 0.604
Equilibrium temperature: 344.05 K

Parsed:
Y1 : 0.622 -> 0.604
T  : 343.15 -> 344.05

 43%|████▎     | 119/276 [03:33<04:40,  1.79s/it]

====================================================================================================
[119/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: C(=O)O
Component 2 SMILES: O
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.048
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.022
Equilibrium temperature: 374.35 K

Prediction:
Vapor-phase mole fraction of component 1: 0.024
Equilibrium temperature: 374.15 K

Parsed:
Y1 : 0.022 -> 0.024
T  : 374.35 -> 374.15

 43%|████▎     | 120/276 [03:34<04:38,  1.79s/it]

====================================================================================================
[120/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: CC(=O)O
Operating pressure: 53.330 kPa
Liquid-phase mole fraction of component 1: 0.344
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.494
Equilibrium temperature: 361.55 K

Prediction:
Vapor-phase mole fraction of component 1: 0.470
Equilibrium temperature: 361.35 K

Parsed:
Y1 : 0.494 -> 0.47
T  : 361.55 -> 361.35

 44%|████▍     | 121/276 [03:36<04:36,  1.79s/it]

====================================================================================================
[121/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: CN(C)C=O
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.885
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.960
Equilibrium temperature: 375.35 K

Prediction:
Vapor-phase mole fraction of component 1: 0.966
Equilibrium temperature: 375.55 K

Parsed:
Y1 : 0.96 -> 0.966
T  : 375.35 -> 375.55

 44%|████▍     | 122/276 [03:38<04:35,  1.79s/it]

====================================================================================================
[122/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: CCC(=O)O
Operating pressure: 13.330 kPa
Liquid-phase mole fraction of component 1: 0.613
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.862
Equilibrium temperature: 326.45 K

Prediction:
Vapor-phase mole fraction of component 1: 0.856
Equilibrium temperature: 325.35 K

Parsed:
Y1 : 0.862 -> 0.856
T  : 326.45 -> 325.35

 45%|████▍     | 123/276 [03:40<04:33,  1.79s/it]

====================================================================================================
[123/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: C1COCCO1
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.500
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.520
Equilibrium temperature: 368.36 K

Prediction:
Vapor-phase mole fraction of component 1: 0.530
Equilibrium temperature: 368.45 K

Parsed:
Y1 : 0.52 -> 0.53
T  : 368.36 -> 368.45

 45%|████▍     | 124/276 [03:41<04:31,  1.79s/it]

====================================================================================================
[124/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: C(Cl)(Cl)Cl
Component 2 SMILES: CCO
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.895
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.873
Equilibrium temperature: 332.70 K

Prediction:
Vapor-phase mole fraction of component 1: 0.850
Equilibrium temperature: 333.05 K

Parsed:
Y1 : 0.873 -> 0.85
T  : 332.7 -> 333.05

 45%|████▌     | 125/276 [03:43<04:29,  1.79s/it]

====================================================================================================
[125/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: CNNC
Operating pressure: 100.390 kPa
Liquid-phase mole fraction of component 1: 0.615
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.910
Equilibrium temperature: 359.55 K

Prediction:
Vapor-phase mole fraction of component 1: 0.930
Equilibrium temperature: 358.65 K

Parsed:
Y1 : 0.91 -> 0.93
T  : 359.55 -> 358.65

 46%|████▌     | 126/276 [03:45<04:27,  1.79s/it]

====================================================================================================
[126/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: CCC(=O)O
Operating pressure: 26.660 kPa
Liquid-phase mole fraction of component 1: 0.197
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.625
Equilibrium temperature: 350.95 K

Prediction:
Vapor-phase mole fraction of component 1: 0.606
Equilibrium temperature: 353.05 K

Parsed:
Y1 : 0.625 -> 0.606
T  : 350.95 -> 353.05

 46%|████▌     | 127/276 [03:47<04:26,  1.79s/it]

====================================================================================================
[127/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: C(=O)O
Component 2 SMILES: O
Operating pressure: 53.330 kPa
Liquid-phase mole fraction of component 1: 0.845
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.904
Equilibrium temperature: 357.15 K

Prediction:
Vapor-phase mole fraction of component 1: 0.915
Equilibrium temperature: 357.45 K

Parsed:
Y1 : 0.904 -> 0.915
T  : 357.15 -> 357.45

 46%|████▋     | 128/276 [03:49<04:24,  1.79s/it]

====================================================================================================
[128/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: O
Operating pressure: 66.660 kPa
Liquid-phase mole fraction of component 1: 0.463
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.782
Equilibrium temperature: 336.25 K

Prediction:
Vapor-phase mole fraction of component 1: 0.774
Equilibrium temperature: 336.85 K

Parsed:
Y1 : 0.782 -> 0.774
T  : 336.25 -> 336.85

 47%|████▋     | 129/276 [03:50<04:22,  1.79s/it]

====================================================================================================
[129/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: CCC(C)C=O
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.969
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.977
Equilibrium temperature: 338.00 K

Prediction:
Vapor-phase mole fraction of component 1: 0.975
Equilibrium temperature: 337.75 K

Parsed:
Y1 : 0.977 -> 0.975
T  : 338.0 -> 337.75

 47%|████▋     | 130/276 [03:52<04:20,  1.79s/it]

====================================================================================================
[130/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(C)C(C)C
Component 2 SMILES: CO
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.024
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.297
Equilibrium temperature: 328.45 K

Prediction:
Vapor-phase mole fraction of component 1: 0.270
Equilibrium temperature: 332.65 K

Parsed:
Y1 : 0.297 -> 0.27
T  : 328.45 -> 332.65

 47%|████▋     | 131/276 [03:54<04:18,  1.79s/it]

====================================================================================================
[131/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: O
Operating pressure: 46.660 kPa
Liquid-phase mole fraction of component 1: 0.059
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.320
Equilibrium temperature: 345.15 K

Prediction:
Vapor-phase mole fraction of component 1: 0.337
Equilibrium temperature: 344.05 K

Parsed:
Y1 : 0.32 -> 0.337
T  : 345.15 -> 344.05

 48%|████▊     | 132/276 [03:56<04:17,  1.79s/it]

====================================================================================================
[132/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: CC(=O)O
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.102
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.172
Equilibrium temperature: 386.35 K

Prediction:
Vapor-phase mole fraction of component 1: 0.169
Equilibrium temperature: 386.85 K

Parsed:
Y1 : 0.172 -> 0.169
T  : 386.35 -> 386.85

 48%|████▊     | 133/276 [03:58<04:15,  1.79s/it]

====================================================================================================
[133/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: CCOC(=O)C=C
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.509
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.682
Equilibrium temperature: 352.75 K

Prediction:
Vapor-phase mole fraction of component 1: 0.675
Equilibrium temperature: 352.25 K

Parsed:
Y1 : 0.682 -> 0.675
T  : 352.75 -> 352.25

 49%|████▊     | 134/276 [03:59<04:13,  1.79s/it]

====================================================================================================
[134/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: C(C(CO)O)O
Operating pressure: 33.330 kPa
Liquid-phase mole fraction of component 1: 0.600
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 1.000
Equilibrium temperature: 360.55 K

Prediction:
Vapor-phase mole fraction of component 1: 0.999
Equilibrium temperature: 365.55 K

Parsed:
Y1 : 1.0 -> 0.999
T  : 360.55 -> 365.55

 49%|████▉     | 135/276 [04:01<04:12,  1.79s/it]

====================================================================================================
[135/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(C)O
Component 2 SMILES: O
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.167
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.521
Equilibrium temperature: 355.14 K

Prediction:
Vapor-phase mole fraction of component 1: 0.528
Equilibrium temperature: 355.05 K

Parsed:
Y1 : 0.521 -> 0.528
T  : 355.14 -> 355.05

 49%|████▉     | 136/276 [04:03<04:10,  1.79s/it]

====================================================================================================
[136/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: C(CN)N
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.903
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.991
Equilibrium temperature: 376.95 K

Prediction:
Vapor-phase mole fraction of component 1: 0.990
Equilibrium temperature: 377.15 K

Parsed:
Y1 : 0.991 -> 0.99
T  : 376.95 -> 377.15

 50%|████▉     | 137/276 [04:05<04:08,  1.79s/it]

====================================================================================================
[137/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: O
Operating pressure: 13.330 kPa
Liquid-phase mole fraction of component 1: 0.300
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.604
Equilibrium temperature: 310.25 K

Prediction:
Vapor-phase mole fraction of component 1: 0.614
Equilibrium temperature: 309.45 K

Parsed:
Y1 : 0.604 -> 0.614
T  : 310.25 -> 309.45

 50%|█████     | 138/276 [04:06<04:06,  1.79s/it]

====================================================================================================
[138/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: C1COCOC1
Operating pressure: 79.990 kPa
Liquid-phase mole fraction of component 1: 0.589
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.735
Equilibrium temperature: 347.12 K

Prediction:
Vapor-phase mole fraction of component 1: 0.732
Equilibrium temperature: 347.40 K

Parsed:
Y1 : 0.735 -> 0.732
T  : 347.12 -> 347.4

 50%|█████     | 139/276 [04:08<04:04,  1.79s/it]

====================================================================================================
[139/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: CCCCO
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.288
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.676
Equilibrium temperature: 370.05 K

Prediction:
Vapor-phase mole fraction of component 1: 0.654
Equilibrium temperature: 369.35 K

Parsed:
Y1 : 0.676 -> 0.654
T  : 370.05 -> 369.35

 51%|█████     | 140/276 [04:10<04:02,  1.79s/it]

====================================================================================================
[140/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(=O)C
Component 2 SMILES: CCO
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.195
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.410
Equilibrium temperature: 342.25 K

Prediction:
Vapor-phase mole fraction of component 1: 0.424
Equilibrium temperature: 344.05 K

Parsed:
Y1 : 0.41 -> 0.424
T  : 342.25 -> 344.05

 51%|█████     | 141/276 [04:12<04:01,  1.79s/it]

====================================================================================================
[141/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: C(CO)O
Operating pressure: 1.330 kPa
Liquid-phase mole fraction of component 1: 0.196
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.969
Equilibrium temperature: 320.35 K

Prediction:
Vapor-phase mole fraction of component 1: 0.972
Equilibrium temperature: 325.25 K

Parsed:
Y1 : 0.969 -> 0.972
T  : 320.35 -> 325.25

 51%|█████▏    | 142/276 [04:14<03:59,  1.79s/it]

====================================================================================================
[142/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: CCC(=O)O
Operating pressure: 26.660 kPa
Liquid-phase mole fraction of component 1: 0.441
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.797
Equilibrium temperature: 343.85 K

Prediction:
Vapor-phase mole fraction of component 1: 0.790
Equilibrium temperature: 344.95 K

Parsed:
Y1 : 0.797 -> 0.79
T  : 343.85 -> 344.95

 52%|█████▏    | 143/276 [04:15<03:57,  1.79s/it]

====================================================================================================
[143/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCOC(=O)C
Component 2 SMILES: CCO
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.016
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.035
Equilibrium temperature: 350.85 K

Prediction:
Vapor-phase mole fraction of component 1: 0.038
Equilibrium temperature: 350.05 K

Parsed:
Y1 : 0.035 -> 0.038
T  : 350.85 -> 350.05

 52%|█████▏    | 144/276 [04:17<03:55,  1.79s/it]

====================================================================================================
[144/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: C1=CC=CC=C1
Operating pressure: 30.730 kPa
Liquid-phase mole fraction of component 1: 0.463
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.548
Equilibrium temperature: 302.92 K

Prediction:
Vapor-phase mole fraction of component 1: 0.550
Equilibrium temperature: 302.98 K

Parsed:
Y1 : 0.548 -> 0.55
T  : 302.92 -> 302.98

 53%|█████▎    | 145/276 [04:19<03:54,  1.79s/it]

====================================================================================================
[145/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(=O)O
Component 2 SMILES: O
Operating pressure: 26.660 kPa
Liquid-phase mole fraction of component 1: 0.989
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.962
Equilibrium temperature: 350.85 K

Prediction:
Vapor-phase mole fraction of component 1: 0.979
Equilibrium temperature: 349.05 K

Parsed:
Y1 : 0.962 -> 0.979
T  : 350.85 -> 349.05

 53%|█████▎    | 146/276 [04:21<03:52,  1.79s/it]

====================================================================================================
[146/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: CCC(=O)O
Operating pressure: 26.660 kPa
Liquid-phase mole fraction of component 1: 0.120
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.507
Equilibrium temperature: 357.65 K

Prediction:
Vapor-phase mole fraction of component 1: 0.500
Equilibrium temperature: 353.05 K

Parsed:
Y1 : 0.507 -> 0.5
T  : 357.65 -> 353.05

 53%|█████▎    | 147/276 [04:23<03:50,  1.79s/it]

====================================================================================================
[147/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: C(CO)O
Operating pressure: 1.330 kPa
Liquid-phase mole fraction of component 1: 0.648
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.998
Equilibrium temperature: 293.45 K

Prediction:
Vapor-phase mole fraction of component 1: 0.997
Equilibrium temperature: 295.15 K

Parsed:
Y1 : 0.998 -> 0.997
T  : 293.45 -> 295.15

 54%|█████▎    | 148/276 [04:24<03:48,  1.79s/it]

====================================================================================================
[148/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(=O)C
Component 2 SMILES: O
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.900
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.937
Equilibrium temperature: 330.22 K

Prediction:
Vapor-phase mole fraction of component 1: 0.944
Equilibrium temperature: 330.05 K

Parsed:
Y1 : 0.937 -> 0.944
T  : 330.22 -> 330.05

 54%|█████▍    | 149/276 [04:26<03:46,  1.79s/it]

====================================================================================================
[149/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(=O)O
Component 2 SMILES: O
Operating pressure: 97.990 kPa
Liquid-phase mole fraction of component 1: 0.411
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.254
Equilibrium temperature: 376.05 K

Prediction:
Vapor-phase mole fraction of component 1: 0.276
Equilibrium temperature: 375.95 K

Parsed:
Y1 : 0.254 -> 0.276
T  : 376.05 -> 375.95

 54%|█████▍    | 150/276 [04:28<03:45,  1.79s/it]

====================================================================================================
[150/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: C1=CC=CC=C1
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.046
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.339
Equilibrium temperature: 341.10 K

Prediction:
Vapor-phase mole fraction of component 1: 0.346
Equilibrium temperature: 340.05 K

Parsed:
Y1 : 0.339 -> 0.346
T  : 341.1 -> 340.05

 55%|█████▍    | 151/276 [04:30<03:43,  1.79s/it]

====================================================================================================
[151/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: CCCC(=O)O
Operating pressure: 26.660 kPa
Liquid-phase mole fraction of component 1: 0.352
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.914
Equilibrium temperature: 345.05 K

Prediction:
Vapor-phase mole fraction of component 1: 0.912
Equilibrium temperature: 344.95 K

Parsed:
Y1 : 0.914 -> 0.912
T  : 345.05 -> 344.95

 55%|█████▌    | 152/276 [04:31<03:41,  1.79s/it]

====================================================================================================
[152/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: C1COCCO1
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.900
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.865
Equilibrium temperature: 369.45 K

Prediction:
Vapor-phase mole fraction of component 1: 0.850
Equilibrium temperature: 368.95 K

Parsed:
Y1 : 0.865 -> 0.85
T  : 369.45 -> 368.95

 55%|█████▌    | 153/276 [04:33<03:39,  1.79s/it]

====================================================================================================
[153/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: CCC(C)C=O
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.000
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.000
Equilibrium temperature: 374.85 K

Prediction:
Vapor-phase mole fraction of component 1: 0.000
Equilibrium temperature: 375.15 K

Parsed:
Y1 : 0.0 -> 0.0
T  : 374.85 -> 375.15

 56%|█████▌    | 154/276 [04:35<03:38,  1.79s/it]

====================================================================================================
[154/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: C(=O)O
Component 2 SMILES: O
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.026
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.011
Equilibrium temperature: 373.85 K

Prediction:
Vapor-phase mole fraction of component 1: 0.012
Equilibrium temperature: 373.95 K

Parsed:
Y1 : 0.011 -> 0.012
T  : 373.85 -> 373.95

 56%|█████▌    | 155/276 [04:37<03:36,  1.79s/it]

====================================================================================================
[155/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: CCOC(=O)C
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.544
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.507
Equilibrium temperature: 345.50 K

Prediction:
Vapor-phase mole fraction of component 1: 0.502
Equilibrium temperature: 345.95 K

Parsed:
Y1 : 0.507 -> 0.502
T  : 345.5 -> 345.95

 57%|█████▋    | 156/276 [04:39<03:34,  1.79s/it]

====================================================================================================
[156/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: CC(C)OC(C)C
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.370
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.536
Equilibrium temperature: 347.46 K

Prediction:
Vapor-phase mole fraction of component 1: 0.520
Equilibrium temperature: 346.55 K

Parsed:
Y1 : 0.536 -> 0.52
T  : 347.46 -> 346.55

 57%|█████▋    | 157/276 [04:40<03:32,  1.79s/it]

====================================================================================================
[157/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: C1COCOC1
Operating pressure: 26.660 kPa
Liquid-phase mole fraction of component 1: 0.181
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.435
Equilibrium temperature: 325.97 K

Prediction:
Vapor-phase mole fraction of component 1: 0.456
Equilibrium temperature: 327.90 K

Parsed:
Y1 : 0.435 -> 0.456
T  : 325.97 -> 327.9

 57%|█████▋    | 158/276 [04:42<03:30,  1.79s/it]

====================================================================================================
[158/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: CC(C)(C(C)(C)O)O
Operating pressure: 14.670 kPa
Liquid-phase mole fraction of component 1: 0.213
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.875
Equilibrium temperature: 869.15 K

Prediction:
Vapor-phase mole fraction of component 1: 0.856
Equilibrium temperature: 903.15 K

Parsed:
Y1 : 0.875 -> 0.856
T  : 869.15 -> 903.15

 58%|█████▊    | 159/276 [04:44<03:29,  1.79s/it]

====================================================================================================
[159/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: C(Cl)(Cl)(Cl)Cl
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.124
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.500
Equilibrium temperature: 330.10 K

Prediction:
Vapor-phase mole fraction of component 1: 0.450
Equilibrium temperature: 330.05 K

Parsed:
Y1 : 0.5 -> 0.45
T  : 330.1 -> 330.05

 58%|█████▊    | 160/276 [04:46<03:27,  1.79s/it]

====================================================================================================
[160/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: C=O
Component 2 SMILES: O
Operating pressure: 26.660 kPa
Liquid-phase mole fraction of component 1: 0.094
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.066
Equilibrium temperature: 340.25 K

Prediction:
Vapor-phase mole fraction of component 1: 0.060
Equilibrium temperature: 339.95 K

Parsed:
Y1 : 0.066 -> 0.06
T  : 340.25 -> 339.95

 58%|█████▊    | 161/276 [04:48<03:25,  1.79s/it]

====================================================================================================
[161/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: C(=O)O
Component 2 SMILES: O
Operating pressure: 6.670 kPa
Liquid-phase mole fraction of component 1: 0.535
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.638
Equilibrium temperature: 314.35 K

Prediction:
Vapor-phase mole fraction of component 1: 0.620
Equilibrium temperature: 313.05 K

Parsed:
Y1 : 0.638 -> 0.62
T  : 314.35 -> 313.05

 59%|█████▊    | 162/276 [04:49<03:23,  1.79s/it]

====================================================================================================
[162/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: CNC=O
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.664
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.983
Equilibrium temperature: 383.35 K

Prediction:
Vapor-phase mole fraction of component 1: 0.980
Equilibrium temperature: 382.05 K

Parsed:
Y1 : 0.983 -> 0.98
T  : 383.35 -> 382.05

 59%|█████▉    | 163/276 [04:51<03:21,  1.79s/it]

====================================================================================================
[163/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: C1COCOC1
Operating pressure: 79.990 kPa
Liquid-phase mole fraction of component 1: 0.904
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.910
Equilibrium temperature: 345.41 K

Prediction:
Vapor-phase mole fraction of component 1: 0.910
Equilibrium temperature: 345.57 K

Parsed:
Y1 : 0.91 -> 0.91
T  : 345.41 -> 345.57

 59%|█████▉    | 164/276 [04:53<03:20,  1.79s/it]

====================================================================================================
[164/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: CCOC(=O)C=C
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.643
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.740
Equilibrium temperature: 351.85 K

Prediction:
Vapor-phase mole fraction of component 1: 0.735
Equilibrium temperature: 351.75 K

Parsed:
Y1 : 0.74 -> 0.735
T  : 351.85 -> 351.75

 60%|█████▉    | 165/276 [04:55<03:18,  1.79s/it]

====================================================================================================
[165/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(C)(C)N
Component 2 SMILES: CO
Operating pressure: 97.330 kPa
Liquid-phase mole fraction of component 1: 0.547
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.686
Equilibrium temperature: 335.85 K

Prediction:
Vapor-phase mole fraction of component 1: 0.642
Equilibrium temperature: 338.85 K

Parsed:
Y1 : 0.686 -> 0.642
T  : 335.85 -> 338.85

 60%|██████    | 166/276 [04:57<03:16,  1.79s/it]

====================================================================================================
[166/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(=O)C
Component 2 SMILES: O
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.400
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.843
Equilibrium temperature: 333.54 K

Prediction:
Vapor-phase mole fraction of component 1: 0.845
Equilibrium temperature: 333.05 K

Parsed:
Y1 : 0.843 -> 0.845
T  : 333.54 -> 333.05

 61%|██████    | 167/276 [04:58<03:14,  1.79s/it]

====================================================================================================
[167/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: O
Operating pressure: 98.070 kPa
Liquid-phase mole fraction of component 1: 0.685
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.743
Equilibrium temperature: 352.05 K

Prediction:
Vapor-phase mole fraction of component 1: 0.740
Equilibrium temperature: 351.95 K

Parsed:
Y1 : 0.743 -> 0.74
T  : 352.05 -> 351.95

 61%|██████    | 168/276 [05:00<03:12,  1.79s/it]

====================================================================================================
[168/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: C(=O)O
Operating pressure: 9.330 kPa
Liquid-phase mole fraction of component 1: 0.907
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.953
Equilibrium temperature: 318.85 K

Prediction:
Vapor-phase mole fraction of component 1: 0.956
Equilibrium temperature: 318.55 K

Parsed:
Y1 : 0.953 -> 0.956
T  : 318.85 -> 318.55

 61%|██████    | 169/276 [05:02<03:11,  1.79s/it]

====================================================================================================
[169/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: C(CN)N
Operating pressure: 13.330 kPa
Liquid-phase mole fraction of component 1: 0.367
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.279
Equilibrium temperature: 341.88 K

Prediction:
Vapor-phase mole fraction of component 1: 0.279
Equilibrium temperature: 342.45 K

Parsed:
Y1 : 0.279 -> 0.279
T  : 341.88 -> 342.45

 62%|██████▏   | 170/276 [05:04<03:09,  1.79s/it]

====================================================================================================
[170/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: CCO
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.248
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.362
Equilibrium temperature: 347.15 K

Prediction:
Vapor-phase mole fraction of component 1: 0.392
Equilibrium temperature: 347.75 K

Parsed:
Y1 : 0.362 -> 0.392
T  : 347.15 -> 347.75

 62%|██████▏   | 171/276 [05:05<03:07,  1.79s/it]

====================================================================================================
[171/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: C(C(CO)O)O
Operating pressure: 48.000 kPa
Liquid-phase mole fraction of component 1: 0.560
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.994
Equilibrium temperature: 413.15 K

Prediction:
Vapor-phase mole fraction of component 1: 0.997
Equilibrium temperature: 403.15 K

Parsed:
Y1 : 0.994 -> 0.997
T  : 413.15 -> 403.15

 62%|██████▏   | 172/276 [05:07<03:05,  1.79s/it]

====================================================================================================
[172/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: C(=O)O
Component 2 SMILES: O
Operating pressure: 26.660 kPa
Liquid-phase mole fraction of component 1: 0.302
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.217
Equilibrium temperature: 343.45 K

Prediction:
Vapor-phase mole fraction of component 1: 0.200
Equilibrium temperature: 342.95 K

Parsed:
Y1 : 0.217 -> 0.2
T  : 343.45 -> 342.95

 63%|██████▎   | 173/276 [05:09<03:03,  1.79s/it]

====================================================================================================
[173/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(C=O)O
Component 2 SMILES: CO
Operating pressure: 79.990 kPa
Liquid-phase mole fraction of component 1: 0.120
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.286
Equilibrium temperature: 326.31 K

Prediction:
Vapor-phase mole fraction of component 1: 0.260
Equilibrium temperature: 325.35 K

Parsed:
Y1 : 0.286 -> 0.26
T  : 326.31 -> 325.35

 63%|██████▎   | 174/276 [05:11<03:02,  1.78s/it]

====================================================================================================
[174/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: CCC(=O)O
Operating pressure: 13.330 kPa
Liquid-phase mole fraction of component 1: 0.059
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.375
Equilibrium temperature: 346.65 K

Prediction:
Vapor-phase mole fraction of component 1: 0.270
Equilibrium temperature: 346.35 K

Parsed:
Y1 : 0.375 -> 0.27
T  : 346.65 -> 346.35

 63%|██████▎   | 175/276 [05:13<03:00,  1.79s/it]

====================================================================================================
[175/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCCC=O
Component 2 SMILES: CO
Operating pressure: 31.400 kPa
Liquid-phase mole fraction of component 1: 0.040
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.089
Equilibrium temperature: 309.35 K

Prediction:
Vapor-phase mole fraction of component 1: 0.070
Equilibrium temperature: 309.25 K

Parsed:
Y1 : 0.089 -> 0.07
T  : 309.35 -> 309.25

 64%|██████▍   | 176/276 [05:14<02:58,  1.79s/it]

====================================================================================================
[176/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: C(=O)O
Component 2 SMILES: O
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.715
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.769
Equilibrium temperature: 380.25 K

Prediction:
Vapor-phase mole fraction of component 1: 0.770
Equilibrium temperature: 380.65 K

Parsed:
Y1 : 0.769 -> 0.77
T  : 380.25 -> 380.65

 64%|██████▍   | 177/276 [05:16<02:56,  1.78s/it]

====================================================================================================
[177/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: C=O
Component 2 SMILES: CO
Operating pressure: 26.660 kPa
Liquid-phase mole fraction of component 1: 0.199
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.046
Equilibrium temperature: 312.15 K

Prediction:
Vapor-phase mole fraction of component 1: 0.049
Equilibrium temperature: 312.45 K

Parsed:
Y1 : 0.046 -> 0.049
T  : 312.15 -> 312.45

 64%|██████▍   | 178/276 [05:18<02:54,  1.78s/it]

====================================================================================================
[178/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(=O)C
Component 2 SMILES: CO
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.870
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.853
Equilibrium temperature: 328.65 K

Prediction:
Vapor-phase mole fraction of component 1: 0.850
Equilibrium temperature: 328.75 K

Parsed:
Y1 : 0.853 -> 0.85
T  : 328.65 -> 328.75

 65%|██████▍   | 179/276 [05:20<02:53,  1.78s/it]

====================================================================================================
[179/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(=O)O
Component 2 SMILES: O
Operating pressure: 46.660 kPa
Liquid-phase mole fraction of component 1: 0.108
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.067
Equilibrium temperature: 352.45 K

Prediction:
Vapor-phase mole fraction of component 1: 0.080
Equilibrium temperature: 351.45 K

Parsed:
Y1 : 0.067 -> 0.08
T  : 352.45 -> 351.45

 65%|██████▌   | 180/276 [05:22<02:51,  1.78s/it]

====================================================================================================
[180/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: C(C(CO)O)O
Operating pressure: 8.000 kPa
Liquid-phase mole fraction of component 1: 0.310
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.974
Equilibrium temperature: 403.15 K

Prediction:
Vapor-phase mole fraction of component 1: 0.989
Equilibrium temperature: 393.15 K

Parsed:
Y1 : 0.974 -> 0.989
T  : 403.15 -> 393.15

 66%|██████▌   | 181/276 [05:23<02:49,  1.78s/it]

====================================================================================================
[181/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: C1COCOC1
Operating pressure: 26.660 kPa
Liquid-phase mole fraction of component 1: 0.311
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.553
Equilibrium temperature: 323.01 K

Prediction:
Vapor-phase mole fraction of component 1: 0.566
Equilibrium temperature: 322.49 K

Parsed:
Y1 : 0.553 -> 0.566
T  : 323.01 -> 322.49

 66%|██████▌   | 182/276 [05:25<02:47,  1.78s/it]

====================================================================================================
[182/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCNCC
Component 2 SMILES: CCO
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.074
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.088
Equilibrium temperature: 351.15 K

Prediction:
Vapor-phase mole fraction of component 1: 0.098
Equilibrium temperature: 351.55 K

Parsed:
Y1 : 0.088 -> 0.098
T  : 351.15 -> 351.55

 66%|██████▋   | 183/276 [05:27<02:45,  1.78s/it]

====================================================================================================
[183/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: C(=O)O
Component 2 SMILES: O
Operating pressure: 79.990 kPa
Liquid-phase mole fraction of component 1: 0.186
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.096
Equilibrium temperature: 369.75 K

Prediction:
Vapor-phase mole fraction of component 1: 0.100
Equilibrium temperature: 369.45 K

Parsed:
Y1 : 0.096 -> 0.1
T  : 369.75 -> 369.45

 67%|██████▋   | 184/276 [05:29<02:44,  1.79s/it]

====================================================================================================
[184/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCNCC
Component 2 SMILES: CCO
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.145
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.186
Equilibrium temperature: 350.25 K

Prediction:
Vapor-phase mole fraction of component 1: 0.220
Equilibrium temperature: 349.85 K

Parsed:
Y1 : 0.186 -> 0.22
T  : 350.25 -> 349.85

 67%|██████▋   | 185/276 [05:30<02:42,  1.79s/it]

====================================================================================================
[185/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(=O)O
Component 2 SMILES: O
Operating pressure: 97.990 kPa
Liquid-phase mole fraction of component 1: 0.145
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.089
Equilibrium temperature: 373.55 K

Prediction:
Vapor-phase mole fraction of component 1: 0.098
Equilibrium temperature: 373.85 K

Parsed:
Y1 : 0.089 -> 0.098
T  : 373.55 -> 373.85

 67%|██████▋   | 186/276 [05:32<02:40,  1.79s/it]

====================================================================================================
[186/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: CCOC(=O)C
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.683
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.609
Equilibrium temperature: 346.05 K

Prediction:
Vapor-phase mole fraction of component 1: 0.590
Equilibrium temperature: 345.55 K

Parsed:
Y1 : 0.609 -> 0.59
T  : 346.05 -> 345.55

 68%|██████▊   | 187/276 [05:34<02:38,  1.79s/it]

====================================================================================================
[187/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: C1=CC=C(C=C1)O
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.015
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.589
Equilibrium temperature: 423.15 K

Prediction:
Vapor-phase mole fraction of component 1: 0.460
Equilibrium temperature: 430.15 K

Parsed:
Y1 : 0.589 -> 0.46
T  : 423.15 -> 430.15

 68%|██████▊   | 188/276 [05:36<02:37,  1.79s/it]

====================================================================================================
[188/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: C(=O)O
Component 2 SMILES: O
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.252
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.157
Equilibrium temperature: 377.75 K

Prediction:
Vapor-phase mole fraction of component 1: 0.164
Equilibrium temperature: 377.15 K

Parsed:
Y1 : 0.157 -> 0.164
T  : 377.75 -> 377.15

 68%|██████▊   | 189/276 [05:38<02:35,  1.79s/it]

====================================================================================================
[189/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: O
Operating pressure: 101.060 kPa
Liquid-phase mole fraction of component 1: 0.327
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.415
Equilibrium temperature: 360.77 K

Prediction:
Vapor-phase mole fraction of component 1: 0.402
Equilibrium temperature: 360.89 K

Parsed:
Y1 : 0.415 -> 0.402
T  : 360.77 -> 360.89

 69%|██████▉   | 190/276 [05:39<02:33,  1.79s/it]

====================================================================================================
[190/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: O
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.067
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.370
Equilibrium temperature: 361.55 K

Prediction:
Vapor-phase mole fraction of component 1: 0.354
Equilibrium temperature: 362.00 K

Parsed:
Y1 : 0.37 -> 0.354
T  : 361.55 -> 362.0

 69%|██████▉   | 191/276 [05:41<02:31,  1.79s/it]

====================================================================================================
[191/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: C(CO)O
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.754
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.999
Equilibrium temperature: 338.65 K

Prediction:
Vapor-phase mole fraction of component 1: 0.999
Equilibrium temperature: 339.95 K

Parsed:
Y1 : 0.999 -> 0.999
T  : 338.65 -> 339.95

 70%|██████▉   | 192/276 [05:43<02:30,  1.79s/it]

====================================================================================================
[192/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: CCCC(=O)O
Operating pressure: 26.660 kPa
Liquid-phase mole fraction of component 1: 0.027
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.419
Equilibrium temperature: 384.35 K

Prediction:
Vapor-phase mole fraction of component 1: 0.424
Equilibrium temperature: 389.05 K

Parsed:
Y1 : 0.419 -> 0.424
T  : 384.35 -> 389.05

 70%|██████▉   | 193/276 [05:45<02:28,  1.79s/it]

====================================================================================================
[193/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(C=O)O
Component 2 SMILES: CO
Operating pressure: 585.660 kPa
Liquid-phase mole fraction of component 1: 0.185
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.253
Equilibrium temperature: 384.79 K

Prediction:
Vapor-phase mole fraction of component 1: 0.290
Equilibrium temperature: 383.50 K

Parsed:
Y1 : 0.253 -> 0.29
T  : 384.79 -> 383.5

 70%|███████   | 194/276 [05:47<02:26,  1.79s/it]

====================================================================================================
[194/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: CCOC(=O)C=C
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.484
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.665
Equilibrium temperature: 353.95 K

Prediction:
Vapor-phase mole fraction of component 1: 0.667
Equilibrium temperature: 353.15 K

Parsed:
Y1 : 0.665 -> 0.667
T  : 353.95 -> 353.15

 71%|███████   | 195/276 [05:48<02:25,  1.79s/it]

====================================================================================================
[195/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(C)O
Component 2 SMILES: O
Operating pressure: 25.330 kPa
Liquid-phase mole fraction of component 1: 0.758
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.724
Equilibrium temperature: 322.55 K

Prediction:
Vapor-phase mole fraction of component 1: 0.722
Equilibrium temperature: 322.39 K

Parsed:
Y1 : 0.724 -> 0.722
T  : 322.55 -> 322.39

 71%|███████   | 196/276 [05:50<02:23,  1.80s/it]

====================================================================================================
[196/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: C1=CC=CC=C1
Operating pressure: 30.730 kPa
Liquid-phase mole fraction of component 1: 0.985
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.946
Equilibrium temperature: 313.08 K

Prediction:
Vapor-phase mole fraction of component 1: 0.930
Equilibrium temperature: 307.19 K

Parsed:
Y1 : 0.946 -> 0.93
T  : 313.08 -> 307.19

 71%|███████▏  | 197/276 [05:52<02:21,  1.80s/it]

====================================================================================================
[197/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: C(CO)O
Operating pressure: 6.670 kPa
Liquid-phase mole fraction of component 1: 0.308
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.980
Equilibrium temperature: 334.15 K

Prediction:
Vapor-phase mole fraction of component 1: 0.984
Equilibrium temperature: 333.15 K

Parsed:
Y1 : 0.98 -> 0.984
T  : 334.15 -> 333.15

 72%|███████▏  | 198/276 [05:54<02:19,  1.79s/it]

====================================================================================================
[198/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(=O)O
Component 2 SMILES: O
Operating pressure: 46.660 kPa
Liquid-phase mole fraction of component 1: 0.507
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.377
Equilibrium temperature: 355.15 K

Prediction:
Vapor-phase mole fraction of component 1: 0.390
Equilibrium temperature: 357.15 K

Parsed:
Y1 : 0.377 -> 0.39
T  : 355.15 -> 357.15

 72%|███████▏  | 199/276 [05:56<02:17,  1.79s/it]

====================================================================================================
[199/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: O
Operating pressure: 101.060 kPa
Liquid-phase mole fraction of component 1: 0.007
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.131
Equilibrium temperature: 369.62 K

Prediction:
Vapor-phase mole fraction of component 1: 0.074
Equilibrium temperature: 371.30 K

Parsed:
Y1 : 0.131 -> 0.074
T  : 369.62 -> 371.3

 72%|███████▏  | 200/276 [05:57<02:16,  1.79s/it]

====================================================================================================
[200/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: C(=O)O
Component 2 SMILES: O
Operating pressure: 6.670 kPa
Liquid-phase mole fraction of component 1: 0.000
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.000
Equilibrium temperature: 311.25 K

Prediction:
Vapor-phase mole fraction of component 1: 0.000
Equilibrium temperature: 311.25 K

Parsed:
Y1 : 0.0 -> 0.0
T  : 311.25 -> 311.25

 73%|███████▎  | 201/276 [05:59<02:14,  1.79s/it]

====================================================================================================
[201/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: O
Operating pressure: 13.330 kPa
Liquid-phase mole fraction of component 1: 0.050
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.284
Equilibrium temperature: 318.05 K

Prediction:
Vapor-phase mole fraction of component 1: 0.325
Equilibrium temperature: 317.95 K

Parsed:
Y1 : 0.284 -> 0.325
T  : 318.05 -> 317.95

 73%|███████▎  | 202/276 [06:01<02:12,  1.79s/it]

====================================================================================================
[202/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: CC(=O)O
Operating pressure: 53.330 kPa
Liquid-phase mole fraction of component 1: 0.907
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.936
Equilibrium temperature: 356.85 K

Prediction:
Vapor-phase mole fraction of component 1: 0.935
Equilibrium temperature: 356.55 K

Parsed:
Y1 : 0.936 -> 0.935
T  : 356.85 -> 356.55

 74%|███████▎  | 203/276 [06:03<02:10,  1.79s/it]

====================================================================================================
[203/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: C1COCOC1
Operating pressure: 26.660 kPa
Liquid-phase mole fraction of component 1: 0.481
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.651
Equilibrium temperature: 320.89 K

Prediction:
Vapor-phase mole fraction of component 1: 0.649
Equilibrium temperature: 320.39 K

Parsed:
Y1 : 0.651 -> 0.649
T  : 320.89 -> 320.39

 74%|███████▍  | 204/276 [06:04<02:08,  1.79s/it]

====================================================================================================
[204/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: COCCl
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.817
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.845
Equilibrium temperature: 371.05 K

Prediction:
Vapor-phase mole fraction of component 1: 0.842
Equilibrium temperature: 371.35 K

Parsed:
Y1 : 0.845 -> 0.842
T  : 371.05 -> 371.35

 74%|███████▍  | 205/276 [06:06<02:06,  1.79s/it]

====================================================================================================
[205/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: C1=CC=CC=C1
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.925
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.812
Equilibrium temperature: 334.05 K

Prediction:
Vapor-phase mole fraction of component 1: 0.805
Equilibrium temperature: 334.13 K

Parsed:
Y1 : 0.812 -> 0.805
T  : 334.05 -> 334.13

 75%|███████▍  | 206/276 [06:08<02:04,  1.79s/it]

====================================================================================================
[206/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: CC(=O)O
Operating pressure: 273.710 kPa
Liquid-phase mole fraction of component 1: 0.831
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.886
Equilibrium temperature: 404.85 K

Prediction:
Vapor-phase mole fraction of component 1: 0.889
Equilibrium temperature: 404.05 K

Parsed:
Y1 : 0.886 -> 0.889
T  : 404.85 -> 404.05

 75%|███████▌  | 207/276 [06:10<02:03,  1.79s/it]

====================================================================================================
[207/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC1CO1
Component 2 SMILES: O
Operating pressure: 99.990 kPa
Liquid-phase mole fraction of component 1: 0.925
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.968
Equilibrium temperature: 308.05 K

Prediction:
Vapor-phase mole fraction of component 1: 0.960
Equilibrium temperature: 308.15 K

Parsed:
Y1 : 0.968 -> 0.96
T  : 308.05 -> 308.15

 75%|███████▌  | 208/276 [06:12<02:01,  1.79s/it]

====================================================================================================
[208/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: C(Cl)(Cl)Cl
Component 2 SMILES: CO
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.146
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.304
Equilibrium temperature: 332.45 K

Prediction:
Vapor-phase mole fraction of component 1: 0.340
Equilibrium temperature: 330.05 K

Parsed:
Y1 : 0.304 -> 0.34
T  : 332.45 -> 330.05

 76%|███████▌  | 209/276 [06:13<01:59,  1.79s/it]

====================================================================================================
[209/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCNCC
Component 2 SMILES: CCO
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.704
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.875
Equilibrium temperature: 334.95 K

Prediction:
Vapor-phase mole fraction of component 1: 0.846
Equilibrium temperature: 333.15 K

Parsed:
Y1 : 0.875 -> 0.846
T  : 334.95 -> 333.15

 76%|███████▌  | 210/276 [06:15<01:57,  1.78s/it]

====================================================================================================
[210/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(C=O)O
Component 2 SMILES: CO
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.321
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.477
Equilibrium temperature: 328.65 K

Prediction:
Vapor-phase mole fraction of component 1: 0.474
Equilibrium temperature: 328.15 K

Parsed:
Y1 : 0.477 -> 0.474
T  : 328.65 -> 328.15

 76%|███████▋  | 211/276 [06:17<01:56,  1.79s/it]

====================================================================================================
[211/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: CN(C)C=O
Operating pressure: 53.330 kPa
Liquid-phase mole fraction of component 1: 0.629
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.896
Equilibrium temperature: 365.05 K

Prediction:
Vapor-phase mole fraction of component 1: 0.899
Equilibrium temperature: 363.00 K

Parsed:
Y1 : 0.896 -> 0.899
T  : 365.05 -> 363.0

 77%|███████▋  | 212/276 [06:19<01:54,  1.79s/it]

====================================================================================================
[212/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: CCCC=O
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.610
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.689
Equilibrium temperature: 337.15 K

Prediction:
Vapor-phase mole fraction of component 1: 0.600
Equilibrium temperature: 335.15 K

Parsed:
Y1 : 0.689 -> 0.6
T  : 337.15 -> 335.15

 77%|███████▋  | 213/276 [06:21<01:52,  1.79s/it]

====================================================================================================
[213/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: CCN(CC)CC
Operating pressure: 97.330 kPa
Liquid-phase mole fraction of component 1: 0.053
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.208
Equilibrium temperature: 356.25 K

Prediction:
Vapor-phase mole fraction of component 1: 0.205
Equilibrium temperature: 358.15 K

Parsed:
Y1 : 0.208 -> 0.205
T  : 356.25 -> 358.15

 78%|███████▊  | 214/276 [06:22<01:50,  1.79s/it]

====================================================================================================
[214/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: C=O
Component 2 SMILES: O
Operating pressure: 8.000 kPa
Liquid-phase mole fraction of component 1: 0.211
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.060
Equilibrium temperature: 318.85 K

Prediction:
Vapor-phase mole fraction of component 1: 0.054
Equilibrium temperature: 319.65 K

Parsed:
Y1 : 0.06 -> 0.054
T  : 318.85 -> 319.65

 78%|███████▊  | 215/276 [06:24<01:48,  1.78s/it]

====================================================================================================
[215/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: CCCCO
Operating pressure: 102.260 kPa
Liquid-phase mole fraction of component 1: 0.980
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.760
Equilibrium temperature: 365.95 K

Prediction:
Vapor-phase mole fraction of component 1: 0.775
Equilibrium temperature: 366.25 K

Parsed:
Y1 : 0.76 -> 0.775
T  : 365.95 -> 366.25

 78%|███████▊  | 216/276 [06:26<01:47,  1.78s/it]

====================================================================================================
[216/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: CNC=O
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.514
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.964
Equilibrium temperature: 390.75 K

Prediction:
Vapor-phase mole fraction of component 1: 0.960
Equilibrium temperature: 393.05 K

Parsed:
Y1 : 0.964 -> 0.96
T  : 390.75 -> 393.05

 79%|███████▊  | 217/276 [06:28<01:45,  1.78s/it]

====================================================================================================
[217/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: CCCCO
Operating pressure: 102.260 kPa
Liquid-phase mole fraction of component 1: 0.992
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.850
Equilibrium temperature: 368.95 K

Prediction:
Vapor-phase mole fraction of component 1: 0.800
Equilibrium temperature: 366.65 K

Parsed:
Y1 : 0.85 -> 0.8
T  : 368.95 -> 366.65

 79%|███████▉  | 218/276 [06:29<01:43,  1.78s/it]

====================================================================================================
[218/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: O
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.255
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.552
Equilibrium temperature: 355.45 K

Prediction:
Vapor-phase mole fraction of component 1: 0.565
Equilibrium temperature: 355.05 K

Parsed:
Y1 : 0.552 -> 0.565
T  : 355.45 -> 355.05

 79%|███████▉  | 219/276 [06:31<01:41,  1.78s/it]

====================================================================================================
[219/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(C=O)O
Component 2 SMILES: CO
Operating pressure: 79.990 kPa
Liquid-phase mole fraction of component 1: 0.843
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.788
Equilibrium temperature: 320.81 K

Prediction:
Vapor-phase mole fraction of component 1: 0.770
Equilibrium temperature: 320.75 K

Parsed:
Y1 : 0.788 -> 0.77
T  : 320.81 -> 320.75

 80%|███████▉  | 220/276 [06:33<01:39,  1.78s/it]

====================================================================================================
[220/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: CNC=O
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.847
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.992
Equilibrium temperature: 377.15 K

Prediction:
Vapor-phase mole fraction of component 1: 0.995
Equilibrium temperature: 377.15 K

Parsed:
Y1 : 0.992 -> 0.995
T  : 377.15 -> 377.15

 80%|████████  | 221/276 [06:35<01:38,  1.78s/it]

====================================================================================================
[221/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: C(=O)O
Component 2 SMILES: O
Operating pressure: 79.990 kPa
Liquid-phase mole fraction of component 1: 0.029
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.013
Equilibrium temperature: 367.35 K

Prediction:
Vapor-phase mole fraction of component 1: 0.012
Equilibrium temperature: 367.65 K

Parsed:
Y1 : 0.013 -> 0.012
T  : 367.35 -> 367.65

 80%|████████  | 222/276 [06:37<01:36,  1.78s/it]

====================================================================================================
[222/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: C1COCOC1
Operating pressure: 79.990 kPa
Liquid-phase mole fraction of component 1: 0.303
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.566
Equilibrium temperature: 351.78 K

Prediction:
Vapor-phase mole fraction of component 1: 0.568
Equilibrium temperature: 352.50 K

Parsed:
Y1 : 0.566 -> 0.568
T  : 351.78 -> 352.5

 81%|████████  | 223/276 [06:38<01:34,  1.78s/it]

====================================================================================================
[223/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: CCCC(=O)O
Operating pressure: 13.330 kPa
Liquid-phase mole fraction of component 1: 0.512
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.943
Equilibrium temperature: 326.65 K

Prediction:
Vapor-phase mole fraction of component 1: 0.946
Equilibrium temperature: 325.95 K

Parsed:
Y1 : 0.943 -> 0.946
T  : 326.65 -> 325.95

 81%|████████  | 224/276 [06:40<01:32,  1.79s/it]

====================================================================================================
[224/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: C(CN)C=O
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.045
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.300
Equilibrium temperature: 413.15 K

Prediction:
Vapor-phase mole fraction of component 1: 0.300
Equilibrium temperature: 407.15 K

Parsed:
Y1 : 0.3 -> 0.3
T  : 413.15 -> 407.15

 82%|████████▏ | 225/276 [06:42<01:31,  1.78s/it]

====================================================================================================
[225/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: C(=O)O
Component 2 SMILES: O
Operating pressure: 79.990 kPa
Liquid-phase mole fraction of component 1: 0.613
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.647
Equilibrium temperature: 373.85 K

Prediction:
Vapor-phase mole fraction of component 1: 0.626
Equilibrium temperature: 373.95 K

Parsed:
Y1 : 0.647 -> 0.626
T  : 373.85 -> 373.95

 82%|████████▏ | 226/276 [06:44<01:29,  1.79s/it]

====================================================================================================
[226/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(=O)O
Component 2 SMILES: O
Operating pressure: 97.990 kPa
Liquid-phase mole fraction of component 1: 0.448
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.320
Equilibrium temperature: 376.85 K

Prediction:
Vapor-phase mole fraction of component 1: 0.318
Equilibrium temperature: 376.15 K

Parsed:
Y1 : 0.32 -> 0.318
T  : 376.85 -> 376.15

 82%|████████▏ | 227/276 [06:45<01:27,  1.79s/it]

====================================================================================================
[227/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: C(=O)O
Component 2 SMILES: O
Operating pressure: 13.330 kPa
Liquid-phase mole fraction of component 1: 0.696
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.826
Equilibrium temperature: 325.45 K

Prediction:
Vapor-phase mole fraction of component 1: 0.822
Equilibrium temperature: 327.15 K

Parsed:
Y1 : 0.826 -> 0.822
T  : 325.45 -> 327.15

 83%|████████▎ | 228/276 [06:47<01:25,  1.78s/it]

====================================================================================================
[228/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(C)O
Component 2 SMILES: O
Operating pressure: 25.330 kPa
Liquid-phase mole fraction of component 1: 0.030
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.294
Equilibrium temperature: 330.81 K

Prediction:
Vapor-phase mole fraction of component 1: 0.359
Equilibrium temperature: 327.97 K

Parsed:
Y1 : 0.294 -> 0.359
T  : 330.81 -> 327.97

 83%|████████▎ | 229/276 [06:49<01:23,  1.78s/it]

====================================================================================================
[229/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: CN(C)C=O
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.360
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.775
Equilibrium temperature: 390.45 K

Prediction:
Vapor-phase mole fraction of component 1: 0.750
Equilibrium temperature: 389.05 K

Parsed:
Y1 : 0.775 -> 0.75
T  : 390.45 -> 389.05

 83%|████████▎ | 230/276 [06:51<01:22,  1.79s/it]

====================================================================================================
[230/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(=O)C
Component 2 SMILES: CO
Operating pressure: 100.260 kPa
Liquid-phase mole fraction of component 1: 0.611
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.666
Equilibrium temperature: 328.60 K

Prediction:
Vapor-phase mole fraction of component 1: 0.670
Equilibrium temperature: 328.70 K

Parsed:
Y1 : 0.666 -> 0.67
T  : 328.6 -> 328.7

 84%|████████▎ | 231/276 [06:53<01:20,  1.79s/it]

====================================================================================================
[231/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCCCO
Component 2 SMILES: CO
Operating pressure: 93.330 kPa
Liquid-phase mole fraction of component 1: 0.092
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.408
Equilibrium temperature: 323.15 K

Prediction:
Vapor-phase mole fraction of component 1: 0.490
Equilibrium temperature: 324.10 K

Parsed:
Y1 : 0.408 -> 0.49
T  : 323.15 -> 324.1

 84%|████████▍ | 232/276 [06:54<01:18,  1.78s/it]

====================================================================================================
[232/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: C(=O)O
Component 2 SMILES: O
Operating pressure: 79.990 kPa
Liquid-phase mole fraction of component 1: 0.126
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.063
Equilibrium temperature: 369.15 K

Prediction:
Vapor-phase mole fraction of component 1: 0.062
Equilibrium temperature: 368.25 K

Parsed:
Y1 : 0.063 -> 0.062
T  : 369.15 -> 368.25

 84%|████████▍ | 233/276 [06:56<01:16,  1.78s/it]

====================================================================================================
[233/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: C(C(CO)O)O
Operating pressure: 61.330 kPa
Liquid-phase mole fraction of component 1: 0.545
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.992
Equilibrium temperature: 423.15 K

Prediction:
Vapor-phase mole fraction of component 1: 0.995
Equilibrium temperature: 413.15 K

Parsed:
Y1 : 0.992 -> 0.995
T  : 423.15 -> 413.15

 85%|████████▍ | 234/276 [06:58<01:14,  1.78s/it]

====================================================================================================
[234/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: C1=CC=CC=C1
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.456
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.587
Equilibrium temperature: 331.30 K

Prediction:
Vapor-phase mole fraction of component 1: 0.596
Equilibrium temperature: 331.17 K

Parsed:
Y1 : 0.587 -> 0.596
T  : 331.3 -> 331.17

 85%|████████▌ | 235/276 [07:00<01:13,  1.78s/it]

====================================================================================================
[235/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: C1CC(OC1)CO
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.900
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.970
Equilibrium temperature: 373.65 K

Prediction:
Vapor-phase mole fraction of component 1: 0.975
Equilibrium temperature: 373.35 K

Parsed:
Y1 : 0.97 -> 0.975
T  : 373.65 -> 373.35

 86%|████████▌ | 236/276 [07:02<01:11,  1.78s/it]

====================================================================================================
[236/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: COCCl
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.988
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.950
Equilibrium temperature: 372.75 K

Prediction:
Vapor-phase mole fraction of component 1: 0.979
Equilibrium temperature: 372.65 K

Parsed:
Y1 : 0.95 -> 0.979
T  : 372.75 -> 372.65

 86%|████████▌ | 237/276 [07:03<01:09,  1.78s/it]

====================================================================================================
[237/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: C1COCOC1
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.055
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.195
Equilibrium temperature: 369.73 K

Prediction:
Vapor-phase mole fraction of component 1: 0.220
Equilibrium temperature: 368.15 K

Parsed:
Y1 : 0.195 -> 0.22
T  : 369.73 -> 368.15

 86%|████████▌ | 238/276 [07:05<01:07,  1.78s/it]

====================================================================================================
[238/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: C(Cl)(Cl)(Cl)Cl
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.051
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.445
Equilibrium temperature: 332.55 K

Prediction:
Vapor-phase mole fraction of component 1: 0.390
Equilibrium temperature: 332.05 K

Parsed:
Y1 : 0.445 -> 0.39
T  : 332.55 -> 332.05

 87%|████████▋ | 239/276 [07:07<01:05,  1.78s/it]

====================================================================================================
[239/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CC(=O)O
Operating pressure: 94.130 kPa
Liquid-phase mole fraction of component 1: 0.669
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.831
Equilibrium temperature: 376.25 K

Prediction:
Vapor-phase mole fraction of component 1: 0.826
Equilibrium temperature: 377.15 K

Parsed:
Y1 : 0.831 -> 0.826
T  : 376.25 -> 377.15

 87%|████████▋ | 240/276 [07:09<01:04,  1.78s/it]

====================================================================================================
[240/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: O
Operating pressure: 333.420 kPa
Liquid-phase mole fraction of component 1: 0.024
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.198
Equilibrium temperature: 404.25 K

Prediction:
Vapor-phase mole fraction of component 1: 0.200
Equilibrium temperature: 404.75 K

Parsed:
Y1 : 0.198 -> 0.2
T  : 404.25 -> 404.75

 87%|████████▋ | 241/276 [07:10<01:02,  1.78s/it]

====================================================================================================
[241/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: CCCC(=O)O
Operating pressure: 79.990 kPa
Liquid-phase mole fraction of component 1: 0.210
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.824
Equilibrium temperature: 381.45 K

Prediction:
Vapor-phase mole fraction of component 1: 0.820
Equilibrium temperature: 380.45 K

Parsed:
Y1 : 0.824 -> 0.82
T  : 381.45 -> 380.45

 88%|████████▊ | 242/276 [07:12<01:00,  1.78s/it]

====================================================================================================
[242/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(C)O
Component 2 SMILES: O
Operating pressure: 12.670 kPa
Liquid-phase mole fraction of component 1: 0.035
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.310
Equilibrium temperature: 316.59 K

Prediction:
Vapor-phase mole fraction of component 1: 0.379
Equilibrium temperature: 316.92 K

Parsed:
Y1 : 0.31 -> 0.379
T  : 316.59 -> 316.92

 88%|████████▊ | 243/276 [07:14<00:58,  1.78s/it]

====================================================================================================
[243/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: C(C(CO)O)O
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.436
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.998
Equilibrium temperature: 404.95 K

Prediction:
Vapor-phase mole fraction of component 1: 0.980
Equilibrium temperature: 413.15 K

Parsed:
Y1 : 0.998 -> 0.98
T  : 404.95 -> 413.15

 88%|████████▊ | 244/276 [07:16<00:57,  1.78s/it]

====================================================================================================
[244/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(C)O
Component 2 SMILES: O
Operating pressure: 12.670 kPa
Liquid-phase mole fraction of component 1: 0.000
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.000
Equilibrium temperature: 323.86 K

Prediction:
Vapor-phase mole fraction of component 1: 0.000
Equilibrium temperature: 319.65 K

Parsed:
Y1 : 0.0 -> 0.0
T  : 323.86 -> 319.65

 89%|████████▉ | 245/276 [07:18<00:55,  1.80s/it]

====================================================================================================
[245/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: CC(C)(C(C)(C)O)O
Operating pressure: 14.670 kPa
Liquid-phase mole fraction of component 1: 0.720
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.951
Equilibrium temperature: 1387.15 K

Prediction:
Vapor-phase mole fraction of component 1: 0.954
Equilibrium temperature: 1375.65 K

Parsed:
Y1 : 0.951 -> 0.954
T  : 1387.15 -> 1375.65

 89%|████████▉ | 246/276 [07:19<00:53,  1.79s/it]

====================================================================================================
[246/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: C(C(CO)O)O
Operating pressure: 48.000 kPa
Liquid-phase mole fraction of component 1: 0.365
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.969
Equilibrium temperature: 443.15 K

Prediction:
Vapor-phase mole fraction of component 1: 0.950
Equilibrium temperature: 453.15 K

Parsed:
Y1 : 0.969 -> 0.95
T  : 443.15 -> 453.15

 89%|████████▉ | 247/276 [07:21<00:51,  1.79s/it]

====================================================================================================
[247/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: C(CN)N
Operating pressure: 53.330 kPa
Liquid-phase mole fraction of component 1: 0.652
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.766
Equilibrium temperature: 372.85 K

Prediction:
Vapor-phase mole fraction of component 1: 0.750
Equilibrium temperature: 372.55 K

Parsed:
Y1 : 0.766 -> 0.75
T  : 372.85 -> 372.55

 90%|████████▉ | 248/276 [07:23<00:50,  1.79s/it]

====================================================================================================
[248/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: C(=O)O
Component 2 SMILES: O
Operating pressure: 79.990 kPa
Liquid-phase mole fraction of component 1: 1.000
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 1.000
Equilibrium temperature: 366.15 K

Prediction:
Vapor-phase mole fraction of component 1: 1.000
Equilibrium temperature: 366.75 K

Parsed:
Y1 : 1.0 -> 1.0
T  : 366.15 -> 366.75

 90%|█████████ | 249/276 [07:25<00:48,  1.79s/it]

====================================================================================================
[249/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: C(CO)O
Operating pressure: 3.330 kPa
Liquid-phase mole fraction of component 1: 0.795
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.999
Equilibrium temperature: 303.55 K

Prediction:
Vapor-phase mole fraction of component 1: 0.999
Equilibrium temperature: 306.25 K

Parsed:
Y1 : 0.999 -> 0.999
T  : 303.55 -> 306.25

 91%|█████████ | 250/276 [07:27<00:46,  1.79s/it]

====================================================================================================
[250/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: C1COCOC1
Operating pressure: 53.330 kPa
Liquid-phase mole fraction of component 1: 0.936
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.927
Equilibrium temperature: 335.55 K

Prediction:
Vapor-phase mole fraction of component 1: 0.930
Equilibrium temperature: 335.65 K

Parsed:
Y1 : 0.927 -> 0.93
T  : 335.55 -> 335.65

 91%|█████████ | 251/276 [07:28<00:44,  1.79s/it]

====================================================================================================
[251/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(C=O)O
Component 2 SMILES: CO
Operating pressure: 585.660 kPa
Liquid-phase mole fraction of component 1: 0.771
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.639
Equilibrium temperature: 384.46 K

Prediction:
Vapor-phase mole fraction of component 1: 0.704
Equilibrium temperature: 383.90 K

Parsed:
Y1 : 0.639 -> 0.704
T  : 384.46 -> 383.9

 91%|█████████▏| 252/276 [07:30<00:42,  1.79s/it]

====================================================================================================
[252/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: C(CO)O
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.154
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.949
Equilibrium temperature: 403.25 K

Prediction:
Vapor-phase mole fraction of component 1: 0.802
Equilibrium temperature: 419.15 K

Parsed:
Y1 : 0.949 -> 0.802
T  : 403.25 -> 419.15

 92%|█████████▏| 253/276 [07:32<00:41,  1.79s/it]

====================================================================================================
[253/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: CCCC(=O)O
Operating pressure: 53.330 kPa
Liquid-phase mole fraction of component 1: 0.297
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.880
Equilibrium temperature: 365.15 K

Prediction:
Vapor-phase mole fraction of component 1: 0.860
Equilibrium temperature: 366.65 K

Parsed:
Y1 : 0.88 -> 0.86
T  : 365.15 -> 366.65

 92%|█████████▏| 254/276 [07:34<00:39,  1.79s/it]

====================================================================================================
[254/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(=O)C
Component 2 SMILES: CO
Operating pressure: 100.260 kPa
Liquid-phase mole fraction of component 1: 0.398
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.526
Equilibrium temperature: 329.93 K

Prediction:
Vapor-phase mole fraction of component 1: 0.504
Equilibrium temperature: 330.97 K

Parsed:
Y1 : 0.526 -> 0.504
T  : 329.93 -> 330.97

 92%|█████████▏| 255/276 [07:35<00:37,  1.79s/it]

====================================================================================================
[255/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: C(CN)N
Operating pressure: 13.330 kPa
Liquid-phase mole fraction of component 1: 0.229
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.138
Equilibrium temperature: 340.04 K

Prediction:
Vapor-phase mole fraction of component 1: 0.150
Equilibrium temperature: 341.55 K

Parsed:
Y1 : 0.138 -> 0.15
T  : 340.04 -> 341.55

 93%|█████████▎| 256/276 [07:37<00:35,  1.78s/it]

====================================================================================================
[256/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: C1=CC=CC=C1
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.003
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.081
Equilibrium temperature: 350.43 K

Prediction:
Vapor-phase mole fraction of component 1: 0.060
Equilibrium temperature: 350.20 K

Parsed:
Y1 : 0.081 -> 0.06
T  : 350.43 -> 350.2

 93%|█████████▎| 257/276 [07:39<00:33,  1.78s/it]

====================================================================================================
[257/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: C1=CC=C(C=C1)O
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.974
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.978
Equilibrium temperature: 372.95 K

Prediction:
Vapor-phase mole fraction of component 1: 0.980
Equilibrium temperature: 373.05 K

Parsed:
Y1 : 0.978 -> 0.98
T  : 372.95 -> 373.05

 93%|█████████▎| 258/276 [07:41<00:32,  1.78s/it]

====================================================================================================
[258/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: CCC(C)C=O
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.117
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.492
Equilibrium temperature: 356.75 K

Prediction:
Vapor-phase mole fraction of component 1: 0.520
Equilibrium temperature: 358.15 K

Parsed:
Y1 : 0.492 -> 0.52
T  : 356.75 -> 358.15

 94%|█████████▍| 259/276 [07:43<00:30,  1.78s/it]

====================================================================================================
[259/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(=O)C
Component 2 SMILES: CO
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.600
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.655
Equilibrium temperature: 328.95 K

Prediction:
Vapor-phase mole fraction of component 1: 0.667
Equilibrium temperature: 329.15 K

Parsed:
Y1 : 0.655 -> 0.667
T  : 328.95 -> 329.15

 94%|█████████▍| 260/276 [07:44<00:28,  1.78s/it]

====================================================================================================
[260/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: C(C(CO)O)O
Operating pressure: 1.330 kPa
Liquid-phase mole fraction of component 1: 0.100
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.978
Equilibrium temperature: 377.25 K

Prediction:
Vapor-phase mole fraction of component 1: 0.997
Equilibrium temperature: 353.15 K

Parsed:
Y1 : 0.978 -> 0.997
T  : 377.25 -> 353.15

 95%|█████████▍| 261/276 [07:46<00:26,  1.78s/it]

====================================================================================================
[261/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: C(=O)O
Component 2 SMILES: O
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.393
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.320
Equilibrium temperature: 379.95 K

Prediction:
Vapor-phase mole fraction of component 1: 0.316
Equilibrium temperature: 378.15 K

Parsed:
Y1 : 0.32 -> 0.316
T  : 379.95 -> 378.15

 95%|█████████▍| 262/276 [07:48<00:24,  1.78s/it]

====================================================================================================
[262/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: CCCC(=O)O
Operating pressure: 79.990 kPa
Liquid-phase mole fraction of component 1: 0.894
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.953
Equilibrium temperature: 366.35 K

Prediction:
Vapor-phase mole fraction of component 1: 0.952
Equilibrium temperature: 366.65 K

Parsed:
Y1 : 0.953 -> 0.952
T  : 366.35 -> 366.65

 95%|█████████▌| 263/276 [07:50<00:23,  1.78s/it]

====================================================================================================
[263/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: C1=CC=CC=C1
Operating pressure: 69.490 kPa
Liquid-phase mole fraction of component 1: 0.868
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.724
Equilibrium temperature: 322.77 K

Prediction:
Vapor-phase mole fraction of component 1: 0.702
Equilibrium temperature: 323.05 K

Parsed:
Y1 : 0.724 -> 0.702
T  : 322.77 -> 323.05

 96%|█████████▌| 264/276 [07:52<00:21,  1.78s/it]

====================================================================================================
[264/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: CS(=O)C
Operating pressure: 73.330 kPa
Liquid-phase mole fraction of component 1: 0.744
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.989
Equilibrium temperature: 375.25 K

Prediction:
Vapor-phase mole fraction of component 1: 0.990
Equilibrium temperature: 374.05 K

Parsed:
Y1 : 0.989 -> 0.99
T  : 375.25 -> 374.05

 96%|█████████▌| 265/276 [07:53<00:19,  1.78s/it]

====================================================================================================
[265/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: C1COCCN1
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.551
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.751
Equilibrium temperature: 366.25 K

Prediction:
Vapor-phase mole fraction of component 1: 0.748
Equilibrium temperature: 366.75 K

Parsed:
Y1 : 0.751 -> 0.748
T  : 366.25 -> 366.75

 96%|█████████▋| 266/276 [07:55<00:17,  1.78s/it]

====================================================================================================
[266/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(C=O)O
Component 2 SMILES: CO
Operating pressure: 53.330 kPa
Liquid-phase mole fraction of component 1: 0.393
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.557
Equilibrium temperature: 311.55 K

Prediction:
Vapor-phase mole fraction of component 1: 0.546
Equilibrium temperature: 311.48 K

Parsed:
Y1 : 0.557 -> 0.546
T  : 311.55 -> 311.48

 97%|█████████▋| 267/276 [07:57<00:16,  1.79s/it]

====================================================================================================
[267/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(=O)O
Component 2 SMILES: O
Operating pressure: 101.320 kPa
Liquid-phase mole fraction of component 1: 0.190
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.133
Equilibrium temperature: 374.45 K

Prediction:
Vapor-phase mole fraction of component 1: 0.130
Equilibrium temperature: 374.15 K

Parsed:
Y1 : 0.133 -> 0.13
T  : 374.45 -> 374.15

 97%|█████████▋| 268/276 [07:59<00:14,  1.79s/it]

====================================================================================================
[268/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: CCC(=O)O
Operating pressure: 13.330 kPa
Liquid-phase mole fraction of component 1: 0.494
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.826
Equilibrium temperature: 327.75 K

Prediction:
Vapor-phase mole fraction of component 1: 0.860
Equilibrium temperature: 327.45 K

Parsed:
Y1 : 0.826 -> 0.86
T  : 327.75 -> 327.45

 97%|█████████▋| 269/276 [08:00<00:12,  1.79s/it]

====================================================================================================
[269/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: CCC(=O)O
Operating pressure: 53.330 kPa
Liquid-phase mole fraction of component 1: 0.470
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.794
Equilibrium temperature: 360.55 K

Prediction:
Vapor-phase mole fraction of component 1: 0.770
Equilibrium temperature: 360.35 K

Parsed:
Y1 : 0.794 -> 0.77
T  : 360.55 -> 360.35

 98%|█████████▊| 270/276 [08:02<00:10,  1.78s/it]

====================================================================================================
[270/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: C1COCCO1
Operating pressure: 6.670 kPa
Liquid-phase mole fraction of component 1: 0.173
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.311
Equilibrium temperature: 300.55 K

Prediction:
Vapor-phase mole fraction of component 1: 0.296
Equilibrium temperature: 300.05 K

Parsed:
Y1 : 0.311 -> 0.296
T  : 300.55 -> 300.05

 98%|█████████▊| 271/276 [08:04<00:08,  1.78s/it]

====================================================================================================
[271/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: C(C(CO)O)O
Operating pressure: 3.330 kPa
Liquid-phase mole fraction of component 1: 0.502
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 1.000
Equilibrium temperature: 318.55 K

Prediction:
Vapor-phase mole fraction of component 1: 0.999
Equilibrium temperature: 320.15 K

Parsed:
Y1 : 1.0 -> 0.999
T  : 318.55 -> 320.15

 99%|█████████▊| 272/276 [08:06<00:07,  1.78s/it]

====================================================================================================
[272/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(C=O)O
Component 2 SMILES: CO
Operating pressure: 26.660 kPa
Liquid-phase mole fraction of component 1: 0.737
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.737
Equilibrium temperature: 294.65 K

Prediction:
Vapor-phase mole fraction of component 1: 0.724
Equilibrium temperature: 295.25 K

Parsed:
Y1 : 0.737 -> 0.724
T  : 294.65 -> 295.25

 99%|█████████▉| 273/276 [08:08<00:05,  1.78s/it]

====================================================================================================
[273/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CC(=O)O
Component 2 SMILES: O
Operating pressure: 13.330 kPa
Liquid-phase mole fraction of component 1: 0.007
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.005
Equilibrium temperature: 322.45 K

Prediction:
Vapor-phase mole fraction of component 1: 0.004
Equilibrium temperature: 323.15 K

Parsed:
Y1 : 0.005 -> 0.004
T  : 322.45 -> 323.15

 99%|█████████▉| 274/276 [08:09<00:03,  1.78s/it]

====================================================================================================
[274/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: O
Component 2 SMILES: C(CN)N
Operating pressure: 13.330 kPa
Liquid-phase mole fraction of component 1: 0.834
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.985
Equilibrium temperature: 332.19 K

Prediction:
Vapor-phase mole fraction of component 1: 0.986
Equilibrium temperature: 330.95 K

Parsed:
Y1 : 0.985 -> 0.986
T  : 332.19 -> 330.95

100%|█████████▉| 275/276 [08:11<00:01,  1.78s/it]

====================================================================================================
[275/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: CCCC=O
Operating pressure: 98.660 kPa
Liquid-phase mole fraction of component 1: 0.654
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.595
Equilibrium temperature: 332.55 K

Prediction:
Vapor-phase mole fraction of component 1: 0.602
Equilibrium temperature: 333.15 K

Parsed:
Y1 : 0.595 -> 0.602
T  : 332.55 -> 333.15

100%|██████████| 276/276 [08:13<00:00,  1.79s/it]

====================================================================================================
[276/276]
Task : isobaric

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isobaric conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: C1=CC=CC=C1
Operating pressure: 45.330 kPa
Liquid-phase mole fraction of component 1: 0.589
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium temperature


Ground Truth:
Vapor-phase mole fraction of component 1: 0.582
Equilibrium temperature: 311.28 K

Prediction:
Vapor-phase mole fraction of component 1: 0.589
Equilibrium temperature: 311.59 K

Parsed:
Y1 : 0.582 -> 0.589
T  : 311.28 -> 311.59

Results saved to ./随机划分/结果文件/test_data_72.json

============================================================
Overall Y1
Samples : 276
MAE  : 0.014928
RMSE : 0.026638
R²   : 0.992467

============================================================
Isobaric Y1
Samples : 276
MAE  : 0.014928
RMSE : 0.026638
R²   : 0.992467

============================================================
Isobaric Temperature
Samples : 276
MAE  : 1.768514
RMSE : 4.529008
R²   : 0.996392

Isothermal Y1: No valid samples

Isothermal Pressure: No valid samples

In [11]:
import pandas as pd
import re
import numpy as np
# =========================
# 1. 转成DataFrame
# =========================
df = pd.DataFrame(results_all)
# =========================
# 2. 从input提取信息
# =========================
def extract_info(input_text):
    input_text = str(input_text)
    smiles1 = None
    smiles2 = None
    x1 = None
    pressure = None
    temperature = None
    # Component 1
    m = re.search(
        r"Component 1 SMILES:\s*(.+)",
        input_text,
        re.IGNORECASE
    )
    if m:
        smiles1 = m.group(1).split("\n")[0].strip()
    # Component 2
    m = re.search(
        r"Component 2 SMILES:\s*(.+)",
        input_text,
        re.IGNORECASE
    )
    if m:
        smiles2 = m.group(1).split("\n")[0].strip()
    # Liquid composition
    m = re.search(
        r"Liquid-phase mole fraction of component 1:\s*([-+]?\d*\.?\d+)",
        input_text,
        re.IGNORECASE
    )
    if m:
        x1 = float(m.group(1))
    # Pressure
    m = re.search(
        r"Operating pressure:\s*([-+]?\d*\.?\d+)",
        input_text,
        re.IGNORECASE
    )
    if m:
        pressure = float(m.group(1))
    # Temperature
    m = re.search(
        r"Operating temperature:\s*([-+]?\d*\.?\d+)",
        input_text,
        re.IGNORECASE
    )
    if m:
        temperature = float(m.group(1))
    return pd.Series(
        [
            smiles1,
            smiles2,
            x1,
            pressure,
            temperature
        ],
        index=[
            "SMILES_1",
            "SMILES_2",
            "X1",
            "Input_P(kPa)",
            "Input_T(K)"
        ]
    )
# 提取信息
df[
    [
        "SMILES_1",
        "SMILES_2",
        "X1",
        "Input_P(kPa)",
        "Input_T(K)"
    ]
] = df["input"].apply(extract_info)
# =========================
# 3. 调整列顺序
# =========================
df_save = pd.DataFrame()
df_save["Task"] = df["task_type"]
df_save["SMILES_1"] = df["SMILES_1"]
df_save["SMILES_2"] = df["SMILES_2"]
df_save["Input_X1"] = df["X1"]
#df_save["Input_P(kPa)"] = df["Input_P(kPa)"]
#df_save["Input_T(K)"] = df["Input_T(K)"]
df_save["True_Y1"] = df["true_Y1"]
df_save["Pred_Y1"] = df["pred_Y1"]
df_save["Error_Y1"] = df["err_Y1"]
df_save["True_T(K)"] = df["true_T"]
df_save["Pred_T(K)"] = df["pred_T"]
df_save["Error_T(K)"] = df["err_T"]
#df_save["True_P(kPa)"] = df["true_P"]
#df_save["Pred_P(kPa)"] = df["pred_P"]
#df_save["Error_P(kPa)"] = df["err_P"]
df_save["Raw Prediction"] = df["raw_prediction"]
# ========================
# 4. 保存Excel
# =========================
save_path = "./随机划分/结果文件/excel结果文件/test_data_72.xlsx"
df_save.to_excel(
    save_path,
    index=False
)
print(f"保存成功：{save_path}")
df_save

保存成功：./随机划分/结果文件/excel结果文件/test_data_72.xlsx

,Task,SMILES_1,SMILES_2,Input_X1,True_Y1,Pred_Y1,Error_Y1,True_T(K),Pred_T(K),Error_T(K),Raw Prediction
0,isobaric,O,CC(=O)O,0.476,0.586,0.580,0.006,333.08,334.99,1.91,Vapor-phase mole fraction of component 1: 0.58...
1,isobaric,CC(C)O,O,0.084,0.484,0.469,0.015,325.14,324.99,0.15,Vapor-phase mole fraction of component 1: 0.46...
2,isobaric,CO,CCCC=O,0.713,0.751,0.650,0.101,336.75,334.15,2.60,Vapor-phase mole fraction of component 1: 0.65...
3,isobaric,CC(C=O)O,CO,0.849,0.788,0.774,0.014,327.65,328.55,0.90,Vapor-phase mole fraction of component 1: 0.77...
4,isobaric,O,C(C(CO)O)O,0.420,0.982,0.985,0.003,433.15,433.15,0.00,Vapor-phase mole fraction of component 1: 0.98...
...,...,...,...,...,...,...,...,...,...,...,...
271,isobaric,CC(C=O)O,CO,0.737,0.737,0.724,0.013,294.65,295.25,0.60,Vapor-phase mole fraction of component 1: 0.72...
272,isobaric,CC(=O)O,O,0.007,0.005,0.004,0.001,322.45,323.15,0.70,Vapor-phase mole fraction of component 1: 0.00...
273,isobaric,O,C(CN)N,0.834,0.985,0.986,0.001,332.19,330.95,1.24,Vapor-phase mole fraction of component 1: 0.98...
274,isobaric,CO,CCCC=O,0.654,0.595,0.602,0.007,332.55,333.15,0.60,Vapor-phase mole fraction of component 1: 0.60...
275,isobaric,CO,C1=CC=CC=C1,0.589,0.582,0.589,0.007,311.28,311.59,0.31,Vapor-phase mole fraction of component 1: 0.58...

In [ ]:
import pandas as pd
import re
import numpy as np

# =========================
# 1. 转成DataFrame
# =========================
df = pd.DataFrame(results_all)

# =========================
# 2. 从input提取信息
# =========================
def extract_info(input_text):
    input_text = str(input_text)
    smiles1 = None
    smiles2 = None
    x1 = None
    pressure = None
    temperature = None
    m = re.search(
        r"Component 1 SMILES:(.+)",
        input_text,
        re.IGNORECASE
    )
    if m:
        smiles1 = m.group(1).split("\n")[0].strip()
    m = re.search(
        r"Component 2 SMILES:(.+)",
        input_text,
        re.IGNORECASE
    )
    if m:
        smiles2 = m.group(1).split("\n")[0].strip()
    m = re.search(
        r"Liquid-phase mole fraction of component 1:([-+]?\d*\.?\d+)",
        input_text,
        re.IGNORECASE
    )
    if m:
        x1 = float(m.group(1))
    m = re.search(
        r"Operating pressure:([-+]?\d*\.?\d+)",
        input_text,
        re.IGNORECASE
    )
    if m:
        pressure = float(m.group(1))
    m = re.search(
        r"Operating temperature:([-+]?\d*\.?\d+)",
        input_text,
        re.IGNORECASE
    )
    if m:
        temperature = float(m.group(1))

    return pd.Series(
        [
            smiles1,
            smiles2,
            x1,
            pressure,
            temperature
        ]
    )

df[
    [
        "SMILES_1",
        "SMILES_2",
        "X1",
        "Input_P(kPa)",
        "Input_T(K)"
    ]
] = df["input"].apply(extract_info)
# =========================
# 3. 调整列顺序
# =========================
df_save = pd.DataFrame()
df_save["Task"] = df["task_type"]
df_save["SMILES_1"] = df["SMILES_1"]
df_save["SMILES_2"] = df["SMILES_2"]
df_save["Input_X1"] = df["X1"]
#df_save["Input_P(kPa)"] = df["Input_P(kPa)"]
#df_save["Input_T(K)"] = df["Input_T(K)"]
df_save["True_Y1"] = df["true_Y1"]
df_save["Pred_Y1"] = df["pred_Y1"]
df_save["Error_Y1"] = df["err_Y1"]
df_save["True_T(K)"] = df["true_T"]
df_save["Pred_T(K)"] = df["pred_T"]
df_save["Error_T(K)"] = df["err_T"]
#df_save["True_P(kPa)"] = df["true_P"]
#df_save["Pred_P(kPa)"] = df["pred_P"]
#df_save["Error_P(kPa)"] = df["err_P"]
#df_save["Raw Prediction"] = df["raw_prediction"]
# =========================
# 4. 保存Excel
# =========================
save_path = "./按体系划分/结果文件/excel结果文件/test_data_42_fine.xlsx"

df_save.to_excel(
    save_path,
    index=False
)
print(f"保存成功：{save_path}")
# 查看前几行
df_save

In [ ]:
test_file_path = "./随机划分/训练文件/train_data_42.jsonl"
save_path = "./随机划分/结果文件/train_result_72.json"
results_all = batch_predict_mixed_vle(
    test_file_path=test_file_path,
    save_path=save_path,
    max_samples= None
)

In [ ]:
import pandas as pd
import re
import numpy as np

# =========================
# 1. 转成DataFrame
# =========================
df = pd.DataFrame(results_all)

# =========================
# 2. 从input提取信息
# =========================
def extract_info(input_text):
    input_text = str(input_text)
    smiles1 = None
    smiles2 = None
    x1 = None
    pressure = None
    temperature = None
    m = re.search(
        r"Component 1 SMILES:(.+)",
        input_text,
        re.IGNORECASE
    )
    if m:
        smiles1 = m.group(1).split("\n")[0].strip()
    m = re.search(
        r"Component 2 SMILES:(.+)",
        input_text,
        re.IGNORECASE
    )
    if m:
        smiles2 = m.group(1).split("\n")[0].strip()
    m = re.search(
        r"Liquid-phase mole fraction of component 1:([-+]?\d*\.?\d+)",
        input_text,
        re.IGNORECASE
    )
    if m:
        x1 = float(m.group(1))
    m = re.search(
        r"Operating pressure:([-+]?\d*\.?\d+)",
        input_text,
        re.IGNORECASE
    )
    if m:
        pressure = float(m.group(1))
    m = re.search(
        r"Operating temperature:([-+]?\d*\.?\d+)",
        input_text,
        re.IGNORECASE
    )
    if m:
        temperature = float(m.group(1))

    return pd.Series(
        [
            smiles1,
            smiles2,
            x1,
            pressure,
            temperature
        ]
    )

df[
    [
        "SMILES_1",
        "SMILES_2",
        "X1",
        "Input_P(kPa)",
        "Input_T(K)"
    ]
] = df["input"].apply(extract_info)
# =========================
# 3. 调整列顺序
# =========================
df_save = pd.DataFrame()
df_save["Task"] = df["task_type"]
df_save["SMILES_1"] = df["SMILES_1"]
df_save["SMILES_2"] = df["SMILES_2"]
df_save["Input_X1"] = df["X1"]
df_save["Input_P(kPa)"] = df["Input_P(kPa)"]
df_save["Input_T(K)"] = df["Input_T(K)"]
df_save["True_Y1"] = df["true_Y1"]
df_save["Pred_Y1"] = df["pred_Y1"]
df_save["Error_Y1"] = df["err_Y1"]
df_save["True_T(K)"] = df["true_T"]
df_save["Pred_T(K)"] = df["pred_T"]
df_save["Error_T(K)"] = df["err_T"]
df_save["True_P(kPa)"] = df["true_P"]
df_save["Pred_P(kPa)"] = df["pred_P"]
df_save["Error_P(kPa)"] = df["err_P"]
df_save["Raw Prediction"] = df["raw_prediction"]
# =========================
# 4. 保存Excel
# =========================
save_path = "./随机划分/结果文件/excel结果文件/train_result_72.xlsx"

df_save.to_excel(
    save_path,
    index=False
)
print(f"保存成功：{save_path}")
# 查看前几行
df_save