In [1]:
import os
import json
import re
import numpy as np
import pandas as pd
import torch
from tqdm import tqdm
from datasets import Dataset
from peft import LoraConfig, TaskType, get_peft_model
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    TrainingArguments,
    Trainer,
    DataCollatorForSeq2Seq
)

In [2]:
# ====================
# 0. 基础配置
# ====================
model_name = "./model/Mistral-7B/mistralai/Mistral-7B-Instruct-v0___3/"
output_dir = "./output/VLE_LLM/等温/体系划分/1/42"

In [3]:
# ====================
# 1. 加载 tokenizer 和模型
# ====================
device = "cuda" if torch.cuda.is_available() else "cpu"
dtype = torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float16
tokenizer = AutoTokenizer.from_pretrained(model_name)
# Mistral 特殊设置：确保 pad_token 存在且方向正确
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right" 

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    dtype=dtype,
    device_map="auto"
)
model.config.use_cache = False
model.enable_input_require_grads()

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

The module name  (originally ) is not a valid Python identifier. Please rename the original module to avoid import issues.

In [4]:
MAX_LENGTH = 1024
SYSTEM_PROMPT = """You are an expert in thermodynamics and vapor-liquid equilibrium.
Your task is to predict equilibrium properties of binary mixtures from molecular structures and operating conditions.
Return only the requested numerical results.
"""
def build_messages(user_input, assistant_output=None):
    # 将System Prompt直接拼接到User内容
    user_content = SYSTEM_PROMPT.strip() + "\n\n" + user_input.strip()
    messages = [
        {
            "role": "user",
            "content": user_content
        }
    ]
    if assistant_output is not None:
        messages.append(
            {
                "role": "assistant",
                "content": assistant_output
            }
        )
    return messages
def process_func(example):
    # 完整聊天
    messages = build_messages(
        example["input"],
        example["output"]
    )
    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=False
    )
    enc = tokenizer(
        text,
        truncation=True,
        max_length=MAX_LENGTH,
        add_special_tokens=False,
    )
    input_ids = enc["input_ids"]
    attention_mask = enc["attention_mask"]
    labels = input_ids.copy()
    # prompt（只有User）
    prompt_messages = build_messages(
        example["input"],
        None
    )
    prompt_text = tokenizer.apply_chat_template(
        prompt_messages,
        tokenize=False,
        add_generation_prompt=False
    )
    prompt_ids = tokenizer(
        prompt_text,
        truncation=True,
        max_length=MAX_LENGTH,
        add_special_tokens=False
    )["input_ids"]
    prompt_len = len(prompt_ids)
    # Mask User部分
    labels[:prompt_len] = [-100] * prompt_len
    return {
        "input_ids": input_ids,
        "attention_mask": attention_mask,
        "labels": labels,
    }

In [5]:
# ====================
# 3. 数据处理
# ====================
train_df = pd.read_json("./等温数据/data/训练_isothermal_62.jsonl", lines=True)
train_ds = Dataset.from_pandas(train_df)
train_dataset = train_ds.map(process_func, remove_columns=train_ds.column_names)

Map:   0%|          | 0/3200 [00:00<?, ? examples/s]

In [6]:
# ====================
# 4. LoRA 配置
# ====================
config = LoraConfig(
    task_type=TaskType.CAUSAL_LM,
    target_modules=[
        "q_proj", "k_proj", "v_proj", "o_proj", 
        "gate_proj", "up_proj", "down_proj"
    ],
    inference_mode=False,
    r=64,
    lora_alpha=128,
    lora_dropout=0.05,
    bias="none"
)
model = get_peft_model(model, config)
model.print_trainable_parameters()

trainable params: 167,772,160 || all params: 7,415,795,712 || trainable%: 2.2624

In [7]:
# ====================
# 5. 训练参数
# ====================
args = TrainingArguments(
    output_dir=output_dir,
    per_device_train_batch_size=4,
    gradient_accumulation_steps=8,
    
    num_train_epochs=5,
    
    learning_rate=8e-6,
    weight_decay=0.03,
    
    lr_scheduler_type="cosine",
    warmup_steps=0,
    
    logging_steps=50,
    save_steps=100,
    #eval_steps=100,
    #eval_strategy="steps",
    save_total_limit=2,
    
    #load_best_model_at_end=True,
    #metric_for_best_model="eval_loss",
    bf16=True,
    gradient_checkpointing=True,
    report_to="none",
    optim="adamw_torch"
)

In [8]:
# ====================
# 6. Trainer 执行
# ====================
trainer = Trainer(
    model=model,
    args=args,
    train_dataset=train_dataset,
    #eval_dataset=eval_dataset,
    data_collator=DataCollatorForSeq2Seq(tokenizer=tokenizer, padding=True),
)
trainer.train()

The model is already on multiple devices. Skipping the move to device specified in `args`.

TrainOutput(global_step=500, training_loss=0.3974169387817383, metrics={'train_runtime': 1363.956, 'train_samples_per_second': 11.731, 'train_steps_per_second': 0.367, 'total_flos': 1.371532980437975e+17, 'train_loss': 0.3974169387817383, 'epoch': 5.0})

In [9]:
def get_task_type(input_text):
    """
    根据input自动判断任务类型
    """
    text = input_text.lower()
    if "isobaric" in text:
        return "isobaric"
    elif "isothermal" in text:
        return "isothermal"
    else:
        raise ValueError("Cannot determine task type.")
def predict(example, model, tokenizer):
    model.eval()
    messages = build_messages(
        user_input=example["input"],
        assistant_output=None
    )
    inputs = tokenizer.apply_chat_template(
        messages,
        add_generation_prompt=True,
        tokenize=True,
        return_tensors="pt",
        return_dict=True
    ).to(device)
    input_length = inputs["input_ids"].shape[1]
    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=64,
            do_sample=False,
            pad_token_id=tokenizer.pad_token_id,
            eos_token_id=tokenizer.eos_token_id
        )
    response = tokenizer.decode(
        outputs[0][input_length:],
        skip_special_tokens=True
    ).strip()
    return response
def parse_vle_output(text, task_type):
    text = str(text)
    y1 = None
    T = None
    P = None
    m = re.search(
        r"Vapor-phase mole fraction of component 1\s*:\s*([-+]?\d*\.?\d+)",
        text,
        re.I
    )
    if m:
        y1 = float(m.group(1))
    if task_type == "isobaric":
        m = re.search(
            r"Equilibrium temperature\s*:\s*([-+]?\d*\.?\d+)",
            text,
            re.I
        )
        if m:
            T = float(m.group(1))
    else:
        m = re.search(
            r"Equilibrium pressure\s*:\s*([-+]?\d*\.?\d+)",
            text,
            re.I
        )
        if m:
            P = float(m.group(1))
    return y1, T, P
def batch_predict_mixed_vle(
    test_file_path,
    save_path,
    max_samples=None
):
    results = []
    # Overall
    true_y1_all = []
    pred_y1_all = []
    # Isobaric
    true_y1_isoB = []
    pred_y1_isoB = []
    true_T_isoB = []
    pred_T_isoB = []
    # Isothermal
    true_y1_isoT = []
    pred_y1_isoT = []
    true_P_isoT = []
    pred_P_isoT = []
    with open(test_file_path, "r", encoding="utf-8") as f:
        lines = [line for line in f if line.strip()]
    if max_samples is not None:
        lines = lines[:max_samples]
    print(f"🚀 Total samples: {len(lines)}")
    model.eval()
    for i, line in enumerate(tqdm(lines)):
        try:
            data = json.loads(line)
            # 自动判断任务
            task_type = get_task_type(data["input"])
            # 模型预测
            raw_pred = predict(
                data,
                model,
                tokenizer
            )
            # 解析预测
            pred_y1, pred_T, pred_P = parse_vle_output(
                raw_pred,
                task_type
            )
            # 解析真实值
            true_y1, true_T, true_P = parse_vle_output(
                data["output"],
                task_type
            )
            #############################
            # 误差
            #############################
            err_y1 = None
            err_T = None
            err_P = None
            if pred_y1 is not None and true_y1 is not None:
                err_y1 = abs(pred_y1 - true_y1)
                true_y1_all.append(true_y1)
                pred_y1_all.append(pred_y1)
                if task_type == "isobaric":
                    true_y1_isoB.append(true_y1)
                    pred_y1_isoB.append(pred_y1)
                else:
                    true_y1_isoT.append(true_y1)
                    pred_y1_isoT.append(pred_y1)
            if task_type == "isobaric":
                if pred_T is not None and true_T is not None:
                    err_T = abs(pred_T - true_T)
                    true_T_isoB.append(true_T)
                    pred_T_isoB.append(pred_T)
            else:
                if pred_P is not None and true_P is not None:
                    err_P = abs(pred_P - true_P)
                    true_P_isoT.append(true_P)
                    pred_P_isoT.append(pred_P)

            #############################
            # 保存结果
            #############################
            result = {
                "task_type": task_type,
                "input": data["input"],
                "true_output": data["output"],
                "raw_prediction": raw_pred,
                "true_Y1": true_y1,
                "pred_Y1": pred_y1,
                "err_Y1": err_y1,
                "true_T": true_T,
                "pred_T": pred_T,
                "err_T": err_T,
                "true_P": true_P,
                "pred_P": pred_P,
                "err_P": err_P

            }
            results.append(result)
            #########################################
            print("\n" + "=" * 100)
            print(f"[{i+1}/{len(lines)}]")
            print("Task :", task_type)
            print("\nInput:")
            print(data["input"])
            print("\nGround Truth:")
            print(data["output"])
            print("\nPrediction:")
            print(raw_pred)
            print("\nParsed:")
            print(
                f"Y1 : {true_y1} -> {pred_y1}"
            )
            if task_type == "isobaric":
                print(
                    f"T  : {true_T} -> {pred_T}"
                )
            else:
                print(
                    f"P  : {true_P} -> {pred_P}"
                )
        except Exception as e:
            print(f"Sample {i+1} failed: {e}")
    #########################################
    # 保存json
    #########################################
    with open(save_path, "w", encoding="utf-8") as f:
        json.dump(
            results,
            f,
            indent=2,
            ensure_ascii=False
        )
    print(f"\nResults saved to {save_path}")
    #########################################
    # Metrics
    #########################################
    def print_metrics(name, y_true, y_pred):
        if len(y_true) == 0:
            print(f"\n{name}: No valid samples")
            return
        y_true = np.array(y_true)
        y_pred = np.array(y_pred)
        mae = np.mean(np.abs(y_true - y_pred))
        rmse = np.sqrt(np.mean((y_true - y_pred) ** 2))
        r2 = r2_score(y_true, y_pred)
        print("\n" + "=" * 60)
        print(name)
        print(f"Samples : {len(y_true)}")
        print(f"MAE  : {mae:.6f}")
        print(f"RMSE : {rmse:.6f}")
        print(f"R²   : {r2:.6f}")
    print_metrics(
        "Overall Y1",
        true_y1_all,
        pred_y1_all
    )
    print_metrics(
        "Isobaric Y1",
        true_y1_isoB,
        pred_y1_isoB
    )
    print_metrics(
        "Isobaric Temperature",
        true_T_isoB,
        pred_T_isoB
    )
    print_metrics(
        "Isothermal Y1",
        true_y1_isoT,
        pred_y1_isoT
    )
    print_metrics(
        "Isothermal Pressure",
        true_P_isoT,
        pred_P_isoT
    )
    return results
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

In [10]:
test_file_path = "./等温数据/data/test_isothermal_62.jsonl"
save_path = "./等温数据/data/训练后数据/test_isothermal_62.json"
results_all = batch_predict_mixed_vle(
    test_file_path=test_file_path,
    save_path=save_path,
    max_samples= None
)

🚀 Total samples: 375

  0%|          | 1/375 [00:02<12:44,  2.04s/it]

====================================================================================================
[1/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: CCC(CC)O
Operating temperature: 358.15 K
Liquid-phase mole fraction of component 1: 0.000
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.000
Equilibrium pressure: 31.310 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.000
Equilibrium pressure: 27.390 kPa

Parsed:
Y1 : 0.0 -> 0.0
P  : 31.31 -> 27.39

  1%|          | 2/375 [00:04<12:23,  1.99s/it]

====================================================================================================
[2/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: CCC(CC)O
Operating temperature: 358.15 K
Liquid-phase mole fraction of component 1: 0.011
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.060
Equilibrium pressure: 33.030 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.053
Equilibrium pressure: 38.090 kPa

Parsed:
Y1 : 0.06 -> 0.053
P  : 33.03 -> 38.09

  1%|          | 3/375 [00:05<12:17,  1.98s/it]

====================================================================================================
[3/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: CCC(CC)O
Operating temperature: 358.15 K
Liquid-phase mole fraction of component 1: 0.026
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.135
Equilibrium pressure: 35.430 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.122
Equilibrium pressure: 35.130 kPa

Parsed:
Y1 : 0.135 -> 0.122
P  : 35.43 -> 35.13

  1%|          | 4/375 [00:07<12:13,  1.98s/it]

====================================================================================================
[4/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: CCC(CC)O
Operating temperature: 358.15 K
Liquid-phase mole fraction of component 1: 0.058
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.249
Equilibrium pressure: 39.730 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.239
Equilibrium pressure: 39.100 kPa

Parsed:
Y1 : 0.249 -> 0.239
P  : 39.73 -> 39.1

  1%|▏         | 5/375 [00:09<12:11,  1.98s/it]

====================================================================================================
[5/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: CCC(CC)O
Operating temperature: 358.15 K
Liquid-phase mole fraction of component 1: 0.158
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.449
Equilibrium pressure: 50.090 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.450
Equilibrium pressure: 53.100 kPa

Parsed:
Y1 : 0.449 -> 0.45
P  : 50.09 -> 53.1

  2%|▏         | 6/375 [00:11<12:09,  1.98s/it]

====================================================================================================
[6/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: CCC(CC)O
Operating temperature: 358.15 K
Liquid-phase mole fraction of component 1: 0.212
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.516
Equilibrium pressure: 54.580 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.493
Equilibrium pressure: 58.100 kPa

Parsed:
Y1 : 0.516 -> 0.493
P  : 54.58 -> 58.1

  2%|▏         | 7/375 [00:13<12:06,  1.97s/it]

====================================================================================================
[7/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: CCC(CC)O
Operating temperature: 358.15 K
Liquid-phase mole fraction of component 1: 0.254
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.555
Equilibrium pressure: 57.470 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.549
Equilibrium pressure: 61.900 kPa

Parsed:
Y1 : 0.555 -> 0.549
P  : 57.47 -> 61.9

  2%|▏         | 8/375 [00:15<12:04,  1.97s/it]

====================================================================================================
[8/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: CCC(CC)O
Operating temperature: 358.15 K
Liquid-phase mole fraction of component 1: 0.340
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.613
Equilibrium pressure: 61.820 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.593
Equilibrium pressure: 63.090 kPa

Parsed:
Y1 : 0.613 -> 0.593
P  : 61.82 -> 63.09

  2%|▏         | 9/375 [00:17<12:01,  1.97s/it]

====================================================================================================
[9/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: CCC(CC)O
Operating temperature: 358.15 K
Liquid-phase mole fraction of component 1: 0.409
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.652
Equilibrium pressure: 64.990 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.632
Equilibrium pressure: 65.060 kPa

Parsed:
Y1 : 0.652 -> 0.632
P  : 64.99 -> 65.06

  3%|▎         | 10/375 [00:19<11:57,  1.97s/it]

====================================================================================================
[10/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: CCC(CC)O
Operating temperature: 358.15 K
Liquid-phase mole fraction of component 1: 0.507
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.694
Equilibrium pressure: 67.820 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.682
Equilibrium pressure: 68.000 kPa

Parsed:
Y1 : 0.694 -> 0.682
P  : 67.82 -> 68.0

  3%|▎         | 11/375 [00:21<11:56,  1.97s/it]

====================================================================================================
[11/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: CCC(CC)O
Operating temperature: 358.15 K
Liquid-phase mole fraction of component 1: 0.637
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.743
Equilibrium pressure: 70.480 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.742
Equilibrium pressure: 69.060 kPa

Parsed:
Y1 : 0.743 -> 0.742
P  : 70.48 -> 69.06

  3%|▎         | 12/375 [00:23<11:53,  1.97s/it]

====================================================================================================
[12/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: CCC(CC)O
Operating temperature: 358.15 K
Liquid-phase mole fraction of component 1: 0.733
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.780
Equilibrium pressure: 71.530 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.782
Equilibrium pressure: 69.360 kPa

Parsed:
Y1 : 0.78 -> 0.782
P  : 71.53 -> 69.36

  3%|▎         | 13/375 [00:25<11:51,  1.97s/it]

====================================================================================================
[13/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: CCC(CC)O
Operating temperature: 358.15 K
Liquid-phase mole fraction of component 1: 0.797
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.810
Equilibrium pressure: 71.810 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.819
Equilibrium pressure: 70.800 kPa

Parsed:
Y1 : 0.81 -> 0.819
P  : 71.81 -> 70.8

  4%|▎         | 14/375 [00:27<11:49,  1.96s/it]

====================================================================================================
[14/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: CCC(CC)O
Operating temperature: 358.15 K
Liquid-phase mole fraction of component 1: 0.811
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.817
Equilibrium pressure: 71.810 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.823
Equilibrium pressure: 70.800 kPa

Parsed:
Y1 : 0.817 -> 0.823
P  : 71.81 -> 70.8

  4%|▍         | 15/375 [00:29<11:47,  1.96s/it]

====================================================================================================
[15/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: CCC(CC)O
Operating temperature: 358.15 K
Liquid-phase mole fraction of component 1: 0.830
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.826
Equilibrium pressure: 71.790 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.828
Equilibrium pressure: 69.360 kPa

Parsed:
Y1 : 0.826 -> 0.828
P  : 71.79 -> 69.36

  4%|▍         | 16/375 [00:31<11:45,  1.97s/it]

====================================================================================================
[16/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: CCC(CC)O
Operating temperature: 358.15 K
Liquid-phase mole fraction of component 1: 0.844
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.834
Equilibrium pressure: 71.750 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.833
Equilibrium pressure: 70.800 kPa

Parsed:
Y1 : 0.834 -> 0.833
P  : 71.75 -> 70.8

  5%|▍         | 17/375 [00:33<11:43,  1.96s/it]

====================================================================================================
[17/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: CCC(CC)O
Operating temperature: 358.15 K
Liquid-phase mole fraction of component 1: 0.859
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.843
Equilibrium pressure: 71.650 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.843
Equilibrium pressure: 70.090 kPa

Parsed:
Y1 : 0.843 -> 0.843
P  : 71.65 -> 70.09

  5%|▍         | 18/375 [00:35<11:40,  1.96s/it]

====================================================================================================
[18/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: CCC(CC)O
Operating temperature: 358.15 K
Liquid-phase mole fraction of component 1: 0.931
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.898
Equilibrium pressure: 70.660 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.900
Equilibrium pressure: 68.900 kPa

Parsed:
Y1 : 0.898 -> 0.9
P  : 70.66 -> 68.9

  5%|▌         | 19/375 [00:37<11:38,  1.96s/it]

====================================================================================================
[19/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: CCC(CC)O
Operating temperature: 358.15 K
Liquid-phase mole fraction of component 1: 0.956
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.927
Equilibrium pressure: 69.920 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.920
Equilibrium pressure: 68.090 kPa

Parsed:
Y1 : 0.927 -> 0.92
P  : 69.92 -> 68.09

  5%|▌         | 20/375 [00:39<11:35,  1.96s/it]

====================================================================================================
[20/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: CCC(CC)O
Operating temperature: 358.15 K
Liquid-phase mole fraction of component 1: 0.966
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.941
Equilibrium pressure: 69.540 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.933
Equilibrium pressure: 68.090 kPa

Parsed:
Y1 : 0.941 -> 0.933
P  : 69.54 -> 68.09

  6%|▌         | 21/375 [00:41<11:34,  1.96s/it]

====================================================================================================
[21/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: CCC(CC)O
Operating temperature: 358.15 K
Liquid-phase mole fraction of component 1: 0.982
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.966
Equilibrium pressure: 68.720 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.965
Equilibrium pressure: 68.000 kPa

Parsed:
Y1 : 0.966 -> 0.965
P  : 68.72 -> 68.0

  6%|▌         | 22/375 [00:43<11:32,  1.96s/it]

====================================================================================================
[22/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: CCC(CC)O
Operating temperature: 358.15 K
Liquid-phase mole fraction of component 1: 0.986
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.974
Equilibrium pressure: 68.450 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.973
Equilibrium pressure: 68.900 kPa

Parsed:
Y1 : 0.974 -> 0.973
P  : 68.45 -> 68.9

  6%|▌         | 23/375 [00:45<11:29,  1.96s/it]

====================================================================================================
[23/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: CCC(CC)O
Operating temperature: 358.15 K
Liquid-phase mole fraction of component 1: 0.993
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.986
Equilibrium pressure: 68.010 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.986
Equilibrium pressure: 68.900 kPa

Parsed:
Y1 : 0.986 -> 0.986
P  : 68.01 -> 68.9

  6%|▋         | 24/375 [00:47<11:27,  1.96s/it]

====================================================================================================
[24/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: CCC(CC)O
Operating temperature: 358.15 K
Liquid-phase mole fraction of component 1: 1.000
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 1.000
Equilibrium pressure: 67.350 kPa

Prediction:
Vapor-phase mole fraction of component 1: 1.000
Equilibrium pressure: 67.360 kPa

Parsed:
Y1 : 1.0 -> 1.0
P  : 67.35 -> 67.36

  7%|▋         | 25/375 [00:49<11:20,  1.94s/it]

====================================================================================================
[25/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CC1=CC=CC=C1
Component 2 SMILES: CCCCCCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.000
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.000
Equilibrium pressure: 4.152 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.000
Equilibrium pressure: 0.800 kPa

Parsed:
Y1 : 0.0 -> 0.0
P  : 4.152 -> 0.8

  7%|▋         | 26/375 [00:51<11:14,  1.93s/it]

====================================================================================================
[26/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CC1=CC=CC=C1
Component 2 SMILES: CCCCCCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.061
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.138
Equilibrium pressure: 4.530 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.283
Equilibrium pressure: 4.090 kPa

Parsed:
Y1 : 0.138 -> 0.283
P  : 4.53 -> 4.09

  7%|▋         | 27/375 [00:52<11:09,  1.92s/it]

====================================================================================================
[27/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CC1=CC=CC=C1
Component 2 SMILES: CCCCCCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.132
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.269
Equilibrium pressure: 4.968 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.432
Equilibrium pressure: 5.095 kPa

Parsed:
Y1 : 0.269 -> 0.432
P  : 4.968 -> 5.095

  7%|▋         | 28/375 [00:54<11:04,  1.92s/it]

====================================================================================================
[28/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CC1=CC=CC=C1
Component 2 SMILES: CCCCCCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.199
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.368
Equilibrium pressure: 5.314 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.532
Equilibrium pressure: 5.090 kPa

Parsed:
Y1 : 0.368 -> 0.532
P  : 5.314 -> 5.09

  8%|▊         | 29/375 [00:56<11:00,  1.91s/it]

====================================================================================================
[29/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CC1=CC=CC=C1
Component 2 SMILES: CCCCCCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.271
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.457
Equilibrium pressure: 5.678 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.692
Equilibrium pressure: 5.095 kPa

Parsed:
Y1 : 0.457 -> 0.692
P  : 5.678 -> 5.095

  8%|▊         | 30/375 [00:58<10:57,  1.91s/it]

====================================================================================================
[30/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CC1=CC=CC=C1
Component 2 SMILES: CCCCCCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.351
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.539
Equilibrium pressure: 6.046 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.791
Equilibrium pressure: 5.390 kPa

Parsed:
Y1 : 0.539 -> 0.791
P  : 6.046 -> 5.39

  8%|▊         | 31/375 [01:00<10:55,  1.91s/it]

====================================================================================================
[31/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CC1=CC=CC=C1
Component 2 SMILES: CCCCCCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.421
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.602
Equilibrium pressure: 6.350 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.829
Equilibrium pressure: 6.390 kPa

Parsed:
Y1 : 0.602 -> 0.829
P  : 6.35 -> 6.39

  9%|▊         | 32/375 [01:02<10:52,  1.90s/it]

====================================================================================================
[32/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CC1=CC=CC=C1
Component 2 SMILES: CCCCCCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.580
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.720
Equilibrium pressure: 6.914 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.892
Equilibrium pressure: 7.900 kPa

Parsed:
Y1 : 0.72 -> 0.892
P  : 6.914 -> 7.9

  9%|▉         | 33/375 [01:04<10:51,  1.90s/it]

====================================================================================================
[33/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CC1=CC=CC=C1
Component 2 SMILES: CCCCCCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.639
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.758
Equilibrium pressure: 7.095 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.893
Equilibrium pressure: 7.900 kPa

Parsed:
Y1 : 0.758 -> 0.893
P  : 7.095 -> 7.9

  9%|▉         | 34/375 [01:06<10:48,  1.90s/it]

====================================================================================================
[34/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CC1=CC=CC=C1
Component 2 SMILES: CCCCCCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.721
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.810
Equilibrium pressure: 7.310 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.923
Equilibrium pressure: 8.800 kPa

Parsed:
Y1 : 0.81 -> 0.923
P  : 7.31 -> 8.8

  9%|▉         | 35/375 [01:08<10:47,  1.90s/it]

====================================================================================================
[35/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CC1=CC=CC=C1
Component 2 SMILES: CCCCCCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.805
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.862
Equilibrium pressure: 7.555 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.942
Equilibrium pressure: 8.905 kPa

Parsed:
Y1 : 0.862 -> 0.942
P  : 7.555 -> 8.905

 10%|▉         | 36/375 [01:10<10:45,  1.91s/it]

====================================================================================================
[36/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CC1=CC=CC=C1
Component 2 SMILES: CCCCCCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 1.000
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 1.000
Equilibrium pressure: 7.894 kPa

Prediction:
Vapor-phase mole fraction of component 1: 1.000
Equilibrium pressure: 6.890 kPa

Parsed:
Y1 : 1.0 -> 1.0
P  : 7.894 -> 6.89

 10%|▉         | 37/375 [01:11<10:43,  1.90s/it]

====================================================================================================
[37/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCC1=CC=CC=C1
Component 2 SMILES: CCCCCCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.000
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.000
Equilibrium pressure: 4.152 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.000
Equilibrium pressure: 4.050 kPa

Parsed:
Y1 : 0.0 -> 0.0
P  : 4.152 -> 4.05

 10%|█         | 38/375 [01:13<10:41,  1.90s/it]

====================================================================================================
[38/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCC1=CC=CC=C1
Component 2 SMILES: CCCCCCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.132
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.117
Equilibrium pressure: 4.109 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.303
Equilibrium pressure: 6.900 kPa

Parsed:
Y1 : 0.117 -> 0.303
P  : 4.109 -> 6.9

 10%|█         | 39/375 [01:15<10:38,  1.90s/it]

====================================================================================================
[39/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCC1=CC=CC=C1
Component 2 SMILES: CCCCCCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.228
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.197
Equilibrium pressure: 4.060 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.508
Equilibrium pressure: 6.905 kPa

Parsed:
Y1 : 0.197 -> 0.508
P  : 4.06 -> 6.905

 11%|█         | 40/375 [01:17<10:36,  1.90s/it]

====================================================================================================
[40/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCC1=CC=CC=C1
Component 2 SMILES: CCCCCCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.305
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.260
Equilibrium pressure: 4.000 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.652
Equilibrium pressure: 7.900 kPa

Parsed:
Y1 : 0.26 -> 0.652
P  : 4.0 -> 7.9

 11%|█         | 41/375 [01:19<10:34,  1.90s/it]

====================================================================================================
[41/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCC1=CC=CC=C1
Component 2 SMILES: CCCCCCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.369
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.311
Equilibrium pressure: 3.954 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.729
Equilibrium pressure: 6.900 kPa

Parsed:
Y1 : 0.311 -> 0.729
P  : 3.954 -> 6.9

 11%|█         | 42/375 [01:21<10:32,  1.90s/it]

====================================================================================================
[42/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCC1=CC=CC=C1
Component 2 SMILES: CCCCCCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.467
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.388
Equilibrium pressure: 3.852 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.793
Equilibrium pressure: 8.905 kPa

Parsed:
Y1 : 0.388 -> 0.793
P  : 3.852 -> 8.905

 11%|█▏        | 43/375 [01:23<10:31,  1.90s/it]

====================================================================================================
[43/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCC1=CC=CC=C1
Component 2 SMILES: CCCCCCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.560
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.465
Equilibrium pressure: 3.746 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.842
Equilibrium pressure: 9.800 kPa

Parsed:
Y1 : 0.465 -> 0.842
P  : 3.746 -> 9.8

 12%|█▏        | 44/375 [01:25<10:35,  1.92s/it]

====================================================================================================
[44/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCC1=CC=CC=C1
Component 2 SMILES: CCCCCCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.709
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.598
Equilibrium pressure: 3.532 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.902
Equilibrium pressure: 10.090 kPa

Parsed:
Y1 : 0.598 -> 0.902
P  : 3.532 -> 10.09

 12%|█▏        | 45/375 [01:27<10:37,  1.93s/it]

====================================================================================================
[45/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCC1=CC=CC=C1
Component 2 SMILES: CCCCCCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.780
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.672
Equilibrium pressure: 3.409 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.920
Equilibrium pressure: 11.000 kPa

Parsed:
Y1 : 0.672 -> 0.92
P  : 3.409 -> 11.0

 12%|█▏        | 46/375 [01:29<10:37,  1.94s/it]

====================================================================================================
[46/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCC1=CC=CC=C1
Component 2 SMILES: CCCCCCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.842
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.744
Equilibrium pressure: 3.285 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.942
Equilibrium pressure: 10.090 kPa

Parsed:
Y1 : 0.744 -> 0.942
P  : 3.285 -> 10.09

 13%|█▎        | 47/375 [01:31<10:38,  1.95s/it]

====================================================================================================
[47/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCC1=CC=CC=C1
Component 2 SMILES: CCCCCCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.897
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.820
Equilibrium pressure: 3.142 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.962
Equilibrium pressure: 11.000 kPa

Parsed:
Y1 : 0.82 -> 0.962
P  : 3.142 -> 11.0

 13%|█▎        | 48/375 [01:33<10:37,  1.95s/it]

====================================================================================================
[48/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCC1=CC=CC=C1
Component 2 SMILES: CCCCCCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.957
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.916
Equilibrium pressure: 2.992 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.985
Equilibrium pressure: 10.090 kPa

Parsed:
Y1 : 0.916 -> 0.985
P  : 2.992 -> 10.09

 13%|█▎        | 49/375 [01:35<10:30,  1.93s/it]

====================================================================================================
[49/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCC1=CC=CC=C1
Component 2 SMILES: CCCCCCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 1.000
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 1.000
Equilibrium pressure: 2.874 kPa

Prediction:
Vapor-phase mole fraction of component 1: 1.000
Equilibrium pressure: 9.000 kPa

Parsed:
Y1 : 1.0 -> 1.0
P  : 2.874 -> 9.0

 13%|█▎        | 50/375 [01:37<10:30,  1.94s/it]

====================================================================================================
[50/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: CCCCOC
Operating temperature: 310.00 K
Liquid-phase mole fraction of component 1: 0.000
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.000
Equilibrium pressure: 30.670 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.000
Equilibrium pressure: 20.900 kPa

Parsed:
Y1 : 0.0 -> 0.0
P  : 30.67 -> 20.9

 14%|█▎        | 51/375 [01:38<10:31,  1.95s/it]

====================================================================================================
[51/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: CCCCOC
Operating temperature: 310.00 K
Liquid-phase mole fraction of component 1: 0.029
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.116
Equilibrium pressure: 33.500 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.123
Equilibrium pressure: 23.900 kPa

Parsed:
Y1 : 0.116 -> 0.123
P  : 33.5 -> 23.9

 14%|█▍        | 52/375 [01:40<10:30,  1.95s/it]

====================================================================================================
[52/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: CCCCOC
Operating temperature: 310.00 K
Liquid-phase mole fraction of component 1: 0.069
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.222
Equilibrium pressure: 37.160 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.202
Equilibrium pressure: 26.900 kPa

Parsed:
Y1 : 0.222 -> 0.202
P  : 37.16 -> 26.9

 14%|█▍        | 53/375 [01:42<10:30,  1.96s/it]

====================================================================================================
[53/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: CCCCOC
Operating temperature: 310.00 K
Liquid-phase mole fraction of component 1: 0.092
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.263
Equilibrium pressure: 38.520 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.283
Equilibrium pressure: 26.900 kPa

Parsed:
Y1 : 0.263 -> 0.283
P  : 38.52 -> 26.9

 14%|█▍        | 54/375 [01:44<10:28,  1.96s/it]

====================================================================================================
[54/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: CCCCOC
Operating temperature: 310.00 K
Liquid-phase mole fraction of component 1: 0.132
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.311
Equilibrium pressure: 40.300 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.329
Equilibrium pressure: 30.000 kPa

Parsed:
Y1 : 0.311 -> 0.329
P  : 40.3 -> 30.0

 15%|█▍        | 55/375 [01:46<10:27,  1.96s/it]

====================================================================================================
[55/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: CCCCOC
Operating temperature: 310.00 K
Liquid-phase mole fraction of component 1: 0.193
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.363
Equilibrium pressure: 42.070 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.373
Equilibrium pressure: 30.900 kPa

Parsed:
Y1 : 0.363 -> 0.373
P  : 42.07 -> 30.9

 15%|█▍        | 56/375 [01:48<10:26,  1.97s/it]

====================================================================================================
[56/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: CCCCOC
Operating temperature: 310.00 K
Liquid-phase mole fraction of component 1: 0.355
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.452
Equilibrium pressure: 44.330 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.452
Equilibrium pressure: 36.100 kPa

Parsed:
Y1 : 0.452 -> 0.452
P  : 44.33 -> 36.1

 15%|█▌        | 57/375 [01:50<10:24,  1.96s/it]

====================================================================================================
[57/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: CCCCOC
Operating temperature: 310.00 K
Liquid-phase mole fraction of component 1: 0.478
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.490
Equilibrium pressure: 44.680 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.493
Equilibrium pressure: 39.000 kPa

Parsed:
Y1 : 0.49 -> 0.493
P  : 44.68 -> 39.0

 15%|█▌        | 58/375 [01:52<10:22,  1.97s/it]

====================================================================================================
[58/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: CCCCOC
Operating temperature: 310.00 K
Liquid-phase mole fraction of component 1: 0.589
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.526
Equilibrium pressure: 44.520 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.553
Equilibrium pressure: 38.000 kPa

Parsed:
Y1 : 0.526 -> 0.553
P  : 44.52 -> 38.0

 16%|█▌        | 59/375 [01:54<10:20,  1.96s/it]

====================================================================================================
[59/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: CCCCOC
Operating temperature: 310.00 K
Liquid-phase mole fraction of component 1: 0.672
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.558
Equilibrium pressure: 44.020 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.592
Equilibrium pressure: 38.000 kPa

Parsed:
Y1 : 0.558 -> 0.592
P  : 44.02 -> 38.0

 16%|█▌        | 60/375 [01:56<10:18,  1.96s/it]

====================================================================================================
[60/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: CCCCOC
Operating temperature: 310.00 K
Liquid-phase mole fraction of component 1: 0.766
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.605
Equilibrium pressure: 42.830 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.652
Equilibrium pressure: 36.100 kPa

Parsed:
Y1 : 0.605 -> 0.652
P  : 42.83 -> 36.1

 16%|█▋        | 61/375 [01:58<10:16,  1.96s/it]

====================================================================================================
[61/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: CCCCOC
Operating temperature: 310.00 K
Liquid-phase mole fraction of component 1: 0.820
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.642
Equilibrium pressure: 41.680 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.700
Equilibrium pressure: 36.100 kPa

Parsed:
Y1 : 0.642 -> 0.7
P  : 41.68 -> 36.1

 17%|█▋        | 62/375 [02:00<10:14,  1.96s/it]

====================================================================================================
[62/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: CCCCOC
Operating temperature: 310.00 K
Liquid-phase mole fraction of component 1: 0.865
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.685
Equilibrium pressure: 40.250 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.732
Equilibrium pressure: 33.900 kPa

Parsed:
Y1 : 0.685 -> 0.732
P  : 40.25 -> 33.9

 17%|█▋        | 63/375 [02:02<10:12,  1.96s/it]

====================================================================================================
[63/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: CCCCOC
Operating temperature: 310.00 K
Liquid-phase mole fraction of component 1: 0.903
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.732
Equilibrium pressure: 38.600 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.781
Equilibrium pressure: 33.900 kPa

Parsed:
Y1 : 0.732 -> 0.781
P  : 38.6 -> 33.9

 17%|█▋        | 64/375 [02:04<10:11,  1.97s/it]

====================================================================================================
[64/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: CCCCOC
Operating temperature: 310.00 K
Liquid-phase mole fraction of component 1: 0.942
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.803
Equilibrium pressure: 36.230 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.842
Equilibrium pressure: 30.000 kPa

Parsed:
Y1 : 0.803 -> 0.842
P  : 36.23 -> 30.0

 17%|█▋        | 65/375 [02:06<10:08,  1.96s/it]

====================================================================================================
[65/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: CCCCOC
Operating temperature: 310.00 K
Liquid-phase mole fraction of component 1: 0.964
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.866
Equilibrium pressure: 34.330 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.892
Equilibrium pressure: 26.900 kPa

Parsed:
Y1 : 0.866 -> 0.892
P  : 34.33 -> 26.9

 18%|█▊        | 66/375 [02:08<10:07,  1.96s/it]

====================================================================================================
[66/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: CCCCOC
Operating temperature: 310.00 K
Liquid-phase mole fraction of component 1: 0.991
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.956
Equilibrium pressure: 31.700 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.953
Equilibrium pressure: 26.100 kPa

Parsed:
Y1 : 0.956 -> 0.953
P  : 31.7 -> 26.1

 18%|█▊        | 67/375 [02:10<10:05,  1.97s/it]

====================================================================================================
[67/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: CCCCOC
Operating temperature: 310.00 K
Liquid-phase mole fraction of component 1: 0.997
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.985
Equilibrium pressure: 30.920 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.983
Equilibrium pressure: 27.900 kPa

Parsed:
Y1 : 0.985 -> 0.983
P  : 30.92 -> 27.9

 18%|█▊        | 68/375 [02:12<10:03,  1.96s/it]

====================================================================================================
[68/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CO
Component 2 SMILES: CCCCOC
Operating temperature: 310.00 K
Liquid-phase mole fraction of component 1: 1.000
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 1.000
Equilibrium pressure: 30.540 kPa

Prediction:
Vapor-phase mole fraction of component 1: 1.000
Equilibrium pressure: 30.800 kPa

Parsed:
Y1 : 1.0 -> 1.0
P  : 30.54 -> 30.8

 18%|█▊        | 69/375 [02:14<10:01,  1.96s/it]

====================================================================================================
[69/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: C1CCCCC1
Operating temperature: 298.15 K
Liquid-phase mole fraction of component 1: 0.000
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.000
Equilibrium pressure: 6.114 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.000
Equilibrium pressure: 10.000 kPa

Parsed:
Y1 : 0.0 -> 0.0
P  : 6.114 -> 10.0

 19%|█▊        | 70/375 [02:16<09:58,  1.96s/it]

====================================================================================================
[70/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: C1CCCCC1
Operating temperature: 298.15 K
Liquid-phase mole fraction of component 1: 0.045
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.096
Equilibrium pressure: 6.475 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.118
Equilibrium pressure: 11.000 kPa

Parsed:
Y1 : 0.096 -> 0.118
P  : 6.475 -> 11.0

 19%|█▉        | 71/375 [02:18<09:56,  1.96s/it]

====================================================================================================
[71/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: C1CCCCC1
Operating temperature: 298.15 K
Liquid-phase mole fraction of component 1: 0.099
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.197
Equilibrium pressure: 6.875 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.253
Equilibrium pressure: 10.000 kPa

Parsed:
Y1 : 0.197 -> 0.253
P  : 6.875 -> 10.0

 19%|█▉        | 72/375 [02:20<09:53,  1.96s/it]

====================================================================================================
[72/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: C1CCCCC1
Operating temperature: 298.15 K
Liquid-phase mole fraction of component 1: 0.149
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.281
Equilibrium pressure: 7.245 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.263
Equilibrium pressure: 12.030 kPa

Parsed:
Y1 : 0.281 -> 0.263
P  : 7.245 -> 12.03

 19%|█▉        | 73/375 [02:22<09:52,  1.96s/it]

====================================================================================================
[73/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: C1CCCCC1
Operating temperature: 298.15 K
Liquid-phase mole fraction of component 1: 0.199
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.355
Equilibrium pressure: 7.619 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.293
Equilibrium pressure: 12.030 kPa

Parsed:
Y1 : 0.355 -> 0.293
P  : 7.619 -> 12.03

 20%|█▉        | 74/375 [02:24<09:50,  1.96s/it]

====================================================================================================
[74/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: C1CCCCC1
Operating temperature: 298.15 K
Liquid-phase mole fraction of component 1: 0.253
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.428
Equilibrium pressure: 8.018 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.373
Equilibrium pressure: 12.030 kPa

Parsed:
Y1 : 0.428 -> 0.373
P  : 8.018 -> 12.03

 20%|██        | 75/375 [02:26<09:48,  1.96s/it]

====================================================================================================
[75/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: C1CCCCC1
Operating temperature: 298.15 K
Liquid-phase mole fraction of component 1: 0.302
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.487
Equilibrium pressure: 8.370 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.382
Equilibrium pressure: 12.080 kPa

Parsed:
Y1 : 0.487 -> 0.382
P  : 8.37 -> 12.08

 20%|██        | 76/375 [02:28<09:45,  1.96s/it]

====================================================================================================
[76/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: C1CCCCC1
Operating temperature: 298.15 K
Liquid-phase mole fraction of component 1: 0.352
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.542
Equilibrium pressure: 8.732 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.432
Equilibrium pressure: 13.090 kPa

Parsed:
Y1 : 0.542 -> 0.432
P  : 8.732 -> 13.09

 21%|██        | 77/375 [02:30<09:44,  1.96s/it]

====================================================================================================
[77/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: C1CCCCC1
Operating temperature: 298.15 K
Liquid-phase mole fraction of component 1: 0.402
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.593
Equilibrium pressure: 9.085 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.453
Equilibrium pressure: 13.090 kPa

Parsed:
Y1 : 0.593 -> 0.453
P  : 9.085 -> 13.09

 21%|██        | 78/375 [02:31<09:43,  1.96s/it]

====================================================================================================
[78/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: C1CCCCC1
Operating temperature: 298.15 K
Liquid-phase mole fraction of component 1: 0.452
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.639
Equilibrium pressure: 9.440 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.452
Equilibrium pressure: 13.000 kPa

Parsed:
Y1 : 0.639 -> 0.452
P  : 9.44 -> 13.0

 21%|██        | 79/375 [02:33<09:41,  1.96s/it]

====================================================================================================
[79/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: C1CCCCC1
Operating temperature: 298.15 K
Liquid-phase mole fraction of component 1: 0.501
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.682
Equilibrium pressure: 9.788 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.493
Equilibrium pressure: 13.030 kPa

Parsed:
Y1 : 0.682 -> 0.493
P  : 9.788 -> 13.03

 21%|██▏       | 80/375 [02:35<09:39,  1.96s/it]

====================================================================================================
[80/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: C1CCCCC1
Operating temperature: 298.15 K
Liquid-phase mole fraction of component 1: 0.548
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.720
Equilibrium pressure: 10.083 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.493
Equilibrium pressure: 13.030 kPa

Parsed:
Y1 : 0.72 -> 0.493
P  : 10.083 -> 13.03

 22%|██▏       | 81/375 [02:37<09:36,  1.96s/it]

====================================================================================================
[81/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: C1CCCCC1
Operating temperature: 298.15 K
Liquid-phase mole fraction of component 1: 0.602
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.761
Equilibrium pressure: 10.452 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.522
Equilibrium pressure: 12.800 kPa

Parsed:
Y1 : 0.761 -> 0.522
P  : 10.452 -> 12.8

 22%|██▏       | 82/375 [02:39<09:35,  1.96s/it]

====================================================================================================
[82/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: C1CCCCC1
Operating temperature: 298.15 K
Liquid-phase mole fraction of component 1: 0.651
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.795
Equilibrium pressure: 10.772 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.523
Equilibrium pressure: 12.800 kPa

Parsed:
Y1 : 0.795 -> 0.523
P  : 10.772 -> 12.8

 22%|██▏       | 83/375 [02:41<09:33,  1.96s/it]

====================================================================================================
[83/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: C1CCCCC1
Operating temperature: 298.15 K
Liquid-phase mole fraction of component 1: 0.700
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.828
Equilibrium pressure: 11.103 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.533
Equilibrium pressure: 12.080 kPa

Parsed:
Y1 : 0.828 -> 0.533
P  : 11.103 -> 12.08

 22%|██▏       | 84/375 [02:43<09:31,  1.96s/it]

====================================================================================================
[84/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: C1CCCCC1
Operating temperature: 298.15 K
Liquid-phase mole fraction of component 1: 0.751
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.860
Equilibrium pressure: 11.440 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.603
Equilibrium pressure: 12.030 kPa

Parsed:
Y1 : 0.86 -> 0.603
P  : 11.44 -> 12.03

 23%|██▎       | 85/375 [02:45<09:28,  1.96s/it]

====================================================================================================
[85/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: C1CCCCC1
Operating temperature: 298.15 K
Liquid-phase mole fraction of component 1: 0.808
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.894
Equilibrium pressure: 11.810 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.628
Equilibrium pressure: 11.000 kPa

Parsed:
Y1 : 0.894 -> 0.628
P  : 11.81 -> 11.0

 23%|██▎       | 86/375 [02:47<09:26,  1.96s/it]

====================================================================================================
[86/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: C1CCCCC1
Operating temperature: 298.15 K
Liquid-phase mole fraction of component 1: 0.849
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.918
Equilibrium pressure: 12.068 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.753
Equilibrium pressure: 12.030 kPa

Parsed:
Y1 : 0.918 -> 0.753
P  : 12.068 -> 12.03

 23%|██▎       | 87/375 [02:49<09:25,  1.96s/it]

====================================================================================================
[87/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: C1CCCCC1
Operating temperature: 298.15 K
Liquid-phase mole fraction of component 1: 0.896
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.944
Equilibrium pressure: 12.369 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.792
Equilibrium pressure: 10.090 kPa

Parsed:
Y1 : 0.944 -> 0.792
P  : 12.369 -> 10.09

 23%|██▎       | 88/375 [02:51<09:18,  1.94s/it]

====================================================================================================
[88/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: C1CCCCC1
Operating temperature: 298.15 K
Liquid-phase mole fraction of component 1: 0.948
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.972
Equilibrium pressure: 12.674 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.853
Equilibrium pressure: 9.090 kPa

Parsed:
Y1 : 0.972 -> 0.853
P  : 12.674 -> 9.09

 24%|██▎       | 89/375 [02:53<09:12,  1.93s/it]

====================================================================================================
[89/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: C1CCCCC1
Operating temperature: 298.15 K
Liquid-phase mole fraction of component 1: 1.000
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 1.000
Equilibrium pressure: 13.007 kPa

Prediction:
Vapor-phase mole fraction of component 1: 1.000
Equilibrium pressure: 7.360 kPa

Parsed:
Y1 : 1.0 -> 1.0
P  : 13.007 -> 7.36

 24%|██▍       | 90/375 [02:55<09:13,  1.94s/it]

====================================================================================================
[90/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: C1CCCCC1
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.000
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.000
Equilibrium pressure: 12.344 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.000
Equilibrium pressure: 24.390 kPa

Parsed:
Y1 : 0.0 -> 0.0
P  : 12.344 -> 24.39

 24%|██▍       | 91/375 [02:57<09:12,  1.94s/it]

====================================================================================================
[91/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: C1CCCCC1
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.100
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.186
Equilibrium pressure: 13.676 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.223
Equilibrium pressure: 26.190 kPa

Parsed:
Y1 : 0.186 -> 0.223
P  : 13.676 -> 26.19

 25%|██▍       | 92/375 [02:59<09:12,  1.95s/it]

====================================================================================================
[92/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: C1CCCCC1
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.103
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.192
Equilibrium pressure: 13.713 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.203
Equilibrium pressure: 26.900 kPa

Parsed:
Y1 : 0.192 -> 0.203
P  : 13.713 -> 26.9

 25%|██▍       | 93/375 [03:01<09:10,  1.95s/it]

====================================================================================================
[93/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: C1CCCCC1
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.153
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.272
Equilibrium pressure: 14.397 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.253
Equilibrium pressure: 27.900 kPa

Parsed:
Y1 : 0.272 -> 0.253
P  : 14.397 -> 27.9

 25%|██▌       | 94/375 [03:03<09:09,  1.96s/it]

====================================================================================================
[94/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: C1CCCCC1
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.203
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.344
Equilibrium pressure: 15.067 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.293
Equilibrium pressure: 31.000 kPa

Parsed:
Y1 : 0.344 -> 0.293
P  : 15.067 -> 31.0

 25%|██▌       | 95/375 [03:05<09:07,  1.96s/it]

====================================================================================================
[95/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: C1CCCCC1
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.252
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.408
Equilibrium pressure: 15.705 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.350
Equilibrium pressure: 31.800 kPa

Parsed:
Y1 : 0.408 -> 0.35
P  : 15.705 -> 31.8

 26%|██▌       | 96/375 [03:07<09:06,  1.96s/it]

====================================================================================================
[96/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: C1CCCCC1
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.301
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.467
Equilibrium pressure: 16.331 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.373
Equilibrium pressure: 32.000 kPa

Parsed:
Y1 : 0.467 -> 0.373
P  : 16.331 -> 32.0

 26%|██▌       | 97/375 [03:09<09:04,  1.96s/it]

====================================================================================================
[97/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: C1CCCCC1
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.352
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.523
Equilibrium pressure: 16.967 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.372
Equilibrium pressure: 33.000 kPa

Parsed:
Y1 : 0.523 -> 0.372
P  : 16.967 -> 33.0

 26%|██▌       | 98/375 [03:11<09:03,  1.96s/it]

====================================================================================================
[98/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: C1CCCCC1
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.402
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.574
Equilibrium pressure: 17.594 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.382
Equilibrium pressure: 33.300 kPa

Parsed:
Y1 : 0.574 -> 0.382
P  : 17.594 -> 33.3

 26%|██▋       | 99/375 [03:13<09:01,  1.96s/it]

====================================================================================================
[99/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: C1CCCCC1
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.450
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.621
Equilibrium pressure: 18.202 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.393
Equilibrium pressure: 32.000 kPa

Parsed:
Y1 : 0.621 -> 0.393
P  : 18.202 -> 32.0

 27%|██▋       | 100/375 [03:15<08:59,  1.96s/it]

====================================================================================================
[100/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: C1CCCCC1
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.497
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.662
Equilibrium pressure: 18.784 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.439
Equilibrium pressure: 32.000 kPa

Parsed:
Y1 : 0.662 -> 0.439
P  : 18.784 -> 32.0

 27%|██▋       | 101/375 [03:16<08:57,  1.96s/it]

====================================================================================================
[101/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: C1CCCCC1
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.549
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.706
Equilibrium pressure: 19.375 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.472
Equilibrium pressure: 31.800 kPa

Parsed:
Y1 : 0.706 -> 0.472
P  : 19.375 -> 31.8

 27%|██▋       | 102/375 [03:18<08:55,  1.96s/it]

====================================================================================================
[102/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: C1CCCCC1
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.599
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.745
Equilibrium pressure: 19.995 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.493
Equilibrium pressure: 27.900 kPa

Parsed:
Y1 : 0.745 -> 0.493
P  : 19.995 -> 27.9

 27%|██▋       | 103/375 [03:20<08:53,  1.96s/it]

====================================================================================================
[103/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: C1CCCCC1
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.645
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.779
Equilibrium pressure: 20.513 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.493
Equilibrium pressure: 27.900 kPa

Parsed:
Y1 : 0.779 -> 0.493
P  : 20.513 -> 27.9

 28%|██▊       | 104/375 [03:22<08:51,  1.96s/it]

====================================================================================================
[104/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: C1CCCCC1
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.698
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.817
Equilibrium pressure: 21.147 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.533
Equilibrium pressure: 26.900 kPa

Parsed:
Y1 : 0.817 -> 0.533
P  : 21.147 -> 26.9

 28%|██▊       | 105/375 [03:24<08:49,  1.96s/it]

====================================================================================================
[105/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: C1CCCCC1
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.743
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.847
Equilibrium pressure: 21.678 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.552
Equilibrium pressure: 26.190 kPa

Parsed:
Y1 : 0.847 -> 0.552
P  : 21.678 -> 26.19

 28%|██▊       | 106/375 [03:26<08:47,  1.96s/it]

====================================================================================================
[106/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: C1CCCCC1
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.800
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.884
Equilibrium pressure: 22.338 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.603
Equilibrium pressure: 25.000 kPa

Parsed:
Y1 : 0.884 -> 0.603
P  : 22.338 -> 25.0

 29%|██▊       | 107/375 [03:28<08:44,  1.96s/it]

====================================================================================================
[107/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: C1CCCCC1
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.850
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.915
Equilibrium pressure: 22.942 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.663
Equilibrium pressure: 25.000 kPa

Parsed:
Y1 : 0.915 -> 0.663
P  : 22.942 -> 25.0

 29%|██▉       | 108/375 [03:30<08:43,  1.96s/it]

====================================================================================================
[108/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: C1CCCCC1
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.910
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.950
Equilibrium pressure: 23.607 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.780
Equilibrium pressure: 22.900 kPa

Parsed:
Y1 : 0.95 -> 0.78
P  : 23.607 -> 22.9

 29%|██▉       | 109/375 [03:32<08:41,  1.96s/it]

====================================================================================================
[109/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: C1CCCCC1
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.951
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.973
Equilibrium pressure: 24.064 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.829
Equilibrium pressure: 18.000 kPa

Parsed:
Y1 : 0.973 -> 0.829
P  : 24.064 -> 18.0

 29%|██▉       | 110/375 [03:34<08:39,  1.96s/it]

====================================================================================================
[110/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCC
Component 2 SMILES: C1CCCCC1
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 1.000
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 1.000
Equilibrium pressure: 24.631 kPa

Prediction:
Vapor-phase mole fraction of component 1: 1.000
Equilibrium pressure: 20.900 kPa

Parsed:
Y1 : 1.0 -> 1.0
P  : 24.631 -> 20.9

 30%|██▉       | 111/375 [03:36<08:33,  1.95s/it]

====================================================================================================
[111/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCOCCC
Operating temperature: 288.15 K
Liquid-phase mole fraction of component 1: 0.000
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.000
Equilibrium pressure: 5.006 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.000
Equilibrium pressure: 5.080 kPa

Parsed:
Y1 : 0.0 -> 0.0
P  : 5.006 -> 5.08

 30%|██▉       | 112/375 [03:38<08:28,  1.93s/it]

====================================================================================================
[112/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCOCCC
Operating temperature: 288.15 K
Liquid-phase mole fraction of component 1: 0.084
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.088
Equilibrium pressure: 5.117 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.083
Equilibrium pressure: 5.800 kPa

Parsed:
Y1 : 0.088 -> 0.083
P  : 5.117 -> 5.8

 30%|███       | 113/375 [03:40<08:24,  1.92s/it]

====================================================================================================
[113/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCOCCC
Operating temperature: 288.15 K
Liquid-phase mole fraction of component 1: 0.111
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.103
Equilibrium pressure: 5.116 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.098
Equilibrium pressure: 5.806 kPa

Parsed:
Y1 : 0.103 -> 0.098
P  : 5.116 -> 5.806

 30%|███       | 114/375 [03:42<08:20,  1.92s/it]

====================================================================================================
[114/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCOCCC
Operating temperature: 288.15 K
Liquid-phase mole fraction of component 1: 0.146
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.120
Equilibrium pressure: 5.096 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.129
Equilibrium pressure: 5.900 kPa

Parsed:
Y1 : 0.12 -> 0.129
P  : 5.096 -> 5.9

 31%|███       | 115/375 [03:44<08:17,  1.91s/it]

====================================================================================================
[115/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCOCCC
Operating temperature: 288.15 K
Liquid-phase mole fraction of component 1: 0.176
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.131
Equilibrium pressure: 5.086 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.139
Equilibrium pressure: 5.806 kPa

Parsed:
Y1 : 0.131 -> 0.139
P  : 5.086 -> 5.806

 31%|███       | 116/375 [03:46<08:14,  1.91s/it]

====================================================================================================
[116/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCOCCC
Operating temperature: 288.15 K
Liquid-phase mole fraction of component 1: 0.204
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.170
Equilibrium pressure: 5.066 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.139
Equilibrium pressure: 5.900 kPa

Parsed:
Y1 : 0.17 -> 0.139
P  : 5.066 -> 5.9

 31%|███       | 117/375 [03:47<08:12,  1.91s/it]

====================================================================================================
[117/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCOCCC
Operating temperature: 288.15 K
Liquid-phase mole fraction of component 1: 0.285
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.161
Equilibrium pressure: 4.984 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.169
Equilibrium pressure: 5.800 kPa

Parsed:
Y1 : 0.161 -> 0.169
P  : 4.984 -> 5.8

 31%|███▏      | 118/375 [03:49<08:10,  1.91s/it]

====================================================================================================
[118/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCOCCC
Operating temperature: 288.15 K
Liquid-phase mole fraction of component 1: 0.415
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.188
Equilibrium pressure: 4.849 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.193
Equilibrium pressure: 5.095 kPa

Parsed:
Y1 : 0.188 -> 0.193
P  : 4.849 -> 5.095

 32%|███▏      | 119/375 [03:51<08:08,  1.91s/it]

====================================================================================================
[119/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCOCCC
Operating temperature: 288.15 K
Liquid-phase mole fraction of component 1: 0.529
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.216
Equilibrium pressure: 4.608 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.219
Equilibrium pressure: 5.090 kPa

Parsed:
Y1 : 0.216 -> 0.219
P  : 4.608 -> 5.09

 32%|███▏      | 120/375 [03:53<08:06,  1.91s/it]

====================================================================================================
[120/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCOCCC
Operating temperature: 288.15 K
Liquid-phase mole fraction of component 1: 0.581
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.230
Equilibrium pressure: 4.484 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.243
Equilibrium pressure: 4.090 kPa

Parsed:
Y1 : 0.23 -> 0.243
P  : 4.484 -> 4.09

 32%|███▏      | 121/375 [03:55<08:04,  1.91s/it]

====================================================================================================
[121/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCOCCC
Operating temperature: 288.15 K
Liquid-phase mole fraction of component 1: 0.712
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.284
Equilibrium pressure: 4.000 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.283
Equilibrium pressure: 4.090 kPa

Parsed:
Y1 : 0.284 -> 0.283
P  : 4.0 -> 4.09

 33%|███▎      | 122/375 [03:57<08:02,  1.91s/it]

====================================================================================================
[122/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCOCCC
Operating temperature: 288.15 K
Liquid-phase mole fraction of component 1: 0.721
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.288
Equilibrium pressure: 3.964 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.303
Equilibrium pressure: 4.090 kPa

Parsed:
Y1 : 0.288 -> 0.303
P  : 3.964 -> 4.09

 33%|███▎      | 123/375 [03:59<08:00,  1.91s/it]

====================================================================================================
[123/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCOCCC
Operating temperature: 288.15 K
Liquid-phase mole fraction of component 1: 0.805
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.346
Equilibrium pressure: 3.528 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.382
Equilibrium pressure: 4.030 kPa

Parsed:
Y1 : 0.346 -> 0.382
P  : 3.528 -> 4.03

 33%|███▎      | 124/375 [04:01<07:58,  1.91s/it]

====================================================================================================
[124/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCOCCC
Operating temperature: 288.15 K
Liquid-phase mole fraction of component 1: 0.933
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.573
Equilibrium pressure: 2.377 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.643
Equilibrium pressure: 3.095 kPa

Parsed:
Y1 : 0.573 -> 0.643
P  : 2.377 -> 3.095

 33%|███▎      | 125/375 [04:03<07:57,  1.91s/it]

====================================================================================================
[125/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCOCCC
Operating temperature: 288.15 K
Liquid-phase mole fraction of component 1: 1.000
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 1.000
Equilibrium pressure: 1.451 kPa

Prediction:
Vapor-phase mole fraction of component 1: 1.000
Equilibrium pressure: 2.000 kPa

Parsed:
Y1 : 1.0 -> 1.0
P  : 1.451 -> 2.0

 34%|███▎      | 126/375 [04:05<07:58,  1.92s/it]

====================================================================================================
[126/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCOCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.000
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.000
Equilibrium pressure: 16.639 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.000
Equilibrium pressure: 20.900 kPa

Parsed:
Y1 : 0.0 -> 0.0
P  : 16.639 -> 20.9

 34%|███▍      | 127/375 [04:07<08:00,  1.94s/it]

====================================================================================================
[127/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCOCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.084
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.113
Equilibrium pressure: 17.391 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.102
Equilibrium pressure: 23.090 kPa

Parsed:
Y1 : 0.113 -> 0.102
P  : 17.391 -> 23.09

 34%|███▍      | 128/375 [04:09<08:00,  1.94s/it]

====================================================================================================
[128/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCOCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.111
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.134
Equilibrium pressure: 17.520 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.119
Equilibrium pressure: 20.900 kPa

Parsed:
Y1 : 0.134 -> 0.119
P  : 17.52 -> 20.9

 34%|███▍      | 129/375 [04:11<08:00,  1.95s/it]

====================================================================================================
[129/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCOCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.146
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.157
Equilibrium pressure: 17.580 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.143
Equilibrium pressure: 23.090 kPa

Parsed:
Y1 : 0.157 -> 0.143
P  : 17.58 -> 23.09

 35%|███▍      | 130/375 [04:13<07:59,  1.96s/it]

====================================================================================================
[130/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCOCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.176
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.173
Equilibrium pressure: 17.599 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.161
Equilibrium pressure: 23.090 kPa

Parsed:
Y1 : 0.173 -> 0.161
P  : 17.599 -> 23.09

 35%|███▍      | 131/375 [04:15<07:57,  1.96s/it]

====================================================================================================
[131/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCOCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.204
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.186
Equilibrium pressure: 17.609 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.172
Equilibrium pressure: 23.090 kPa

Parsed:
Y1 : 0.186 -> 0.172
P  : 17.609 -> 23.09

 35%|███▌      | 132/375 [04:16<07:56,  1.96s/it]

====================================================================================================
[132/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCOCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.285
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.217
Equilibrium pressure: 17.453 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.218
Equilibrium pressure: 22.090 kPa

Parsed:
Y1 : 0.217 -> 0.218
P  : 17.453 -> 22.09

 35%|███▌      | 133/375 [04:18<07:54,  1.96s/it]

====================================================================================================
[133/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCOCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.416
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.258
Equilibrium pressure: 17.005 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.254
Equilibrium pressure: 19.390 kPa

Parsed:
Y1 : 0.258 -> 0.254
P  : 17.005 -> 19.39

 36%|███▌      | 134/375 [04:20<07:53,  1.96s/it]

====================================================================================================
[134/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCOCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.530
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.293
Equilibrium pressure: 16.411 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.283
Equilibrium pressure: 18.196 kPa

Parsed:
Y1 : 0.293 -> 0.283
P  : 16.411 -> 18.196

 36%|███▌      | 135/375 [04:22<07:51,  1.96s/it]

====================================================================================================
[135/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCOCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.581
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.312
Equilibrium pressure: 16.048 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.303
Equilibrium pressure: 17.900 kPa

Parsed:
Y1 : 0.312 -> 0.303
P  : 16.048 -> 17.9

 36%|███▋      | 136/375 [04:24<07:49,  1.96s/it]

====================================================================================================
[136/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCOCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.713
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.375
Equilibrium pressure: 14.715 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.352
Equilibrium pressure: 15.090 kPa

Parsed:
Y1 : 0.375 -> 0.352
P  : 14.715 -> 15.09

 37%|███▋      | 137/375 [04:26<07:47,  1.96s/it]

====================================================================================================
[137/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCOCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.722
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.381
Equilibrium pressure: 14.568 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.352
Equilibrium pressure: 15.090 kPa

Parsed:
Y1 : 0.381 -> 0.352
P  : 14.568 -> 15.09

 37%|███▋      | 138/375 [04:28<07:45,  1.96s/it]

====================================================================================================
[138/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCOCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.807
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.452
Equilibrium pressure: 13.143 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.438
Equilibrium pressure: 13.900 kPa

Parsed:
Y1 : 0.452 -> 0.438
P  : 13.143 -> 13.9

 37%|███▋      | 139/375 [04:30<07:42,  1.96s/it]

====================================================================================================
[139/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCOCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.934
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.680
Equilibrium pressure: 9.709 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.692
Equilibrium pressure: 10.095 kPa

Parsed:
Y1 : 0.68 -> 0.692
P  : 9.709 -> 10.095

 37%|███▋      | 140/375 [04:32<07:37,  1.95s/it]

====================================================================================================
[140/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCOCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 1.000
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 1.000
Equilibrium pressure: 7.025 kPa

Prediction:
Vapor-phase mole fraction of component 1: 1.000
Equilibrium pressure: 6.830 kPa

Parsed:
Y1 : 1.0 -> 1.0
P  : 7.025 -> 6.83

 38%|███▊      | 141/375 [04:34<07:36,  1.95s/it]

====================================================================================================
[141/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CC(C)O
Component 2 SMILES: CCCOCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.000
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.000
Equilibrium pressure: 16.639 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.000
Equilibrium pressure: 20.900 kPa

Parsed:
Y1 : 0.0 -> 0.0
P  : 16.639 -> 20.9

 38%|███▊      | 142/375 [04:36<07:35,  1.95s/it]

====================================================================================================
[142/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CC(C)O
Component 2 SMILES: CCCOCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.064
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.169
Equilibrium pressure: 19.056 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.172
Equilibrium pressure: 23.900 kPa

Parsed:
Y1 : 0.169 -> 0.172
P  : 19.056 -> 23.9

 38%|███▊      | 143/375 [04:38<07:33,  1.96s/it]

====================================================================================================
[143/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CC(C)O
Component 2 SMILES: CCCOCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.138
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.263
Equilibrium pressure: 20.338 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.252
Equilibrium pressure: 24.190 kPa

Parsed:
Y1 : 0.263 -> 0.252
P  : 20.338 -> 24.19

 38%|███▊      | 144/375 [04:40<07:31,  1.96s/it]

====================================================================================================
[144/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CC(C)O
Component 2 SMILES: CCCOCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.175
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.293
Equilibrium pressure: 20.789 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.283
Equilibrium pressure: 26.090 kPa

Parsed:
Y1 : 0.293 -> 0.283
P  : 20.789 -> 26.09

 39%|███▊      | 145/375 [04:42<07:31,  1.96s/it]

====================================================================================================
[145/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CC(C)O
Component 2 SMILES: CCCOCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.210
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.318
Equilibrium pressure: 20.905 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.300
Equilibrium pressure: 26.090 kPa

Parsed:
Y1 : 0.318 -> 0.3
P  : 20.905 -> 26.09

 39%|███▉      | 146/375 [04:44<07:28,  1.96s/it]

====================================================================================================
[146/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CC(C)O
Component 2 SMILES: CCCOCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.292
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.359
Equilibrium pressure: 21.301 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.353
Equilibrium pressure: 26.090 kPa

Parsed:
Y1 : 0.359 -> 0.353
P  : 21.301 -> 26.09

 39%|███▉      | 147/375 [04:46<07:27,  1.96s/it]

====================================================================================================
[147/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CC(C)O
Component 2 SMILES: CCCOCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.357
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.386
Equilibrium pressure: 21.376 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.382
Equilibrium pressure: 27.360 kPa

Parsed:
Y1 : 0.386 -> 0.382
P  : 21.376 -> 27.36

 39%|███▉      | 148/375 [04:48<07:25,  1.96s/it]

====================================================================================================
[148/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CC(C)O
Component 2 SMILES: CCCOCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.468
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.428
Equilibrium pressure: 21.325 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.408
Equilibrium pressure: 27.360 kPa

Parsed:
Y1 : 0.428 -> 0.408
P  : 21.325 -> 27.36

 40%|███▉      | 149/375 [04:50<07:23,  1.96s/it]

====================================================================================================
[149/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CC(C)O
Component 2 SMILES: CCCOCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.517
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.446
Equilibrium pressure: 21.262 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.452
Equilibrium pressure: 26.090 kPa

Parsed:
Y1 : 0.446 -> 0.452
P  : 21.262 -> 26.09

 40%|████      | 150/375 [04:52<07:22,  1.97s/it]

====================================================================================================
[150/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CC(C)O
Component 2 SMILES: CCCOCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.602
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.480
Equilibrium pressure: 21.045 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.492
Equilibrium pressure: 26.090 kPa

Parsed:
Y1 : 0.48 -> 0.492
P  : 21.045 -> 26.09

 40%|████      | 151/375 [04:54<07:19,  1.96s/it]

====================================================================================================
[151/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CC(C)O
Component 2 SMILES: CCCOCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.767
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.581
Equilibrium pressure: 19.660 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.583
Equilibrium pressure: 24.190 kPa

Parsed:
Y1 : 0.581 -> 0.583
P  : 19.66 -> 24.19

 41%|████      | 152/375 [04:56<07:17,  1.96s/it]

====================================================================================================
[152/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CC(C)O
Component 2 SMILES: CCCOCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.834
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.644
Equilibrium pressure: 18.708 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.649
Equilibrium pressure: 23.900 kPa

Parsed:
Y1 : 0.644 -> 0.649
P  : 18.708 -> 23.9

 41%|████      | 153/375 [04:58<07:16,  1.96s/it]

====================================================================================================
[153/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CC(C)O
Component 2 SMILES: CCCOCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.921
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.774
Equilibrium pressure: 16.768 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.749
Equilibrium pressure: 20.900 kPa

Parsed:
Y1 : 0.774 -> 0.749
P  : 16.768 -> 20.9

 41%|████      | 154/375 [05:00<07:13,  1.96s/it]

====================================================================================================
[154/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CC(C)O
Component 2 SMILES: CCCOCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 1.000
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 1.000
Equilibrium pressure: 13.966 kPa

Prediction:
Vapor-phase mole fraction of component 1: 1.000
Equilibrium pressure: 20.800 kPa

Parsed:
Y1 : 1.0 -> 1.0
P  : 13.966 -> 20.8

 41%|████▏     | 155/375 [05:02<07:08,  1.95s/it]

====================================================================================================
[155/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCCCCC
Component 2 SMILES: C1=CC=C(C=C1)O
Operating temperature: 393.15 K
Liquid-phase mole fraction of component 1: 0.000
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.000
Equilibrium pressure: 12.892 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.000
Equilibrium pressure: 4.900 kPa

Parsed:
Y1 : 0.0 -> 0.0
P  : 12.892 -> 4.9

 42%|████▏     | 156/375 [05:03<07:03,  1.93s/it]

====================================================================================================
[156/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCCCCC
Component 2 SMILES: C1=CC=C(C=C1)O
Operating temperature: 393.15 K
Liquid-phase mole fraction of component 1: 0.047
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.375
Equilibrium pressure: 20.769 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.059
Equilibrium pressure: 5.095 kPa

Parsed:
Y1 : 0.375 -> 0.059
P  : 20.769 -> 5.095

 42%|████▏     | 157/375 [05:05<06:59,  1.93s/it]

====================================================================================================
[157/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCCCCC
Component 2 SMILES: C1=CC=C(C=C1)O
Operating temperature: 393.15 K
Liquid-phase mole fraction of component 1: 0.080
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.445
Equilibrium pressure: 23.018 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.089
Equilibrium pressure: 6.900 kPa

Parsed:
Y1 : 0.445 -> 0.089
P  : 23.018 -> 6.9

 42%|████▏     | 158/375 [05:07<06:56,  1.92s/it]

====================================================================================================
[158/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCCCCC
Component 2 SMILES: C1=CC=C(C=C1)O
Operating temperature: 393.15 K
Liquid-phase mole fraction of component 1: 0.146
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.525
Equilibrium pressure: 25.449 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.098
Equilibrium pressure: 6.900 kPa

Parsed:
Y1 : 0.525 -> 0.098
P  : 25.449 -> 6.9

 42%|████▏     | 159/375 [05:09<06:53,  1.91s/it]

====================================================================================================
[159/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCCCCC
Component 2 SMILES: C1=CC=C(C=C1)O
Operating temperature: 393.15 K
Liquid-phase mole fraction of component 1: 0.238
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.559
Equilibrium pressure: 26.507 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.133
Equilibrium pressure: 5.000 kPa

Parsed:
Y1 : 0.559 -> 0.133
P  : 26.507 -> 5.0

 43%|████▎     | 160/375 [05:11<06:50,  1.91s/it]

====================================================================================================
[160/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCCCCC
Component 2 SMILES: C1=CC=C(C=C1)O
Operating temperature: 393.15 K
Liquid-phase mole fraction of component 1: 0.342
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.579
Equilibrium pressure: 27.058 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.182
Equilibrium pressure: 6.905 kPa

Parsed:
Y1 : 0.579 -> 0.182
P  : 27.058 -> 6.905

 43%|████▎     | 161/375 [05:13<06:48,  1.91s/it]

====================================================================================================
[161/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCCCCC
Component 2 SMILES: C1=CC=C(C=C1)O
Operating temperature: 393.15 K
Liquid-phase mole fraction of component 1: 0.467
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.581
Equilibrium pressure: 27.248 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.233
Equilibrium pressure: 5.905 kPa

Parsed:
Y1 : 0.581 -> 0.233
P  : 27.248 -> 5.905

 43%|████▎     | 162/375 [05:15<06:45,  1.91s/it]

====================================================================================================
[162/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCCCCC
Component 2 SMILES: C1=CC=C(C=C1)O
Operating temperature: 393.15 K
Liquid-phase mole fraction of component 1: 0.612
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.605
Equilibrium pressure: 27.308 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.333
Equilibrium pressure: 5.900 kPa

Parsed:
Y1 : 0.605 -> 0.333
P  : 27.308 -> 5.9

 43%|████▎     | 163/375 [05:17<06:44,  1.91s/it]

====================================================================================================
[163/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCCCCC
Component 2 SMILES: C1=CC=C(C=C1)O
Operating temperature: 393.15 K
Liquid-phase mole fraction of component 1: 0.693
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.624
Equilibrium pressure: 27.123 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.393
Equilibrium pressure: 4.900 kPa

Parsed:
Y1 : 0.624 -> 0.393
P  : 27.123 -> 4.9

 44%|████▎     | 164/375 [05:19<06:42,  1.91s/it]

====================================================================================================
[164/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCCCCC
Component 2 SMILES: C1=CC=C(C=C1)O
Operating temperature: 393.15 K
Liquid-phase mole fraction of component 1: 0.752
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.642
Equilibrium pressure: 26.903 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.503
Equilibrium pressure: 5.000 kPa

Parsed:
Y1 : 0.642 -> 0.503
P  : 26.903 -> 5.0

 44%|████▍     | 165/375 [05:21<06:40,  1.91s/it]

====================================================================================================
[165/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCCCCC
Component 2 SMILES: C1=CC=C(C=C1)O
Operating temperature: 393.15 K
Liquid-phase mole fraction of component 1: 0.791
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.660
Equilibrium pressure: 26.698 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.503
Equilibrium pressure: 4.905 kPa

Parsed:
Y1 : 0.66 -> 0.503
P  : 26.698 -> 4.905

 44%|████▍     | 166/375 [05:22<06:38,  1.91s/it]

====================================================================================================
[166/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCCCCC
Component 2 SMILES: C1=CC=C(C=C1)O
Operating temperature: 393.15 K
Liquid-phase mole fraction of component 1: 0.856
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.697
Equilibrium pressure: 26.033 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.662
Equilibrium pressure: 4.305 kPa

Parsed:
Y1 : 0.697 -> 0.662
P  : 26.033 -> 4.305

 45%|████▍     | 167/375 [05:24<06:36,  1.91s/it]

====================================================================================================
[167/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCCCCC
Component 2 SMILES: C1=CC=C(C=C1)O
Operating temperature: 393.15 K
Liquid-phase mole fraction of component 1: 0.904
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.743
Equilibrium pressure: 25.225 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.781
Equilibrium pressure: 3.900 kPa

Parsed:
Y1 : 0.743 -> 0.781
P  : 25.225 -> 3.9

 45%|████▍     | 168/375 [05:26<06:34,  1.91s/it]

====================================================================================================
[168/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCCCCC
Component 2 SMILES: C1=CC=C(C=C1)O
Operating temperature: 393.15 K
Liquid-phase mole fraction of component 1: 0.942
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.805
Equilibrium pressure: 24.165 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.863
Equilibrium pressure: 3.300 kPa

Parsed:
Y1 : 0.805 -> 0.863
P  : 24.165 -> 3.3

 45%|████▌     | 169/375 [05:28<06:32,  1.91s/it]

====================================================================================================
[169/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCCCCC
Component 2 SMILES: C1=CC=C(C=C1)O
Operating temperature: 393.15 K
Liquid-phase mole fraction of component 1: 0.967
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.872
Equilibrium pressure: 22.725 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.929
Equilibrium pressure: 3.000 kPa

Parsed:
Y1 : 0.872 -> 0.929
P  : 22.725 -> 3.0

 45%|████▌     | 170/375 [05:30<06:30,  1.90s/it]

====================================================================================================
[170/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCCCCC
Component 2 SMILES: C1=CC=C(C=C1)O
Operating temperature: 393.15 K
Liquid-phase mole fraction of component 1: 0.988
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.945
Equilibrium pressure: 21.198 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.979
Equilibrium pressure: 3.000 kPa

Parsed:
Y1 : 0.945 -> 0.979
P  : 21.198 -> 3.0

 46%|████▌     | 171/375 [05:32<06:29,  1.91s/it]

====================================================================================================
[171/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCCCCCCCC
Component 2 SMILES: C1=CC=C(C=C1)O
Operating temperature: 393.15 K
Liquid-phase mole fraction of component 1: 1.000
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 1.000
Equilibrium pressure: 20.078 kPa

Prediction:
Vapor-phase mole fraction of component 1: 1.000
Equilibrium pressure: 0.900 kPa

Parsed:
Y1 : 1.0 -> 1.0
P  : 20.078 -> 0.9

 46%|████▌     | 172/375 [05:34<06:26,  1.91s/it]

====================================================================================================
[172/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: CC1=CC=CC=C1
Operating temperature: 318.15 K
Liquid-phase mole fraction of component 1: 0.000
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.000
Equilibrium pressure: 10.053 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.000
Equilibrium pressure: 6.890 kPa

Parsed:
Y1 : 0.0 -> 0.0
P  : 10.053 -> 6.89

 46%|████▌     | 173/375 [05:36<06:24,  1.91s/it]

====================================================================================================
[173/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: CC1=CC=CC=C1
Operating temperature: 318.15 K
Liquid-phase mole fraction of component 1: 0.005
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.119
Equilibrium pressure: 10.959 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.133
Equilibrium pressure: 9.090 kPa

Parsed:
Y1 : 0.119 -> 0.133
P  : 10.959 -> 9.09

 46%|████▋     | 174/375 [05:38<06:26,  1.92s/it]

====================================================================================================
[174/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: CC1=CC=CC=C1
Operating temperature: 318.15 K
Liquid-phase mole fraction of component 1: 0.010
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.204
Equilibrium pressure: 12.532 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.253
Equilibrium pressure: 10.090 kPa

Parsed:
Y1 : 0.204 -> 0.253
P  : 12.532 -> 10.09

 47%|████▋     | 175/375 [05:40<06:27,  1.94s/it]

====================================================================================================
[175/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: CC1=CC=CC=C1
Operating temperature: 318.15 K
Liquid-phase mole fraction of component 1: 0.015
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.268
Equilibrium pressure: 13.572 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.262
Equilibrium pressure: 10.090 kPa

Parsed:
Y1 : 0.268 -> 0.262
P  : 13.572 -> 10.09

 47%|████▋     | 176/375 [05:42<06:27,  1.95s/it]

====================================================================================================
[176/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: CC1=CC=CC=C1
Operating temperature: 318.15 K
Liquid-phase mole fraction of component 1: 0.020
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.318
Equilibrium pressure: 14.505 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.393
Equilibrium pressure: 11.000 kPa

Parsed:
Y1 : 0.318 -> 0.393
P  : 14.505 -> 11.0

 47%|████▋     | 177/375 [05:44<06:26,  1.95s/it]

====================================================================================================
[177/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: CC1=CC=CC=C1
Operating temperature: 318.15 K
Liquid-phase mole fraction of component 1: 0.040
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.438
Equilibrium pressure: 17.345 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.432
Equilibrium pressure: 12.906 kPa

Parsed:
Y1 : 0.438 -> 0.432
P  : 17.345 -> 12.906

 47%|████▋     | 178/375 [05:46<06:24,  1.95s/it]

====================================================================================================
[178/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: CC1=CC=CC=C1
Operating temperature: 318.15 K
Liquid-phase mole fraction of component 1: 0.060
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.497
Equilibrium pressure: 19.185 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.523
Equilibrium pressure: 13.900 kPa

Parsed:
Y1 : 0.497 -> 0.523
P  : 19.185 -> 13.9

 48%|████▊     | 179/375 [05:48<06:23,  1.96s/it]

====================================================================================================
[179/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: CC1=CC=CC=C1
Operating temperature: 318.15 K
Liquid-phase mole fraction of component 1: 0.080
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.532
Equilibrium pressure: 20.418 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.533
Equilibrium pressure: 13.930 kPa

Parsed:
Y1 : 0.532 -> 0.533
P  : 20.418 -> 13.93

 48%|████▊     | 180/375 [05:50<06:21,  1.96s/it]

====================================================================================================
[180/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: CC1=CC=CC=C1
Operating temperature: 318.15 K
Liquid-phase mole fraction of component 1: 0.100
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.555
Equilibrium pressure: 21.278 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.582
Equilibrium pressure: 16.396 kPa

Parsed:
Y1 : 0.555 -> 0.582
P  : 21.278 -> 16.396

 48%|████▊     | 181/375 [05:52<06:19,  1.96s/it]

====================================================================================================
[181/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: CC1=CC=CC=C1
Operating temperature: 318.15 K
Liquid-phase mole fraction of component 1: 0.150
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.588
Equilibrium pressure: 22.605 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.592
Equilibrium pressure: 17.906 kPa

Parsed:
Y1 : 0.588 -> 0.592
P  : 22.605 -> 17.906

 49%|████▊     | 182/375 [05:54<06:18,  1.96s/it]

====================================================================================================
[182/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: CC1=CC=CC=C1
Operating temperature: 318.15 K
Liquid-phase mole fraction of component 1: 0.200
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.608
Equilibrium pressure: 23.425 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.610
Equilibrium pressure: 18.390 kPa

Parsed:
Y1 : 0.608 -> 0.61
P  : 23.425 -> 18.39

 49%|████▉     | 183/375 [05:55<06:16,  1.96s/it]

====================================================================================================
[183/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: CC1=CC=CC=C1
Operating temperature: 318.15 K
Liquid-phase mole fraction of component 1: 0.300
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.634
Equilibrium pressure: 24.411 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.622
Equilibrium pressure: 20.900 kPa

Parsed:
Y1 : 0.634 -> 0.622
P  : 24.411 -> 20.9

 49%|████▉     | 184/375 [05:57<06:15,  1.96s/it]

====================================================================================================
[184/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: CC1=CC=CC=C1
Operating temperature: 318.15 K
Liquid-phase mole fraction of component 1: 0.400
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.653
Equilibrium pressure: 25.038 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.662
Equilibrium pressure: 20.900 kPa

Parsed:
Y1 : 0.653 -> 0.662
P  : 25.038 -> 20.9

 49%|████▉     | 185/375 [05:59<06:13,  1.96s/it]

====================================================================================================
[185/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: CC1=CC=CC=C1
Operating temperature: 318.15 K
Liquid-phase mole fraction of component 1: 0.500
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.672
Equilibrium pressure: 25.505 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.680
Equilibrium pressure: 23.090 kPa

Parsed:
Y1 : 0.672 -> 0.68
P  : 25.505 -> 23.09

 50%|████▉     | 186/375 [06:01<06:10,  1.96s/it]

====================================================================================================
[186/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: CC1=CC=CC=C1
Operating temperature: 318.15 K
Liquid-phase mole fraction of component 1: 0.600
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.693
Equilibrium pressure: 25.818 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.723
Equilibrium pressure: 23.190 kPa

Parsed:
Y1 : 0.693 -> 0.723
P  : 25.818 -> 23.19

 50%|████▉     | 187/375 [06:03<06:09,  1.97s/it]

====================================================================================================
[187/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: CC1=CC=CC=C1
Operating temperature: 318.15 K
Liquid-phase mole fraction of component 1: 0.700
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.719
Equilibrium pressure: 25.985 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.752
Equilibrium pressure: 24.090 kPa

Parsed:
Y1 : 0.719 -> 0.752
P  : 25.985 -> 24.09

 50%|█████     | 188/375 [06:05<06:07,  1.97s/it]

====================================================================================================
[188/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: CC1=CC=CC=C1
Operating temperature: 318.15 K
Liquid-phase mole fraction of component 1: 0.800
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.761
Equilibrium pressure: 25.905 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.783
Equilibrium pressure: 24.090 kPa

Parsed:
Y1 : 0.761 -> 0.783
P  : 25.905 -> 24.09

 50%|█████     | 189/375 [06:07<06:05,  1.97s/it]

====================================================================================================
[189/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: CC1=CC=CC=C1
Operating temperature: 318.15 K
Liquid-phase mole fraction of component 1: 0.850
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.794
Equilibrium pressure: 25.671 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.813
Equilibrium pressure: 23.390 kPa

Parsed:
Y1 : 0.794 -> 0.813
P  : 25.671 -> 23.39

 51%|█████     | 190/375 [06:09<06:04,  1.97s/it]

====================================================================================================
[190/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: CC1=CC=CC=C1
Operating temperature: 318.15 K
Liquid-phase mole fraction of component 1: 0.900
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.838
Equilibrium pressure: 25.211 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.843
Equilibrium pressure: 23.390 kPa

Parsed:
Y1 : 0.838 -> 0.843
P  : 25.211 -> 23.39

 51%|█████     | 191/375 [06:11<06:01,  1.97s/it]

====================================================================================================
[191/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: CC1=CC=CC=C1
Operating temperature: 318.15 K
Liquid-phase mole fraction of component 1: 0.950
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.902
Equilibrium pressure: 24.398 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.900
Equilibrium pressure: 23.000 kPa

Parsed:
Y1 : 0.902 -> 0.9
P  : 24.398 -> 23.0

 51%|█████     | 192/375 [06:13<06:00,  1.97s/it]

====================================================================================================
[192/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCO
Component 2 SMILES: CC1=CC=CC=C1
Operating temperature: 318.15 K
Liquid-phase mole fraction of component 1: 1.000
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 1.000
Equilibrium pressure: 23.058 kPa

Prediction:
Vapor-phase mole fraction of component 1: 1.000
Equilibrium pressure: 24.400 kPa

Parsed:
Y1 : 1.0 -> 1.0
P  : 23.058 -> 24.4

 51%|█████▏    | 193/375 [06:15<05:54,  1.95s/it]

====================================================================================================
[193/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCCCCC
Operating temperature: 303.15 K
Liquid-phase mole fraction of component 1: 0.000
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.000
Equilibrium pressure: 7.822 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.000
Equilibrium pressure: 8.330 kPa

Parsed:
Y1 : 0.0 -> 0.0
P  : 7.822 -> 8.33

 52%|█████▏    | 194/375 [06:17<05:50,  1.93s/it]

====================================================================================================
[194/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCCCCC
Operating temperature: 303.15 K
Liquid-phase mole fraction of component 1: 0.005
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.079
Equilibrium pressure: 8.465 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.093
Equilibrium pressure: 7.890 kPa

Parsed:
Y1 : 0.079 -> 0.093
P  : 8.465 -> 7.89

 52%|█████▏    | 195/375 [06:19<05:47,  1.93s/it]

====================================================================================================
[195/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCCCCC
Operating temperature: 303.15 K
Liquid-phase mole fraction of component 1: 0.010
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.125
Equilibrium pressure: 8.878 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.122
Equilibrium pressure: 8.890 kPa

Parsed:
Y1 : 0.125 -> 0.122
P  : 8.878 -> 8.89

 52%|█████▏    | 196/375 [06:21<05:43,  1.92s/it]

====================================================================================================
[196/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCCCCC
Operating temperature: 303.15 K
Liquid-phase mole fraction of component 1: 0.020
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.166
Equilibrium pressure: 9.274 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.150
Equilibrium pressure: 9.396 kPa

Parsed:
Y1 : 0.166 -> 0.15
P  : 9.274 -> 9.396

 53%|█████▎    | 197/375 [06:23<05:41,  1.92s/it]

====================================================================================================
[197/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCCCCC
Operating temperature: 303.15 K
Liquid-phase mole fraction of component 1: 0.040
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.199
Equilibrium pressure: 9.602 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.163
Equilibrium pressure: 9.890 kPa

Parsed:
Y1 : 0.199 -> 0.163
P  : 9.602 -> 9.89

 53%|█████▎    | 198/375 [06:25<05:42,  1.93s/it]

====================================================================================================
[198/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCCCCC
Operating temperature: 303.15 K
Liquid-phase mole fraction of component 1: 0.100
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.238
Equilibrium pressure: 9.950 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.283
Equilibrium pressure: 10.090 kPa

Parsed:
Y1 : 0.238 -> 0.283
P  : 9.95 -> 10.09

 53%|█████▎    | 199/375 [06:27<05:41,  1.94s/it]

====================================================================================================
[199/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCCCCC
Operating temperature: 303.15 K
Liquid-phase mole fraction of component 1: 0.200
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.270
Equilibrium pressure: 10.138 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.302
Equilibrium pressure: 11.092 kPa

Parsed:
Y1 : 0.27 -> 0.302
P  : 10.138 -> 11.092

 53%|█████▎    | 200/375 [06:29<05:41,  1.95s/it]

====================================================================================================
[200/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCCCCC
Operating temperature: 303.15 K
Liquid-phase mole fraction of component 1: 0.300
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.281
Equilibrium pressure: 10.150 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.338
Equilibrium pressure: 11.096 kPa

Parsed:
Y1 : 0.281 -> 0.338
P  : 10.15 -> 11.096

 54%|█████▎    | 201/375 [06:31<05:40,  1.95s/it]

====================================================================================================
[201/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCCCCC
Operating temperature: 303.15 K
Liquid-phase mole fraction of component 1: 0.400
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.296
Equilibrium pressure: 10.107 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.338
Equilibrium pressure: 11.090 kPa

Parsed:
Y1 : 0.296 -> 0.338
P  : 10.107 -> 11.09

 54%|█████▍    | 202/375 [06:33<05:38,  1.96s/it]

====================================================================================================
[202/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCCCCC
Operating temperature: 303.15 K
Liquid-phase mole fraction of component 1: 0.500
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.308
Equilibrium pressure: 10.019 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.350
Equilibrium pressure: 11.090 kPa

Parsed:
Y1 : 0.308 -> 0.35
P  : 10.019 -> 11.09

 54%|█████▍    | 203/375 [06:34<05:36,  1.96s/it]

====================================================================================================
[203/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCCCCC
Operating temperature: 303.15 K
Liquid-phase mole fraction of component 1: 0.600
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.322
Equilibrium pressure: 9.861 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.382
Equilibrium pressure: 11.096 kPa

Parsed:
Y1 : 0.322 -> 0.382
P  : 9.861 -> 11.096

 54%|█████▍    | 204/375 [06:36<05:34,  1.96s/it]

====================================================================================================
[204/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCCCCC
Operating temperature: 303.15 K
Liquid-phase mole fraction of component 1: 0.700
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.343
Equilibrium pressure: 9.574 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.422
Equilibrium pressure: 10.390 kPa

Parsed:
Y1 : 0.343 -> 0.422
P  : 9.574 -> 10.39

 55%|█████▍    | 205/375 [06:38<05:30,  1.94s/it]

====================================================================================================
[205/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCCCCC
Operating temperature: 303.15 K
Liquid-phase mole fraction of component 1: 0.800
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.382
Equilibrium pressure: 8.946 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.482
Equilibrium pressure: 9.592 kPa

Parsed:
Y1 : 0.382 -> 0.482
P  : 8.946 -> 9.592

 55%|█████▍    | 206/375 [06:40<05:26,  1.93s/it]

====================================================================================================
[206/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCCCCC
Operating temperature: 303.15 K
Liquid-phase mole fraction of component 1: 0.850
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.419
Equilibrium pressure: 8.377 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.493
Equilibrium pressure: 9.834 kPa

Parsed:
Y1 : 0.419 -> 0.493
P  : 8.377 -> 9.834

 55%|█████▌    | 207/375 [06:42<05:23,  1.92s/it]

====================================================================================================
[207/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCCCCC
Operating temperature: 303.15 K
Liquid-phase mole fraction of component 1: 0.900
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.482
Equilibrium pressure: 7.511 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.563
Equilibrium pressure: 8.906 kPa

Parsed:
Y1 : 0.482 -> 0.563
P  : 7.511 -> 8.906

 55%|█████▌    | 208/375 [06:44<05:20,  1.92s/it]

====================================================================================================
[208/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCCCCC
Operating temperature: 303.15 K
Liquid-phase mole fraction of component 1: 0.920
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.522
Equilibrium pressure: 7.034 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.593
Equilibrium pressure: 8.906 kPa

Parsed:
Y1 : 0.522 -> 0.593
P  : 7.034 -> 8.906

 56%|█████▌    | 209/375 [06:46<05:17,  1.91s/it]

====================================================================================================
[209/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCCCCC
Operating temperature: 303.15 K
Liquid-phase mole fraction of component 1: 0.940
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.577
Equilibrium pressure: 6.458 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.629
Equilibrium pressure: 8.906 kPa

Parsed:
Y1 : 0.577 -> 0.629
P  : 6.458 -> 8.906

 56%|█████▌    | 210/375 [06:48<05:15,  1.91s/it]

====================================================================================================
[210/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCCCCC
Operating temperature: 303.15 K
Liquid-phase mole fraction of component 1: 0.960
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.657
Equilibrium pressure: 5.769 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.693
Equilibrium pressure: 7.900 kPa

Parsed:
Y1 : 0.657 -> 0.693
P  : 5.769 -> 7.9

 56%|█████▋    | 211/375 [06:50<05:13,  1.91s/it]

====================================================================================================
[211/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCCCCC
Operating temperature: 303.15 K
Liquid-phase mole fraction of component 1: 0.980
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.781
Equilibrium pressure: 4.937 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.782
Equilibrium pressure: 6.890 kPa

Parsed:
Y1 : 0.781 -> 0.782
P  : 4.937 -> 6.89

 57%|█████▋    | 212/375 [06:52<05:10,  1.91s/it]

====================================================================================================
[212/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCCCCC
Operating temperature: 303.15 K
Liquid-phase mole fraction of component 1: 0.990
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.873
Equilibrium pressure: 4.456 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.860
Equilibrium pressure: 6.830 kPa

Parsed:
Y1 : 0.873 -> 0.86
P  : 4.456 -> 6.83

 57%|█████▋    | 213/375 [06:54<05:08,  1.91s/it]

====================================================================================================
[213/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCCCCC
Operating temperature: 303.15 K
Liquid-phase mole fraction of component 1: 1.000
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 1.000
Equilibrium pressure: 3.926 kPa

Prediction:
Vapor-phase mole fraction of component 1: 1.000
Equilibrium pressure: 5.800 kPa

Parsed:
Y1 : 1.0 -> 1.0
P  : 3.926 -> 5.8

 57%|█████▋    | 214/375 [06:56<05:09,  1.92s/it]

====================================================================================================
[214/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCCCCC
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.000
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.000
Equilibrium pressure: 28.134 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.000
Equilibrium pressure: 40.300 kPa

Parsed:
Y1 : 0.0 -> 0.0
P  : 28.134 -> 40.3

 57%|█████▋    | 215/375 [06:58<05:09,  1.93s/it]

====================================================================================================
[215/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCCCCC
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.005
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.056
Equilibrium pressure: 29.703 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.043
Equilibrium pressure: 36.130 kPa

Parsed:
Y1 : 0.056 -> 0.043
P  : 29.703 -> 36.13

 58%|█████▊    | 216/375 [06:59<05:09,  1.95s/it]

====================================================================================================
[216/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCCCCC
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.010
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.099
Equilibrium pressure: 31.019 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.080
Equilibrium pressure: 38.360 kPa

Parsed:
Y1 : 0.099 -> 0.08
P  : 31.019 -> 38.36

 58%|█████▊    | 217/375 [07:01<05:08,  1.95s/it]

====================================================================================================
[217/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCCCCC
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.020
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.162
Equilibrium pressure: 33.097 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.110
Equilibrium pressure: 37.330 kPa

Parsed:
Y1 : 0.162 -> 0.11
P  : 33.097 -> 37.33

 58%|█████▊    | 218/375 [07:03<05:07,  1.96s/it]

====================================================================================================
[218/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCCCCC
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.040
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.226
Equilibrium pressure: 35.476 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.150
Equilibrium pressure: 42.900 kPa

Parsed:
Y1 : 0.226 -> 0.15
P  : 35.476 -> 42.9

 58%|█████▊    | 219/375 [07:05<05:05,  1.96s/it]

====================================================================================================
[219/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCCCCC
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.100
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.289
Equilibrium pressure: 37.906 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.263
Equilibrium pressure: 46.390 kPa

Parsed:
Y1 : 0.289 -> 0.263
P  : 37.906 -> 46.39

 59%|█████▊    | 220/375 [07:07<05:03,  1.96s/it]

====================================================================================================
[220/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCCCCC
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.200
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.337
Equilibrium pressure: 39.435 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.303
Equilibrium pressure: 50.000 kPa

Parsed:
Y1 : 0.337 -> 0.303
P  : 39.435 -> 50.0

 59%|█████▉    | 221/375 [07:09<05:02,  1.96s/it]

====================================================================================================
[221/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCCCCC
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.300
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.357
Equilibrium pressure: 39.770 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.350
Equilibrium pressure: 51.000 kPa

Parsed:
Y1 : 0.357 -> 0.35
P  : 39.77 -> 51.0

 59%|█████▉    | 222/375 [07:11<05:00,  1.96s/it]

====================================================================================================
[222/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCCCCC
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.400
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.379
Equilibrium pressure: 39.845 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.350
Equilibrium pressure: 50.100 kPa

Parsed:
Y1 : 0.379 -> 0.35
P  : 39.845 -> 50.1

 59%|█████▉    | 223/375 [07:13<04:58,  1.96s/it]

====================================================================================================
[223/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCCCCC
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.500
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.397
Equilibrium pressure: 39.653 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.373
Equilibrium pressure: 50.000 kPa

Parsed:
Y1 : 0.397 -> 0.373
P  : 39.653 -> 50.0

 60%|█████▉    | 224/375 [07:15<04:56,  1.96s/it]

====================================================================================================
[224/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCCCCC
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.600
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.417
Equilibrium pressure: 39.174 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.400
Equilibrium pressure: 50.000 kPa

Parsed:
Y1 : 0.417 -> 0.4
P  : 39.174 -> 50.0

 60%|██████    | 225/375 [07:17<04:54,  1.96s/it]

====================================================================================================
[225/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCCCCC
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.700
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.443
Equilibrium pressure: 38.245 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.423
Equilibrium pressure: 45.000 kPa

Parsed:
Y1 : 0.443 -> 0.423
P  : 38.245 -> 45.0

 60%|██████    | 226/375 [07:19<04:52,  1.96s/it]

====================================================================================================
[226/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCCCCC
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.800
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.489
Equilibrium pressure: 36.212 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.493
Equilibrium pressure: 40.900 kPa

Parsed:
Y1 : 0.489 -> 0.493
P  : 36.212 -> 40.9

 61%|██████    | 227/375 [07:21<04:50,  1.96s/it]

====================================================================================================
[227/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCCCCC
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.850
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.529
Equilibrium pressure: 34.388 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.500
Equilibrium pressure: 40.000 kPa

Parsed:
Y1 : 0.529 -> 0.5
P  : 34.388 -> 40.0

 61%|██████    | 228/375 [07:23<04:48,  1.96s/it]

====================================================================================================
[228/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCCCCC
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.900
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.594
Equilibrium pressure: 31.611 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.600
Equilibrium pressure: 37.330 kPa

Parsed:
Y1 : 0.594 -> 0.6
P  : 31.611 -> 37.33

 61%|██████    | 229/375 [07:25<04:46,  1.96s/it]

====================================================================================================
[229/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCCCCC
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.920
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.633
Equilibrium pressure: 30.094 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.643
Equilibrium pressure: 35.130 kPa

Parsed:
Y1 : 0.633 -> 0.643
P  : 30.094 -> 35.13

 61%|██████▏   | 230/375 [07:27<04:44,  1.96s/it]

====================================================================================================
[230/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCCCCC
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.940
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.684
Equilibrium pressure: 28.270 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.692
Equilibrium pressure: 34.390 kPa

Parsed:
Y1 : 0.684 -> 0.692
P  : 28.27 -> 34.39

 62%|██████▏   | 231/375 [07:29<04:41,  1.95s/it]

====================================================================================================
[231/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCCCCC
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.960
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.753
Equilibrium pressure: 26.091 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.763
Equilibrium pressure: 30.900 kPa

Parsed:
Y1 : 0.753 -> 0.763
P  : 26.091 -> 30.9

 62%|██████▏   | 232/375 [07:31<04:38,  1.95s/it]

====================================================================================================
[232/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCCCCC
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.980
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.851
Equilibrium pressure: 23.481 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.843
Equilibrium pressure: 28.330 kPa

Parsed:
Y1 : 0.851 -> 0.843
P  : 23.481 -> 28.33

 62%|██████▏   | 233/375 [07:33<04:35,  1.94s/it]

====================================================================================================
[233/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCCCCC
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.990
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.917
Equilibrium pressure: 21.974 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.929
Equilibrium pressure: 28.190 kPa

Parsed:
Y1 : 0.917 -> 0.929
P  : 21.974 -> 28.19

 62%|██████▏   | 234/375 [07:35<04:33,  1.94s/it]

====================================================================================================
[234/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCCO
Component 2 SMILES: CCCCCCC
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 1.000
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 1.000
Equilibrium pressure: 20.318 kPa

Prediction:
Vapor-phase mole fraction of component 1: 1.000
Equilibrium pressure: 28.200 kPa

Parsed:
Y1 : 1.0 -> 1.0
P  : 20.318 -> 28.2

 63%|██████▎   | 235/375 [07:37<04:31,  1.94s/it]

====================================================================================================
[235/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCCCC1
Component 2 SMILES: CCC(C)O
Operating temperature: 323.15 K
Liquid-phase mole fraction of component 1: 0.000
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.000
Equilibrium pressure: 11.060 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.000
Equilibrium pressure: 19.300 kPa

Parsed:
Y1 : 0.0 -> 0.0
P  : 11.06 -> 19.3

 63%|██████▎   | 236/375 [07:39<04:28,  1.93s/it]

====================================================================================================
[236/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCCCC1
Component 2 SMILES: CCC(C)O
Operating temperature: 323.15 K
Liquid-phase mole fraction of component 1: 0.056
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.244
Equilibrium pressure: 15.330 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.203
Equilibrium pressure: 28.100 kPa

Parsed:
Y1 : 0.244 -> 0.203
P  : 15.33 -> 28.1

 63%|██████▎   | 237/375 [07:41<04:26,  1.93s/it]

====================================================================================================
[237/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCCCC1
Component 2 SMILES: CCC(C)O
Operating temperature: 323.15 K
Liquid-phase mole fraction of component 1: 0.103
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.404
Equilibrium pressure: 18.830 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.329
Equilibrium pressure: 30.000 kPa

Parsed:
Y1 : 0.404 -> 0.329
P  : 18.83 -> 30.0

 63%|██████▎   | 238/375 [07:42<04:24,  1.93s/it]

====================================================================================================
[238/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCCCC1
Component 2 SMILES: CCC(C)O
Operating temperature: 323.15 K
Liquid-phase mole fraction of component 1: 0.198
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.645
Equilibrium pressure: 26.980 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.482
Equilibrium pressure: 34.090 kPa

Parsed:
Y1 : 0.645 -> 0.482
P  : 26.98 -> 34.09

 64%|██████▎   | 239/375 [07:44<04:22,  1.93s/it]

====================================================================================================
[239/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCCCC1
Component 2 SMILES: CCC(C)O
Operating temperature: 323.15 K
Liquid-phase mole fraction of component 1: 0.244
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.678
Equilibrium pressure: 28.790 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.529
Equilibrium pressure: 37.190 kPa

Parsed:
Y1 : 0.678 -> 0.529
P  : 28.79 -> 37.19

 64%|██████▍   | 240/375 [07:46<04:21,  1.93s/it]

====================================================================================================
[240/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCCCC1
Component 2 SMILES: CCC(C)O
Operating temperature: 323.15 K
Liquid-phase mole fraction of component 1: 0.287
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.712
Equilibrium pressure: 30.910 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.562
Equilibrium pressure: 38.190 kPa

Parsed:
Y1 : 0.712 -> 0.562
P  : 30.91 -> 38.19

 64%|██████▍   | 241/375 [07:48<04:18,  1.93s/it]

====================================================================================================
[241/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCCCC1
Component 2 SMILES: CCC(C)O
Operating temperature: 323.15 K
Liquid-phase mole fraction of component 1: 0.328
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.744
Equilibrium pressure: 33.400 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.592
Equilibrium pressure: 40.000 kPa

Parsed:
Y1 : 0.744 -> 0.592
P  : 33.4 -> 40.0

 65%|██████▍   | 242/375 [07:50<04:17,  1.93s/it]

====================================================================================================
[242/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCCCC1
Component 2 SMILES: CCC(C)O
Operating temperature: 323.15 K
Liquid-phase mole fraction of component 1: 0.367
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.755
Equilibrium pressure: 34.090 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.629
Equilibrium pressure: 41.100 kPa

Parsed:
Y1 : 0.755 -> 0.629
P  : 34.09 -> 41.1

 65%|██████▍   | 243/375 [07:52<04:14,  1.93s/it]

====================================================================================================
[243/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCCCC1
Component 2 SMILES: CCC(C)O
Operating temperature: 323.15 K
Liquid-phase mole fraction of component 1: 0.404
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.775
Equilibrium pressure: 35.490 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.643
Equilibrium pressure: 41.100 kPa

Parsed:
Y1 : 0.775 -> 0.643
P  : 35.49 -> 41.1

 65%|██████▌   | 244/375 [07:54<04:12,  1.93s/it]

====================================================================================================
[244/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCCCC1
Component 2 SMILES: CCC(C)O
Operating temperature: 323.15 K
Liquid-phase mole fraction of component 1: 0.441
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.785
Equilibrium pressure: 35.910 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.669
Equilibrium pressure: 41.000 kPa

Parsed:
Y1 : 0.785 -> 0.669
P  : 35.91 -> 41.0

 65%|██████▌   | 245/375 [07:56<04:10,  1.93s/it]

====================================================================================================
[245/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCCCC1
Component 2 SMILES: CCC(C)O
Operating temperature: 323.15 K
Liquid-phase mole fraction of component 1: 0.510
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.806
Equilibrium pressure: 37.130 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.682
Equilibrium pressure: 43.060 kPa

Parsed:
Y1 : 0.806 -> 0.682
P  : 37.13 -> 43.06

 66%|██████▌   | 246/375 [07:58<04:08,  1.93s/it]

====================================================================================================
[246/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCCCC1
Component 2 SMILES: CCC(C)O
Operating temperature: 323.15 K
Liquid-phase mole fraction of component 1: 0.545
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.817
Equilibrium pressure: 37.750 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.703
Equilibrium pressure: 44.090 kPa

Parsed:
Y1 : 0.817 -> 0.703
P  : 37.75 -> 44.09

 66%|██████▌   | 247/375 [08:00<04:07,  1.93s/it]

====================================================================================================
[247/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCCCC1
Component 2 SMILES: CCC(C)O
Operating temperature: 323.15 K
Liquid-phase mole fraction of component 1: 0.578
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.835
Equilibrium pressure: 38.120 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.713
Equilibrium pressure: 45.160 kPa

Parsed:
Y1 : 0.835 -> 0.713
P  : 38.12 -> 45.16

 66%|██████▌   | 248/375 [08:02<04:04,  1.93s/it]

====================================================================================================
[248/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCCCC1
Component 2 SMILES: CCC(C)O
Operating temperature: 323.15 K
Liquid-phase mole fraction of component 1: 0.712
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.862
Equilibrium pressure: 38.790 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.779
Equilibrium pressure: 48.190 kPa

Parsed:
Y1 : 0.862 -> 0.779
P  : 38.79 -> 48.19

 66%|██████▋   | 249/375 [08:04<04:02,  1.93s/it]

====================================================================================================
[249/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCCCC1
Component 2 SMILES: CCC(C)O
Operating temperature: 323.15 K
Liquid-phase mole fraction of component 1: 0.889
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.889
Equilibrium pressure: 39.490 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.862
Equilibrium pressure: 48.190 kPa

Parsed:
Y1 : 0.889 -> 0.862
P  : 39.49 -> 48.19

 67%|██████▋   | 250/375 [08:06<04:01,  1.93s/it]

====================================================================================================
[250/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCCCC1
Component 2 SMILES: CCC(C)O
Operating temperature: 323.15 K
Liquid-phase mole fraction of component 1: 0.964
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.914
Equilibrium pressure: 39.300 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.929
Equilibrium pressure: 44.190 kPa

Parsed:
Y1 : 0.914 -> 0.929
P  : 39.3 -> 44.19

 67%|██████▋   | 251/375 [08:08<03:59,  1.93s/it]

====================================================================================================
[251/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCCCC1
Component 2 SMILES: CCC(C)O
Operating temperature: 323.15 K
Liquid-phase mole fraction of component 1: 0.989
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.939
Equilibrium pressure: 37.820 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.979
Equilibrium pressure: 44.090 kPa

Parsed:
Y1 : 0.939 -> 0.979
P  : 37.82 -> 44.09

 67%|██████▋   | 252/375 [08:09<03:57,  1.93s/it]

====================================================================================================
[252/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCCCC1
Component 2 SMILES: CCC(C)O
Operating temperature: 323.15 K
Liquid-phase mole fraction of component 1: 1.000
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 1.000
Equilibrium pressure: 36.510 kPa

Prediction:
Vapor-phase mole fraction of component 1: 1.000
Equilibrium pressure: 44.000 kPa

Parsed:
Y1 : 1.0 -> 1.0
P  : 36.51 -> 44.0

 67%|██████▋   | 253/375 [08:11<03:55,  1.93s/it]

====================================================================================================
[253/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCC1CO1
Component 2 SMILES: CCCCCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.000
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.000
Equilibrium pressure: 12.303 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.000
Equilibrium pressure: 27.330 kPa

Parsed:
Y1 : 0.0 -> 0.0
P  : 12.303 -> 27.33

 68%|██████▊   | 254/375 [08:13<03:53,  1.93s/it]

====================================================================================================
[254/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCC1CO1
Component 2 SMILES: CCCCCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.037
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.203
Equilibrium pressure: 14.933 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.100
Equilibrium pressure: 27.900 kPa

Parsed:
Y1 : 0.203 -> 0.1
P  : 14.933 -> 27.9

 68%|██████▊   | 255/375 [08:15<03:51,  1.93s/it]

====================================================================================================
[255/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCC1CO1
Component 2 SMILES: CCCCCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.097
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.411
Equilibrium pressure: 19.077 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.209
Equilibrium pressure: 30.000 kPa

Parsed:
Y1 : 0.411 -> 0.209
P  : 19.077 -> 30.0

 68%|██████▊   | 256/375 [08:17<03:49,  1.93s/it]

====================================================================================================
[256/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCC1CO1
Component 2 SMILES: CCCCCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.156
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.523
Equilibrium pressure: 22.363 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.302
Equilibrium pressure: 31.900 kPa

Parsed:
Y1 : 0.523 -> 0.302
P  : 22.363 -> 31.9

 69%|██████▊   | 257/375 [08:19<03:47,  1.93s/it]

====================================================================================================
[257/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCC1CO1
Component 2 SMILES: CCCCCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.250
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.630
Equilibrium pressure: 26.611 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.382
Equilibrium pressure: 35.000 kPa

Parsed:
Y1 : 0.63 -> 0.382
P  : 26.611 -> 35.0

 69%|██████▉   | 258/375 [08:21<03:45,  1.93s/it]

====================================================================================================
[258/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCC1CO1
Component 2 SMILES: CCCCCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.345
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.703
Equilibrium pressure: 30.015 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.432
Equilibrium pressure: 38.160 kPa

Parsed:
Y1 : 0.703 -> 0.432
P  : 30.015 -> 38.16

 69%|██████▉   | 259/375 [08:23<03:43,  1.93s/it]

====================================================================================================
[259/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCC1CO1
Component 2 SMILES: CCCCCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.467
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.766
Equilibrium pressure: 33.613 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.490
Equilibrium pressure: 39.900 kPa

Parsed:
Y1 : 0.766 -> 0.49
P  : 33.613 -> 39.9

 69%|██████▉   | 260/375 [08:25<03:41,  1.93s/it]

====================================================================================================
[260/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCC1CO1
Component 2 SMILES: CCCCCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.589
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.814
Equilibrium pressure: 36.488 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.529
Equilibrium pressure: 38.900 kPa

Parsed:
Y1 : 0.814 -> 0.529
P  : 36.488 -> 38.9

 70%|██████▉   | 261/375 [08:27<03:40,  1.93s/it]

====================================================================================================
[261/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCC1CO1
Component 2 SMILES: CCCCCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.695
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.855
Equilibrium pressure: 40.366 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.582
Equilibrium pressure: 37.000 kPa

Parsed:
Y1 : 0.855 -> 0.582
P  : 40.366 -> 37.0

 70%|██████▉   | 262/375 [08:29<03:38,  1.93s/it]

====================================================================================================
[262/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCC1CO1
Component 2 SMILES: CCCCCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.791
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.893
Equilibrium pressure: 41.784 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.652
Equilibrium pressure: 35.000 kPa

Parsed:
Y1 : 0.893 -> 0.652
P  : 41.784 -> 35.0

 70%|███████   | 263/375 [08:31<03:36,  1.93s/it]

====================================================================================================
[263/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCC1CO1
Component 2 SMILES: CCCCCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.939
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.928
Equilibrium pressure: 42.706 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.852
Equilibrium pressure: 28.900 kPa

Parsed:
Y1 : 0.928 -> 0.852
P  : 42.706 -> 28.9

 70%|███████   | 264/375 [08:33<03:34,  1.93s/it]

====================================================================================================
[264/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCC1CO1
Component 2 SMILES: CCCCCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.978
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.961
Equilibrium pressure: 43.328 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.933
Equilibrium pressure: 27.900 kPa

Parsed:
Y1 : 0.961 -> 0.933
P  : 43.328 -> 27.9

 71%|███████   | 265/375 [08:35<03:32,  1.93s/it]

====================================================================================================
[265/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCC1CO1
Component 2 SMILES: CCCCCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 1.000
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 1.000
Equilibrium pressure: 43.624 kPa

Prediction:
Vapor-phase mole fraction of component 1: 1.000
Equilibrium pressure: 33.800 kPa

Parsed:
Y1 : 1.0 -> 1.0
P  : 43.624 -> 33.8

 71%|███████   | 266/375 [08:36<03:30,  1.93s/it]

====================================================================================================
[266/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCC1CO1
Component 2 SMILES: CCCCCCC
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.000
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.000
Equilibrium pressure: 28.077 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.000
Equilibrium pressure: 48.300 kPa

Parsed:
Y1 : 0.0 -> 0.0
P  : 28.077 -> 48.3

 71%|███████   | 267/375 [08:38<03:28,  1.93s/it]

====================================================================================================
[267/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCC1CO1
Component 2 SMILES: CCCCCCC
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.046
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.203
Equilibrium pressure: 34.118 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.120
Equilibrium pressure: 50.000 kPa

Parsed:
Y1 : 0.203 -> 0.12
P  : 34.118 -> 50.0

 71%|███████▏  | 268/375 [08:40<03:26,  1.93s/it]

====================================================================================================
[268/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCC1CO1
Component 2 SMILES: CCCCCCC
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.100
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.378
Equilibrium pressure: 41.006 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.250
Equilibrium pressure: 51.000 kPa

Parsed:
Y1 : 0.378 -> 0.25
P  : 41.006 -> 51.0

 72%|███████▏  | 269/375 [08:42<03:24,  1.93s/it]

====================================================================================================
[269/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCC1CO1
Component 2 SMILES: CCCCCCC
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.169
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.502
Equilibrium pressure: 48.085 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.293
Equilibrium pressure: 62.000 kPa

Parsed:
Y1 : 0.502 -> 0.293
P  : 48.085 -> 62.0

 72%|███████▏  | 270/375 [08:44<03:22,  1.93s/it]

====================================================================================================
[270/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCC1CO1
Component 2 SMILES: CCCCCCC
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.250
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.598
Equilibrium pressure: 55.347 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.350
Equilibrium pressure: 67.000 kPa

Parsed:
Y1 : 0.598 -> 0.35
P  : 55.347 -> 67.0

 72%|███████▏  | 271/375 [08:46<03:20,  1.93s/it]

====================================================================================================
[271/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCC1CO1
Component 2 SMILES: CCCCCCC
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.350
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.678
Equilibrium pressure: 62.629 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.429
Equilibrium pressure: 69.000 kPa

Parsed:
Y1 : 0.678 -> 0.429
P  : 62.629 -> 69.0

 73%|███████▎  | 272/375 [08:48<03:18,  1.93s/it]

====================================================================================================
[272/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCC1CO1
Component 2 SMILES: CCCCCCC
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.475
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.750
Equilibrium pressure: 69.985 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.492
Equilibrium pressure: 73.000 kPa

Parsed:
Y1 : 0.75 -> 0.492
P  : 69.985 -> 73.0

 73%|███████▎  | 273/375 [08:50<03:16,  1.93s/it]

====================================================================================================
[273/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCC1CO1
Component 2 SMILES: CCCCCCC
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.591
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.803
Equilibrium pressure: 75.787 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.528
Equilibrium pressure: 68.000 kPa

Parsed:
Y1 : 0.803 -> 0.528
P  : 75.787 -> 68.0

 73%|███████▎  | 274/375 [08:52<03:14,  1.93s/it]

====================================================================================================
[274/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCC1CO1
Component 2 SMILES: CCCCCCC
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.698
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.848
Equilibrium pressure: 80.300 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.583
Equilibrium pressure: 64.000 kPa

Parsed:
Y1 : 0.848 -> 0.583
P  : 80.3 -> 64.0

 73%|███████▎  | 275/375 [08:54<03:12,  1.93s/it]

====================================================================================================
[275/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCC1CO1
Component 2 SMILES: CCCCCCC
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.792
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.888
Equilibrium pressure: 83.850 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.633
Equilibrium pressure: 54.000 kPa

Parsed:
Y1 : 0.888 -> 0.633
P  : 83.85 -> 54.0

 74%|███████▎  | 276/375 [08:56<03:11,  1.93s/it]

====================================================================================================
[276/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCC1CO1
Component 2 SMILES: CCCCCCC
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.871
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.924
Equilibrium pressure: 86.527 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.742
Equilibrium pressure: 50.000 kPa

Parsed:
Y1 : 0.924 -> 0.742
P  : 86.527 -> 50.0

 74%|███████▍  | 277/375 [08:58<03:08,  1.93s/it]

====================================================================================================
[277/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCC1CO1
Component 2 SMILES: CCCCCCC
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.936
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.959
Equilibrium pressure: 88.773 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.832
Equilibrium pressure: 50.000 kPa

Parsed:
Y1 : 0.959 -> 0.832
P  : 88.773 -> 50.0

 74%|███████▍  | 278/375 [09:00<03:07,  1.93s/it]

====================================================================================================
[278/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCC1CO1
Component 2 SMILES: CCCCCCC
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.979
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.985
Equilibrium pressure: 90.195 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.929
Equilibrium pressure: 50.000 kPa

Parsed:
Y1 : 0.985 -> 0.929
P  : 90.195 -> 50.0

 74%|███████▍  | 279/375 [09:02<03:05,  1.93s/it]

====================================================================================================
[279/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCC1CO1
Component 2 SMILES: CCCCCCC
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 1.000
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 1.000
Equilibrium pressure: 90.718 kPa

Prediction:
Vapor-phase mole fraction of component 1: 1.000
Equilibrium pressure: 66.650 kPa

Parsed:
Y1 : 1.0 -> 1.0
P  : 90.718 -> 66.65

 75%|███████▍  | 280/375 [09:03<03:03,  1.93s/it]

====================================================================================================
[280/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCC1CO1
Component 2 SMILES: CCCCCCC=C
Operating temperature: 323.15 K
Liquid-phase mole fraction of component 1: 0.000
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.000
Equilibrium pressure: 8.080 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.000
Equilibrium pressure: 10.000 kPa

Parsed:
Y1 : 0.0 -> 0.0
P  : 8.08 -> 10.0

 75%|███████▍  | 281/375 [09:05<03:01,  1.93s/it]

====================================================================================================
[281/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCC1CO1
Component 2 SMILES: CCCCCCC=C
Operating temperature: 323.15 K
Liquid-phase mole fraction of component 1: 0.019
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.155
Equilibrium pressure: 9.455 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.103
Equilibrium pressure: 10.090 kPa

Parsed:
Y1 : 0.155 -> 0.103
P  : 9.455 -> 10.09

 75%|███████▌  | 282/375 [09:07<02:59,  1.93s/it]

====================================================================================================
[282/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCC1CO1
Component 2 SMILES: CCCCCCC=C
Operating temperature: 323.15 K
Liquid-phase mole fraction of component 1: 0.054
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.386
Equilibrium pressure: 12.665 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.332
Equilibrium pressure: 12.035 kPa

Parsed:
Y1 : 0.386 -> 0.332
P  : 12.665 -> 12.035

 75%|███████▌  | 283/375 [09:09<02:57,  1.93s/it]

====================================================================================================
[283/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCC1CO1
Component 2 SMILES: CCCCCCC=C
Operating temperature: 323.15 K
Liquid-phase mole fraction of component 1: 0.066
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.441
Equilibrium pressure: 13.631 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.392
Equilibrium pressure: 11.320 kPa

Parsed:
Y1 : 0.441 -> 0.392
P  : 13.631 -> 11.32

 76%|███████▌  | 284/375 [09:11<02:55,  1.93s/it]

====================================================================================================
[284/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCC1CO1
Component 2 SMILES: CCCCCCC=C
Operating temperature: 323.15 K
Liquid-phase mole fraction of component 1: 0.099
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.550
Equilibrium pressure: 16.355 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.508
Equilibrium pressure: 12.900 kPa

Parsed:
Y1 : 0.55 -> 0.508
P  : 16.355 -> 12.9

 76%|███████▌  | 285/375 [09:13<02:53,  1.93s/it]

====================================================================================================
[285/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCC1CO1
Component 2 SMILES: CCCCCCC=C
Operating temperature: 323.15 K
Liquid-phase mole fraction of component 1: 0.134
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.627
Equilibrium pressure: 18.935 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.692
Equilibrium pressure: 15.900 kPa

Parsed:
Y1 : 0.627 -> 0.692
P  : 18.935 -> 15.9

 76%|███████▋  | 286/375 [09:15<02:51,  1.93s/it]

====================================================================================================
[286/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCC1CO1
Component 2 SMILES: CCCCCCC=C
Operating temperature: 323.15 K
Liquid-phase mole fraction of component 1: 0.229
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.749
Equilibrium pressure: 25.611 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.803
Equilibrium pressure: 25.030 kPa

Parsed:
Y1 : 0.749 -> 0.803
P  : 25.611 -> 25.03

 77%|███████▋  | 287/375 [09:17<02:49,  1.93s/it]

====================================================================================================
[287/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCC1CO1
Component 2 SMILES: CCCCCCC=C
Operating temperature: 323.15 K
Liquid-phase mole fraction of component 1: 0.295
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.800
Equilibrium pressure: 29.710 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.823
Equilibrium pressure: 28.300 kPa

Parsed:
Y1 : 0.8 -> 0.823
P  : 29.71 -> 28.3

 77%|███████▋  | 288/375 [09:19<02:47,  1.93s/it]

====================================================================================================
[288/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCC1CO1
Component 2 SMILES: CCCCCCC=C
Operating temperature: 323.15 K
Liquid-phase mole fraction of component 1: 0.421
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.862
Equilibrium pressure: 36.803 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.893
Equilibrium pressure: 32.090 kPa

Parsed:
Y1 : 0.862 -> 0.893
P  : 36.803 -> 32.09

 77%|███████▋  | 289/375 [09:21<02:45,  1.93s/it]

====================================================================================================
[289/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCC1CO1
Component 2 SMILES: CCCCCCC=C
Operating temperature: 323.15 K
Liquid-phase mole fraction of component 1: 0.516
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.894
Equilibrium pressure: 41.520 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.929
Equilibrium pressure: 35.060 kPa

Parsed:
Y1 : 0.894 -> 0.929
P  : 41.52 -> 35.06

 77%|███████▋  | 290/375 [09:23<02:44,  1.93s/it]

====================================================================================================
[290/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCC1CO1
Component 2 SMILES: CCCCCCC=C
Operating temperature: 323.15 K
Liquid-phase mole fraction of component 1: 0.611
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.919
Equilibrium pressure: 45.986 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.969
Equilibrium pressure: 39.000 kPa

Parsed:
Y1 : 0.919 -> 0.969
P  : 45.986 -> 39.0

 78%|███████▊  | 291/375 [09:25<02:42,  1.93s/it]

====================================================================================================
[291/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCC1CO1
Component 2 SMILES: CCCCCCC=C
Operating temperature: 323.15 K
Liquid-phase mole fraction of component 1: 0.786
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.957
Equilibrium pressure: 53.783 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.959
Equilibrium pressure: 44.090 kPa

Parsed:
Y1 : 0.957 -> 0.959
P  : 53.783 -> 44.09

 78%|███████▊  | 292/375 [09:27<02:40,  1.93s/it]

====================================================================================================
[292/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCC1CO1
Component 2 SMILES: CCCCCCC=C
Operating temperature: 323.15 K
Liquid-phase mole fraction of component 1: 0.851
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.968
Equilibrium pressure: 56.649 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.973
Equilibrium pressure: 44.030 kPa

Parsed:
Y1 : 0.968 -> 0.973
P  : 56.649 -> 44.03

 78%|███████▊  | 293/375 [09:29<02:38,  1.93s/it]

====================================================================================================
[293/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCC1CO1
Component 2 SMILES: CCCCCCC=C
Operating temperature: 323.15 K
Liquid-phase mole fraction of component 1: 0.912
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.980
Equilibrium pressure: 59.534 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.979
Equilibrium pressure: 50.000 kPa

Parsed:
Y1 : 0.98 -> 0.979
P  : 59.534 -> 50.0

 78%|███████▊  | 294/375 [09:30<02:36,  1.93s/it]

====================================================================================================
[294/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CCC1CO1
Component 2 SMILES: CCCCCCC=C
Operating temperature: 323.15 K
Liquid-phase mole fraction of component 1: 1.000
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 1.000
Equilibrium pressure: 64.108 kPa

Prediction:
Vapor-phase mole fraction of component 1: 1.000
Equilibrium pressure: 48.200 kPa

Parsed:
Y1 : 1.0 -> 1.0
P  : 64.108 -> 48.2

 79%|███████▊  | 295/375 [09:32<02:34,  1.93s/it]

====================================================================================================
[295/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCOC1
Component 2 SMILES: CCCCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.000
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.000
Equilibrium pressure: 37.220 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.000
Equilibrium pressure: 23.390 kPa

Parsed:
Y1 : 0.0 -> 0.0
P  : 37.22 -> 23.39

 79%|███████▉  | 296/375 [09:34<02:32,  1.93s/it]

====================================================================================================
[296/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCOC1
Component 2 SMILES: CCCCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.011
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.019
Equilibrium pressure: 37.624 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.039
Equilibrium pressure: 26.390 kPa

Parsed:
Y1 : 0.019 -> 0.039
P  : 37.624 -> 26.39

 79%|███████▉  | 297/375 [09:36<02:30,  1.93s/it]

====================================================================================================
[297/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCOC1
Component 2 SMILES: CCCCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.046
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.079
Equilibrium pressure: 38.780 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.109
Equilibrium pressure: 27.900 kPa

Parsed:
Y1 : 0.079 -> 0.109
P  : 38.78 -> 27.9

 79%|███████▉  | 298/375 [09:38<02:28,  1.93s/it]

====================================================================================================
[298/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCOC1
Component 2 SMILES: CCCCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.097
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.154
Equilibrium pressure: 40.171 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.283
Equilibrium pressure: 24.900 kPa

Parsed:
Y1 : 0.154 -> 0.283
P  : 40.171 -> 24.9

 80%|███████▉  | 299/375 [09:40<02:26,  1.93s/it]

====================================================================================================
[299/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCOC1
Component 2 SMILES: CCCCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.166
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.240
Equilibrium pressure: 41.725 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.382
Equilibrium pressure: 27.900 kPa

Parsed:
Y1 : 0.24 -> 0.382
P  : 41.725 -> 27.9

 80%|████████  | 300/375 [09:42<02:24,  1.93s/it]

====================================================================================================
[300/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCOC1
Component 2 SMILES: CCCCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.247
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.323
Equilibrium pressure: 43.040 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.482
Equilibrium pressure: 30.900 kPa

Parsed:
Y1 : 0.323 -> 0.482
P  : 43.04 -> 30.9

 80%|████████  | 301/375 [09:44<02:22,  1.93s/it]

====================================================================================================
[301/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCOC1
Component 2 SMILES: CCCCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.346
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.409
Equilibrium pressure: 44.076 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.592
Equilibrium pressure: 31.800 kPa

Parsed:
Y1 : 0.409 -> 0.592
P  : 44.076 -> 31.8

 81%|████████  | 302/375 [09:46<02:20,  1.93s/it]

====================================================================================================
[302/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCOC1
Component 2 SMILES: CCCCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.425
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.469
Equilibrium pressure: 44.670 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.608
Equilibrium pressure: 35.000 kPa

Parsed:
Y1 : 0.469 -> 0.608
P  : 44.67 -> 35.0

 81%|████████  | 303/375 [09:48<02:18,  1.93s/it]

====================================================================================================
[303/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCOC1
Component 2 SMILES: CCCCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.497
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.522
Equilibrium pressure: 45.020 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.692
Equilibrium pressure: 36.150 kPa

Parsed:
Y1 : 0.522 -> 0.692
P  : 45.02 -> 36.15

 81%|████████  | 304/375 [09:50<02:17,  1.93s/it]

====================================================================================================
[304/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCOC1
Component 2 SMILES: CCCCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.620
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.611
Equilibrium pressure: 45.113 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.749
Equilibrium pressure: 38.900 kPa

Parsed:
Y1 : 0.611 -> 0.749
P  : 45.113 -> 38.9

 81%|████████▏ | 305/375 [09:52<02:15,  1.93s/it]

====================================================================================================
[305/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCOC1
Component 2 SMILES: CCCCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.711
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.677
Equilibrium pressure: 44.830 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.792
Equilibrium pressure: 39.900 kPa

Parsed:
Y1 : 0.677 -> 0.792
P  : 44.83 -> 39.9

 82%|████████▏ | 306/375 [09:54<02:13,  1.93s/it]

====================================================================================================
[306/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCOC1
Component 2 SMILES: CCCCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.792
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.745
Equilibrium pressure: 44.282 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.829
Equilibrium pressure: 39.900 kPa

Parsed:
Y1 : 0.745 -> 0.829
P  : 44.282 -> 39.9

 82%|████████▏ | 307/375 [09:56<02:11,  1.93s/it]

====================================================================================================
[307/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCOC1
Component 2 SMILES: CCCCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.847
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.798
Equilibrium pressure: 43.625 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.872
Equilibrium pressure: 40.000 kPa

Parsed:
Y1 : 0.798 -> 0.872
P  : 43.625 -> 40.0

 82%|████████▏ | 308/375 [09:58<02:10,  1.94s/it]

====================================================================================================
[308/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCOC1
Component 2 SMILES: CCCCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.908
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.866
Equilibrium pressure: 42.705 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.900
Equilibrium pressure: 39.000 kPa

Parsed:
Y1 : 0.866 -> 0.9
P  : 42.705 -> 39.0

 82%|████████▏ | 309/375 [10:00<02:08,  1.95s/it]

====================================================================================================
[309/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCOC1
Component 2 SMILES: CCCCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.948
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.920
Equilibrium pressure: 41.770 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.929
Equilibrium pressure: 39.900 kPa

Parsed:
Y1 : 0.92 -> 0.929
P  : 41.77 -> 39.9

 83%|████████▎ | 310/375 [10:01<02:06,  1.95s/it]

====================================================================================================
[310/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCOC1
Component 2 SMILES: CCCCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.979
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.966
Equilibrium pressure: 40.882 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.969
Equilibrium pressure: 40.000 kPa

Parsed:
Y1 : 0.966 -> 0.969
P  : 40.882 -> 40.0

 83%|████████▎ | 311/375 [10:03<02:04,  1.95s/it]

====================================================================================================
[311/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCOC1
Component 2 SMILES: CCCCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 0.996
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.993
Equilibrium pressure: 40.334 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.995
Equilibrium pressure: 40.000 kPa

Parsed:
Y1 : 0.993 -> 0.995
P  : 40.334 -> 40.0

 83%|████████▎ | 312/375 [10:05<02:03,  1.95s/it]

====================================================================================================
[312/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCOC1
Component 2 SMILES: CCCCCC
Operating temperature: 313.15 K
Liquid-phase mole fraction of component 1: 1.000
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 1.000
Equilibrium pressure: 40.200 kPa

Prediction:
Vapor-phase mole fraction of component 1: 1.000
Equilibrium pressure: 37.000 kPa

Parsed:
Y1 : 1.0 -> 1.0
P  : 40.2 -> 37.0

 83%|████████▎ | 313/375 [10:07<02:01,  1.96s/it]

====================================================================================================
[313/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCOC1
Component 2 SMILES: CCCCCC
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.000
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.000
Equilibrium pressure: 76.340 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.000
Equilibrium pressure: 40.300 kPa

Parsed:
Y1 : 0.0 -> 0.0
P  : 76.34 -> 40.3

 84%|████████▎ | 314/375 [10:09<01:59,  1.96s/it]

====================================================================================================
[314/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCOC1
Component 2 SMILES: CCCCCC
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.012
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.021
Equilibrium pressure: 77.092 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.039
Equilibrium pressure: 50.000 kPa

Parsed:
Y1 : 0.021 -> 0.039
P  : 77.092 -> 50.0

 84%|████████▍ | 315/375 [10:11<01:57,  1.95s/it]

====================================================================================================
[315/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCOC1
Component 2 SMILES: CCCCCC
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.048
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.075
Equilibrium pressure: 79.193 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.120
Equilibrium pressure: 50.000 kPa

Parsed:
Y1 : 0.075 -> 0.12
P  : 79.193 -> 50.0

 84%|████████▍ | 316/375 [10:13<01:55,  1.96s/it]

====================================================================================================
[316/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCOC1
Component 2 SMILES: CCCCCC
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.109
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.170
Equilibrium pressure: 82.670 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.282
Equilibrium pressure: 51.100 kPa

Parsed:
Y1 : 0.17 -> 0.282
P  : 82.67 -> 51.1

 85%|████████▍ | 317/375 [10:15<01:53,  1.96s/it]

====================================================================================================
[317/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCOC1
Component 2 SMILES: CCCCCC
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.203
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.271
Equilibrium pressure: 85.900 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.398
Equilibrium pressure: 53.000 kPa

Parsed:
Y1 : 0.271 -> 0.398
P  : 85.9 -> 53.0

 85%|████████▍ | 318/375 [10:17<01:51,  1.95s/it]

====================================================================================================
[318/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCOC1
Component 2 SMILES: CCCCCC
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.306
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.369
Equilibrium pressure: 88.440 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.492
Equilibrium pressure: 62.000 kPa

Parsed:
Y1 : 0.369 -> 0.492
P  : 88.44 -> 62.0

 85%|████████▌ | 319/375 [10:19<01:49,  1.96s/it]

====================================================================================================
[319/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCOC1
Component 2 SMILES: CCCCCC
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.399
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.447
Equilibrium pressure: 90.115 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.582
Equilibrium pressure: 64.000 kPa

Parsed:
Y1 : 0.447 -> 0.582
P  : 90.115 -> 64.0

 85%|████████▌ | 320/375 [10:21<01:47,  1.96s/it]

====================================================================================================
[320/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCOC1
Component 2 SMILES: CCCCCC
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.481
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.511
Equilibrium pressure: 91.125 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.633
Equilibrium pressure: 68.000 kPa

Parsed:
Y1 : 0.511 -> 0.633
P  : 91.125 -> 68.0

 86%|████████▌ | 321/375 [10:23<01:45,  1.96s/it]

====================================================================================================
[321/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCOC1
Component 2 SMILES: CCCCCC
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.579
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.585
Equilibrium pressure: 91.647 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.683
Equilibrium pressure: 72.000 kPa

Parsed:
Y1 : 0.585 -> 0.683
P  : 91.647 -> 72.0

 86%|████████▌ | 322/375 [10:25<01:43,  1.96s/it]

====================================================================================================
[322/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCOC1
Component 2 SMILES: CCCCCC
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.625
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.619
Equilibrium pressure: 91.600 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.669
Equilibrium pressure: 73.000 kPa

Parsed:
Y1 : 0.619 -> 0.669
P  : 91.6 -> 73.0

 86%|████████▌ | 323/375 [10:27<01:41,  1.96s/it]

====================================================================================================
[323/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCOC1
Component 2 SMILES: CCCCCC
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.707
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.682
Equilibrium pressure: 91.230 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.683
Equilibrium pressure: 73.090 kPa

Parsed:
Y1 : 0.682 -> 0.683
P  : 91.23 -> 73.09

 86%|████████▋ | 324/375 [10:29<01:39,  1.96s/it]

====================================================================================================
[324/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCOC1
Component 2 SMILES: CCCCCC
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.788
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.752
Equilibrium pressure: 90.365 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.819
Equilibrium pressure: 79.000 kPa

Parsed:
Y1 : 0.752 -> 0.819
P  : 90.365 -> 79.0

 87%|████████▋ | 325/375 [10:31<01:37,  1.96s/it]

====================================================================================================
[325/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCOC1
Component 2 SMILES: CCCCCC
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.860
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.819
Equilibrium pressure: 88.980 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.840
Equilibrium pressure: 79.000 kPa

Parsed:
Y1 : 0.819 -> 0.84
P  : 88.98 -> 79.0

 87%|████████▋ | 326/375 [10:33<01:35,  1.96s/it]

====================================================================================================
[326/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCOC1
Component 2 SMILES: CCCCCC
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.911
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.877
Equilibrium pressure: 87.375 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.900
Equilibrium pressure: 81.000 kPa

Parsed:
Y1 : 0.877 -> 0.9
P  : 87.375 -> 81.0

 87%|████████▋ | 327/375 [10:35<01:33,  1.96s/it]

====================================================================================================
[327/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCOC1
Component 2 SMILES: CCCCCC
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.953
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.930
Equilibrium pressure: 85.690 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.932
Equilibrium pressure: 76.000 kPa

Parsed:
Y1 : 0.93 -> 0.932
P  : 85.69 -> 76.0

 87%|████████▋ | 328/375 [10:37<01:32,  1.96s/it]

====================================================================================================
[328/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCOC1
Component 2 SMILES: CCCCCC
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.981
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.970
Equilibrium pressure: 84.250 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.979
Equilibrium pressure: 83.000 kPa

Parsed:
Y1 : 0.97 -> 0.979
P  : 84.25 -> 83.0

 88%|████████▊ | 329/375 [10:39<01:30,  1.96s/it]

====================================================================================================
[329/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCOC1
Component 2 SMILES: CCCCCC
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.997
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.995
Equilibrium pressure: 83.275 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.996
Equilibrium pressure: 83.000 kPa

Parsed:
Y1 : 0.995 -> 0.996
P  : 83.275 -> 83.0

 88%|████████▊ | 330/375 [10:41<01:28,  1.96s/it]

====================================================================================================
[330/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCOC1
Component 2 SMILES: CCCCCC
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 1.000
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 1.000
Equilibrium pressure: 83.100 kPa

Prediction:
Vapor-phase mole fraction of component 1: 1.000
Equilibrium pressure: 73.000 kPa

Parsed:
Y1 : 1.0 -> 1.0
P  : 83.1 -> 73.0

 88%|████████▊ | 331/375 [10:43<01:26,  1.96s/it]

====================================================================================================
[331/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCOC1
Component 2 SMILES: CCOC(=O)C
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.000
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.000
Equilibrium pressure: 55.858 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.000
Equilibrium pressure: 50.300 kPa

Parsed:
Y1 : 0.0 -> 0.0
P  : 55.858 -> 50.3

 89%|████████▊ | 332/375 [10:45<01:24,  1.96s/it]

====================================================================================================
[332/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCOC1
Component 2 SMILES: CCOC(=O)C
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.007
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.012
Equilibrium pressure: 56.160 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.015
Equilibrium pressure: 63.000 kPa

Parsed:
Y1 : 0.012 -> 0.015
P  : 56.16 -> 63.0

 89%|████████▉ | 333/375 [10:46<01:22,  1.96s/it]

====================================================================================================
[333/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCOC1
Component 2 SMILES: CCOC(=O)C
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.046
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.074
Equilibrium pressure: 57.492 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.079
Equilibrium pressure: 68.000 kPa

Parsed:
Y1 : 0.074 -> 0.079
P  : 57.492 -> 68.0

 89%|████████▉ | 334/375 [10:48<01:20,  1.96s/it]

====================================================================================================
[334/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCOC1
Component 2 SMILES: CCOC(=O)C
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.107
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.159
Equilibrium pressure: 59.500 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.182
Equilibrium pressure: 64.100 kPa

Parsed:
Y1 : 0.159 -> 0.182
P  : 59.5 -> 64.1

 89%|████████▉ | 335/375 [10:50<01:18,  1.96s/it]

====================================================================================================
[335/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCOC1
Component 2 SMILES: CCOC(=O)C
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.194
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.274
Equilibrium pressure: 62.400 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.282
Equilibrium pressure: 69.000 kPa

Parsed:
Y1 : 0.274 -> 0.282
P  : 62.4 -> 69.0

 90%|████████▉ | 336/375 [10:52<01:16,  1.96s/it]

====================================================================================================
[336/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCOC1
Component 2 SMILES: CCOC(=O)C
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.280
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.378
Equilibrium pressure: 65.115 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.383
Equilibrium pressure: 71.000 kPa

Parsed:
Y1 : 0.378 -> 0.383
P  : 65.115 -> 71.0

 90%|████████▉ | 337/375 [10:54<01:14,  1.96s/it]

====================================================================================================
[337/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCOC1
Component 2 SMILES: CCOC(=O)C
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.388
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.485
Equilibrium pressure: 67.754 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.503
Equilibrium pressure: 68.000 kPa

Parsed:
Y1 : 0.485 -> 0.503
P  : 67.754 -> 68.0

 90%|█████████ | 338/375 [10:56<01:12,  1.96s/it]

====================================================================================================
[338/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCOC1
Component 2 SMILES: CCOC(=O)C
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.473
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.574
Equilibrium pressure: 70.509 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.582
Equilibrium pressure: 73.000 kPa

Parsed:
Y1 : 0.574 -> 0.582
P  : 70.509 -> 73.0

 90%|█████████ | 339/375 [10:58<01:10,  1.96s/it]

====================================================================================================
[339/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCOC1
Component 2 SMILES: CCOC(=O)C
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.523
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.618
Equilibrium pressure: 71.880 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.618
Equilibrium pressure: 73.100 kPa

Parsed:
Y1 : 0.618 -> 0.618
P  : 71.88 -> 73.1

 91%|█████████ | 340/375 [11:00<01:08,  1.96s/it]

====================================================================================================
[340/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCOC1
Component 2 SMILES: CCOC(=O)C
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.610
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.695
Equilibrium pressure: 74.052 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.689
Equilibrium pressure: 79.000 kPa

Parsed:
Y1 : 0.695 -> 0.689
P  : 74.052 -> 79.0

 91%|█████████ | 341/375 [11:02<01:06,  1.96s/it]

====================================================================================================
[341/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCOC1
Component 2 SMILES: CCOC(=O)C
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.707
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.776
Equilibrium pressure: 76.462 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.763
Equilibrium pressure: 78.000 kPa

Parsed:
Y1 : 0.776 -> 0.763
P  : 76.462 -> 78.0

 91%|█████████ | 342/375 [11:04<01:04,  1.96s/it]

====================================================================================================
[342/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCOC1
Component 2 SMILES: CCOC(=O)C
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.797
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.846
Equilibrium pressure: 78.631 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.833
Equilibrium pressure: 80.000 kPa

Parsed:
Y1 : 0.846 -> 0.833
P  : 78.631 -> 80.0

 91%|█████████▏| 343/375 [11:06<01:02,  1.96s/it]

====================================================================================================
[343/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCOC1
Component 2 SMILES: CCOC(=O)C
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.874
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.906
Equilibrium pressure: 80.365 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.895
Equilibrium pressure: 81.000 kPa

Parsed:
Y1 : 0.906 -> 0.895
P  : 80.365 -> 81.0

 92%|█████████▏| 344/375 [11:08<01:00,  1.96s/it]

====================================================================================================
[344/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCOC1
Component 2 SMILES: CCOC(=O)C
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.926
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.946
Equilibrium pressure: 81.570 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.942
Equilibrium pressure: 83.000 kPa

Parsed:
Y1 : 0.946 -> 0.942
P  : 81.57 -> 83.0

 92%|█████████▏| 345/375 [11:10<00:58,  1.96s/it]

====================================================================================================
[345/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCOC1
Component 2 SMILES: CCOC(=O)C
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 0.955
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.966
Equilibrium pressure: 82.210 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.962
Equilibrium pressure: 81.000 kPa

Parsed:
Y1 : 0.966 -> 0.962
P  : 82.21 -> 81.0

 92%|█████████▏| 346/375 [11:12<00:56,  1.96s/it]

====================================================================================================
[346/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: C1CCOC1
Component 2 SMILES: CCOC(=O)C
Operating temperature: 333.15 K
Liquid-phase mole fraction of component 1: 1.000
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 1.000
Equilibrium pressure: 83.100 kPa

Prediction:
Vapor-phase mole fraction of component 1: 1.000
Equilibrium pressure: 80.000 kPa

Parsed:
Y1 : 1.0 -> 1.0
P  : 83.1 -> 80.0

 93%|█████████▎| 347/375 [11:14<00:54,  1.96s/it]

====================================================================================================
[347/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CC1=CC=CC=C1C
Component 2 SMILES: CC1CCCCC1
Operating temperature: 348.15 K
Liquid-phase mole fraction of component 1: 0.108
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.034
Equilibrium pressure: 42.391 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.128
Equilibrium pressure: 27.900 kPa

Parsed:
Y1 : 0.034 -> 0.128
P  : 42.391 -> 27.9

 93%|█████████▎| 348/375 [11:16<00:52,  1.96s/it]

====================================================================================================
[348/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CC1=CC=CC=C1C
Component 2 SMILES: CC1CCCCC1
Operating temperature: 348.15 K
Liquid-phase mole fraction of component 1: 0.150
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.048
Equilibrium pressure: 41.069 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.150
Equilibrium pressure: 25.080 kPa

Parsed:
Y1 : 0.048 -> 0.15
P  : 41.069 -> 25.08

 93%|█████████▎| 349/375 [11:18<00:50,  1.96s/it]

====================================================================================================
[349/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CC1=CC=CC=C1C
Component 2 SMILES: CC1CCCCC1
Operating temperature: 348.15 K
Liquid-phase mole fraction of component 1: 0.178
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.057
Equilibrium pressure: 40.223 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.162
Equilibrium pressure: 27.900 kPa

Parsed:
Y1 : 0.057 -> 0.162
P  : 40.223 -> 27.9

 93%|█████████▎| 350/375 [11:20<00:48,  1.96s/it]

====================================================================================================
[350/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CC1=CC=CC=C1C
Component 2 SMILES: CC1CCCCC1
Operating temperature: 348.15 K
Liquid-phase mole fraction of component 1: 0.208
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.067
Equilibrium pressure: 39.271 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.200
Equilibrium pressure: 27.330 kPa

Parsed:
Y1 : 0.067 -> 0.2
P  : 39.271 -> 27.33

 94%|█████████▎| 351/375 [11:22<00:46,  1.96s/it]

====================================================================================================
[351/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CC1=CC=CC=C1C
Component 2 SMILES: CC1CCCCC1
Operating temperature: 348.15 K
Liquid-phase mole fraction of component 1: 0.243
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.080
Equilibrium pressure: 38.223 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.233
Equilibrium pressure: 33.900 kPa

Parsed:
Y1 : 0.08 -> 0.233
P  : 38.223 -> 33.9

 94%|█████████▍| 352/375 [11:24<00:45,  1.96s/it]

====================================================================================================
[352/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CC1=CC=CC=C1C
Component 2 SMILES: CC1CCCCC1
Operating temperature: 348.15 K
Liquid-phase mole fraction of component 1: 0.277
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.092
Equilibrium pressure: 37.136 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.250
Equilibrium pressure: 28.300 kPa

Parsed:
Y1 : 0.092 -> 0.25
P  : 37.136 -> 28.3

 94%|█████████▍| 353/375 [11:26<00:43,  1.96s/it]

====================================================================================================
[353/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CC1=CC=CC=C1C
Component 2 SMILES: CC1CCCCC1
Operating temperature: 348.15 K
Liquid-phase mole fraction of component 1: 0.318
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.107
Equilibrium pressure: 35.856 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.300
Equilibrium pressure: 27.900 kPa

Parsed:
Y1 : 0.107 -> 0.3
P  : 35.856 -> 27.9

 94%|█████████▍| 354/375 [11:28<00:41,  1.96s/it]

====================================================================================================
[354/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CC1=CC=CC=C1C
Component 2 SMILES: CC1CCCCC1
Operating temperature: 348.15 K
Liquid-phase mole fraction of component 1: 0.348
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.119
Equilibrium pressure: 34.901 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.339
Equilibrium pressure: 34.390 kPa

Parsed:
Y1 : 0.119 -> 0.339
P  : 34.901 -> 34.39

 95%|█████████▍| 355/375 [11:30<00:39,  1.96s/it]

====================================================================================================
[355/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CC1=CC=CC=C1C
Component 2 SMILES: CC1CCCCC1
Operating temperature: 348.15 K
Liquid-phase mole fraction of component 1: 0.377
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.131
Equilibrium pressure: 34.004 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.329
Equilibrium pressure: 29.330 kPa

Parsed:
Y1 : 0.131 -> 0.329
P  : 34.004 -> 29.33

 95%|█████████▍| 356/375 [11:32<00:37,  1.96s/it]

====================================================================================================
[356/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CC1=CC=CC=C1C
Component 2 SMILES: CC1CCCCC1
Operating temperature: 348.15 K
Liquid-phase mole fraction of component 1: 0.394
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.138
Equilibrium pressure: 33.453 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.339
Equilibrium pressure: 29.130 kPa

Parsed:
Y1 : 0.138 -> 0.339
P  : 33.453 -> 29.13

 95%|█████████▌| 357/375 [11:33<00:35,  1.96s/it]

====================================================================================================
[357/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CC1=CC=CC=C1C
Component 2 SMILES: CC1CCCCC1
Operating temperature: 348.15 K
Liquid-phase mole fraction of component 1: 0.419
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.149
Equilibrium pressure: 32.661 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.369
Equilibrium pressure: 29.190 kPa

Parsed:
Y1 : 0.149 -> 0.369
P  : 32.661 -> 29.19

 95%|█████████▌| 358/375 [11:35<00:33,  1.96s/it]

====================================================================================================
[358/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CC1=CC=CC=C1C
Component 2 SMILES: CC1CCCCC1
Operating temperature: 348.15 K
Liquid-phase mole fraction of component 1: 0.432
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.155
Equilibrium pressure: 32.233 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.383
Equilibrium pressure: 33.190 kPa

Parsed:
Y1 : 0.155 -> 0.383
P  : 32.233 -> 33.19

 96%|█████████▌| 359/375 [11:37<00:31,  1.96s/it]

====================================================================================================
[359/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CC1=CC=CC=C1C
Component 2 SMILES: CC1CCCCC1
Operating temperature: 348.15 K
Liquid-phase mole fraction of component 1: 0.476
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.177
Equilibrium pressure: 30.815 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.403
Equilibrium pressure: 28.135 kPa

Parsed:
Y1 : 0.177 -> 0.403
P  : 30.815 -> 28.135

 96%|█████████▌| 360/375 [11:39<00:29,  1.96s/it]

====================================================================================================
[360/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CC1=CC=CC=C1C
Component 2 SMILES: CC1CCCCC1
Operating temperature: 348.15 K
Liquid-phase mole fraction of component 1: 0.520
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.200
Equilibrium pressure: 29.340 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.452
Equilibrium pressure: 27.900 kPa

Parsed:
Y1 : 0.2 -> 0.452
P  : 29.34 -> 27.9

 96%|█████████▋| 361/375 [11:41<00:27,  1.96s/it]

====================================================================================================
[361/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CC1=CC=CC=C1C
Component 2 SMILES: CC1CCCCC1
Operating temperature: 348.15 K
Liquid-phase mole fraction of component 1: 0.546
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.215
Equilibrium pressure: 28.478 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.482
Equilibrium pressure: 27.390 kPa

Parsed:
Y1 : 0.215 -> 0.482
P  : 28.478 -> 27.39

 97%|█████████▋| 362/375 [11:43<00:25,  1.96s/it]

====================================================================================================
[362/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CC1=CC=CC=C1C
Component 2 SMILES: CC1CCCCC1
Operating temperature: 348.15 K
Liquid-phase mole fraction of component 1: 0.555
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.220
Equilibrium pressure: 28.180 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.483
Equilibrium pressure: 27.900 kPa

Parsed:
Y1 : 0.22 -> 0.483
P  : 28.18 -> 27.9

 97%|█████████▋| 363/375 [11:45<00:23,  1.96s/it]

====================================================================================================
[363/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CC1=CC=CC=C1C
Component 2 SMILES: CC1CCCCC1
Operating temperature: 348.15 K
Liquid-phase mole fraction of component 1: 0.581
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.236
Equilibrium pressure: 27.291 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.509
Equilibrium pressure: 26.190 kPa

Parsed:
Y1 : 0.236 -> 0.509
P  : 27.291 -> 26.19

 97%|█████████▋| 364/375 [11:47<00:21,  1.96s/it]

====================================================================================================
[364/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CC1=CC=CC=C1C
Component 2 SMILES: CC1CCCCC1
Operating temperature: 348.15 K
Liquid-phase mole fraction of component 1: 0.612
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.256
Equilibrium pressure: 26.243 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.532
Equilibrium pressure: 27.320 kPa

Parsed:
Y1 : 0.256 -> 0.532
P  : 26.243 -> 27.32

 97%|█████████▋| 365/375 [11:49<00:19,  1.96s/it]

====================================================================================================
[365/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CC1=CC=CC=C1C
Component 2 SMILES: CC1CCCCC1
Operating temperature: 348.15 K
Liquid-phase mole fraction of component 1: 0.640
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.277
Equilibrium pressure: 25.230 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.552
Equilibrium pressure: 26.190 kPa

Parsed:
Y1 : 0.277 -> 0.552
P  : 25.23 -> 26.19

 98%|█████████▊| 366/375 [11:51<00:17,  1.96s/it]

====================================================================================================
[366/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CC1=CC=CC=C1C
Component 2 SMILES: CC1CCCCC1
Operating temperature: 348.15 K
Liquid-phase mole fraction of component 1: 0.673
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.304
Equilibrium pressure: 24.077 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.568
Equilibrium pressure: 26.130 kPa

Parsed:
Y1 : 0.304 -> 0.568
P  : 24.077 -> 26.13

 98%|█████████▊| 367/375 [11:53<00:15,  1.96s/it]

====================================================================================================
[367/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CC1=CC=CC=C1C
Component 2 SMILES: CC1CCCCC1
Operating temperature: 348.15 K
Liquid-phase mole fraction of component 1: 0.706
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.333
Equilibrium pressure: 22.858 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.608
Equilibrium pressure: 27.300 kPa

Parsed:
Y1 : 0.333 -> 0.608
P  : 22.858 -> 27.3

 98%|█████████▊| 368/375 [11:55<00:13,  1.96s/it]

====================================================================================================
[368/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CC1=CC=CC=C1C
Component 2 SMILES: CC1CCCCC1
Operating temperature: 348.15 K
Liquid-phase mole fraction of component 1: 0.743
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.370
Equilibrium pressure: 21.469 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.639
Equilibrium pressure: 26.190 kPa

Parsed:
Y1 : 0.37 -> 0.639
P  : 21.469 -> 26.19

 98%|█████████▊| 369/375 [11:57<00:11,  1.96s/it]

====================================================================================================
[369/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CC1=CC=CC=C1C
Component 2 SMILES: CC1CCCCC1
Operating temperature: 348.15 K
Liquid-phase mole fraction of component 1: 0.780
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.415
Equilibrium pressure: 20.029 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.669
Equilibrium pressure: 25.000 kPa

Parsed:
Y1 : 0.415 -> 0.669
P  : 20.029 -> 25.0

 99%|█████████▊| 370/375 [11:59<00:09,  1.96s/it]

====================================================================================================
[370/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CC1=CC=CC=C1C
Component 2 SMILES: CC1CCCCC1
Operating temperature: 348.15 K
Liquid-phase mole fraction of component 1: 0.812
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.459
Equilibrium pressure: 18.706 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.719
Equilibrium pressure: 25.090 kPa

Parsed:
Y1 : 0.459 -> 0.719
P  : 18.706 -> 25.09

 99%|█████████▉| 371/375 [12:01<00:07,  1.96s/it]

====================================================================================================
[371/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CC1=CC=CC=C1C
Component 2 SMILES: CC1CCCCC1
Operating temperature: 348.15 K
Liquid-phase mole fraction of component 1: 0.848
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.517
Equilibrium pressure: 17.264 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.752
Equilibrium pressure: 23.130 kPa

Parsed:
Y1 : 0.517 -> 0.752
P  : 17.264 -> 23.13

 99%|█████████▉| 372/375 [12:03<00:05,  1.96s/it]

====================================================================================================
[372/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CC1=CC=CC=C1C
Component 2 SMILES: CC1CCCCC1
Operating temperature: 348.15 K
Liquid-phase mole fraction of component 1: 0.875
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.570
Equilibrium pressure: 16.117 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.779
Equilibrium pressure: 23.095 kPa

Parsed:
Y1 : 0.57 -> 0.779
P  : 16.117 -> 23.095

 99%|█████████▉| 373/375 [12:05<00:03,  1.96s/it]

====================================================================================================
[373/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CC1=CC=CC=C1C
Component 2 SMILES: CC1CCCCC1
Operating temperature: 348.15 K
Liquid-phase mole fraction of component 1: 0.911
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.656
Equilibrium pressure: 14.543 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.853
Equilibrium pressure: 20.900 kPa

Parsed:
Y1 : 0.656 -> 0.853
P  : 14.543 -> 20.9

100%|█████████▉| 374/375 [12:07<00:01,  1.96s/it]

====================================================================================================
[374/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CC1=CC=CC=C1C
Component 2 SMILES: CC1CCCCC1
Operating temperature: 348.15 K
Liquid-phase mole fraction of component 1: 0.938
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.737
Equilibrium pressure: 13.300 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.879
Equilibrium pressure: 19.090 kPa

Parsed:
Y1 : 0.737 -> 0.879
P  : 13.3 -> 19.09

100%|██████████| 375/375 [12:09<00:00,  1.94s/it]

====================================================================================================
[375/375]
Task : isothermal

Input:
Task: Predict the vapor-liquid equilibrium state of a binary mixture under isothermal conditions.
Given:
Component 1 SMILES: CC1=CC=CC=C1C
Component 2 SMILES: CC1CCCCC1
Operating temperature: 348.15 K
Liquid-phase mole fraction of component 1: 0.968
Please predict:
1. Vapor-phase mole fraction of component 1
2. Equilibrium pressure


Ground Truth:
Vapor-phase mole fraction of component 1: 0.846
Equilibrium pressure: 11.930 kPa

Prediction:
Vapor-phase mole fraction of component 1: 0.933
Equilibrium pressure: 19.090 kPa

Parsed:
Y1 : 0.846 -> 0.933
P  : 11.93 -> 19.09

Results saved to ./等温数据/data/训练后数据/test_isothermal_62.json

============================================================
Overall Y1
Samples : 375
MAE  : 0.085547
RMSE : 0.133797
R²   : 0.814421

Isobaric Y1: No valid samples

Isobaric Temperature: No valid samples

============================================================
Isothermal Y1
Samples : 375
MAE  : 0.085547
RMSE : 0.133797
R²   : 0.814421

============================================================
Isothermal Pressure
Samples : 375
MAE  : 6.738568
RMSE : 9.717675
R²   : 0.830284

In [11]:
import pandas as pd
import re
import numpy as np
# =========================
# 1. 转成DataFrame
# =========================
df = pd.DataFrame(results_all)
# =========================
# 2. 从input提取信息
# =========================
def extract_info(input_text):
    input_text = str(input_text)
    smiles1 = None
    smiles2 = None
    x1 = None
    pressure = None
    temperature = None
    # Component 1
    m = re.search(
        r"Component 1 SMILES:\s*(.+)",
        input_text,
        re.IGNORECASE
    )
    if m:
        smiles1 = m.group(1).split("\n")[0].strip()
    # Component 2
    m = re.search(
        r"Component 2 SMILES:\s*(.+)",
        input_text,
        re.IGNORECASE
    )
    if m:
        smiles2 = m.group(1).split("\n")[0].strip()
    # Liquid composition
    m = re.search(
        r"Liquid-phase mole fraction of component 1:\s*([-+]?\d*\.?\d+)",
        input_text,
        re.IGNORECASE
    )
    if m:
        x1 = float(m.group(1))
    # Pressure
    m = re.search(
        r"Operating pressure:\s*([-+]?\d*\.?\d+)",
        input_text,
        re.IGNORECASE
    )
    if m:
        pressure = float(m.group(1))
    # Temperature
    m = re.search(
        r"Operating temperature:\s*([-+]?\d*\.?\d+)",
        input_text,
        re.IGNORECASE
    )
    if m:
        temperature = float(m.group(1))
    return pd.Series(
        [
            smiles1,
            smiles2,
            x1,
            pressure,
            temperature
        ],
        index=[
            "SMILES_1",
            "SMILES_2",
            "X1",
            "Input_P(kPa)",
            "Input_T(K)"
        ]
    )
# 提取信息
df[
    [
        "SMILES_1",
        "SMILES_2",
        "X1",
        "Input_P(kPa)",
        "Input_T(K)"
    ]
] = df["input"].apply(extract_info)
# =========================
# 3. 调整列顺序
# =========================
df_save = pd.DataFrame()
df_save["Task"] = df["task_type"]
df_save["SMILES_1"] = df["SMILES_1"]
df_save["SMILES_2"] = df["SMILES_2"]
df_save["Input_X1"] = df["X1"]
df_save["Input_P(kPa)"] = df["Input_P(kPa)"]
df_save["Input_T(K)"] = df["Input_T(K)"]
df_save["True_Y1"] = df["true_Y1"]
df_save["Pred_Y1"] = df["pred_Y1"]
df_save["Error_Y1"] = df["err_Y1"]
#df_save["True_T(K)"] = df["true_T"]
#df_save["Pred_T(K)"] = df["pred_T"]
#df_save["Error_T(K)"] = df["err_T"]
df_save["True_P(kPa)"] = df["true_P"]
df_save["Pred_P(kPa)"] = df["pred_P"]
df_save["Error_P(kPa)"] = df["err_P"]
#df_save["Raw Prediction"] = df["raw_prediction"]
# ========================
# 4. 保存Excel
# ========================
save_path = "./等温数据/data/训练后数据/excel/test_isothermal_62.xlsx"
df_save.to_excel(
    save_path,
    index=False
)
print(f"保存成功：{save_path}")
df_save

保存成功：./等温数据/data/训练后数据/excel/test_isothermal_62.xlsx

,Task,SMILES_1,SMILES_2,Input_X1,Input_P(kPa),Input_T(K),True_Y1,Pred_Y1,Error_Y1,True_P(kPa),Pred_P(kPa),Error_P(kPa)
0,isothermal,CCCCCCC,CCC(CC)O,0.000,None,358.15,0.000,0.000,0.000,31.310,27.390,3.920
1,isothermal,CCCCCCC,CCC(CC)O,0.011,None,358.15,0.060,0.053,0.007,33.030,38.090,5.060
2,isothermal,CCCCCCC,CCC(CC)O,0.026,None,358.15,0.135,0.122,0.013,35.430,35.130,0.300
3,isothermal,CCCCCCC,CCC(CC)O,0.058,None,358.15,0.249,0.239,0.010,39.730,39.100,0.630
4,isothermal,CCCCCCC,CCC(CC)O,0.158,None,358.15,0.449,0.450,0.001,50.090,53.100,3.010
...,...,...,...,...,...,...,...,...,...,...,...,...
370,isothermal,CC1=CC=CC=C1C,CC1CCCCC1,0.848,None,348.15,0.517,0.752,0.235,17.264,23.130,5.866
371,isothermal,CC1=CC=CC=C1C,CC1CCCCC1,0.875,None,348.15,0.570,0.779,0.209,16.117,23.095,6.978
372,isothermal,CC1=CC=CC=C1C,CC1CCCCC1,0.911,None,348.15,0.656,0.853,0.197,14.543,20.900,6.357
373,isothermal,CC1=CC=CC=C1C,CC1CCCCC1,0.938,None,348.15,0.737,0.879,0.142,13.300,19.090,5.790
374,isothermal,CC1=CC=CC=C1C,CC1CCCCC1,0.968,None,348.15,0.846,0.933,0.087,11.930,19.090,7.160

In [12]:
#train_file_path = "./等温数据/data/train_isothermal_42.jsonl"
#save_path = "./等温数据/data/train_isothermal_42.json"
#results_all = batch_predict_mixed_vle(
#    test_file_path=train_file_path,
#    save_path=save_path,
#    max_samples= None
#)